### PR TITLE
Add BillEase installment option available for Dragonpay in the Philip…

### PR DESCRIPTION
**Pull request by jerieldragonpay**
…pines

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible. (As long as the icon they [Billease] provided was used)

If this pull request is not adding new icons, you can remove this checklist.

@larouxn created new branch based on the latest master.

Old branch https://github.com/activemerchant/payment_icons/pull/481

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
LTGM! Thanks for the clean PR.
Screenshot 2021-09-21 135100

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋  Ran into a few release pipeline issues. Hoping to have this live by end of next week, potentially sooner.

**Comment by jerieldragonpay** [comment]
Thank you for the update. Appreciate it very much.

**Comment by larouxn** [comment]
👋 Hello again, your new icon should be live everywhere now.

**Pull request merged**
