### PR TITLE
Addition of icons for Przelew24, ePayments, PaySera and PaySafeCard.

### PR DESCRIPTION
**Pull request by et-altapay-com**

### CODE REVIEW

**Comment by millingab** [comment]
@et-altapay-com PaySera and Przelew24 violates the style guide for payment icons set by Shopify. 1. Add a white background to the Paysera icon
2. Przelew24 does not pass the readability test. (Recommend steps: only have at most 3 characters in the logo)

**Comment by et-altapay-com** [comment]
The icons were corrected.

**Comment by millingab** [comment]
@et-altapay-com you have a conflict here. Can you resolve this conflict ?
The reason for conflict is that you forgot to rebase your branch off the most recent master branch before committing your changes.

**Comment by et-altapay-com** [comment]
The conflict was solved.

**Pull request merged**
