### PR TITLE
Sika updated icons

### PR DESCRIPTION
**Pull request by sarahsp-sika**
## Why are you adding this icons?
I'm adding these icons because Sika is a Shopify Payments Partner for HSA/FSA spending, and we are going through a brand redesign where the look and feel of our flow is changing, including the icons.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: 
[Here](https://www.figma.com/file/kSAQqHP5t2TaD461nkA5dd/Sika-Brand-Kit-for-Shopify-Merchants?type=design&node-id=302%3A642&mode=design&t=GwMCZiyQxg9vVLms-1) is a link to the Sika Brand Kit for Shopify Merchants

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
sikascreenshot
sikahsascreenshot
sikafsascreenshot

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
Adeniyi Adeyemi

What's the expected date of this change to deploy on Shopify?
We would like to resubmit our application with our entire branded redesign, it will have to be approved and then go live.
Because we already use two icons, and I am replacing them, those two icons would go live when this would be approved.

### CODE REVIEW

**Comment by sarahsp-sika** [comment]
I am still in the process of adding our brand guideline information, and have listed this PR as a draft, I hope that is okay! I will mark it ready for review when it is good to go.

**Comment by sarahsp-sika** [comment]
This PR is good to go now!

**Comment by sarahsp-sika** [comment]
Hello @Jacquesattaque, I was just wondering when the next deploy will be/ when to expect these icons available. Thank you!!

**Comment by Jacquesattaque** [comment]
@sarahsp-sika We aim to do a release on the first Wednesday of every month. The next release is tentatively scheduled for September 6.

**Pull request merged**
