### PR TITLE
netprotections icons

### PR DESCRIPTION
**Pull request by kkasamoto**
## Why are you adding this icons?
I'm adding/updating this icon(s) because I'm developing payment app gateway which allows paying with Netprotections.

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
The icons look good; please update the names to remove the underscores. You also have some automated checks that are failing.

**Comment by kkasamoto** [comment]
I made some revisions. Would you be able to check them?

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Why such a huge diff between the previous YML file and this update? You just needed to remove the underscores. Please revert, make the one required change, and resubmit.

**Comment by kkasamoto** [comment]
Thanks for checking. I fixed.

**Comment by Jacquesattaque** [comment]
Much better! We just did a release so you may have some conflicts to resolve. Once those are resolved, I'll approve.

**Comment by kkasamoto** [comment]
I resolved conflicts.

**Comment by kkasamoto** [comment]
wait

**Comment by kkasamoto** [comment]
Could you check it?

**Comment by adeniyiao** [comment]
Hi @kkasamoto , 

Could you also fix the issue with test failure please. Thanks

image

**Comment by kkasamoto** [comment]
Thanks. I fixed it.

**Comment by kkasamoto** [comment]
I fixed some test failures.

**Comment by kkasamoto** [comment]
Hi, Could you run the workflow again?

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
