### PR TITLE
added pse icon

### PR DESCRIPTION
**Pull request by Maxi-TD**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" viewBox="0 0 38 24" aria-labelledby="pi-pse" role="img" fill="none" xmlns="http://www.w3.org/2000/svg"><title id="pi-pse">PSE</title><rect width="38" height="24" rx="2" fill="#fff"/><path d="M26.833 14.932h-3.305a.19.19 0 01-.188-.191.19.19 0 01.188-.192h3.288c.125-.026.993-.25 1.032-1.289.039-1.03-.54-1.134-.635-1.144h-2.12c-.852-.144-1.03-.925-1.004-1.34-.005-1.079.887-1.562 1.361-1.666a.203.203 0 01.04-.004h2.976a.19.19 0 01.188.191.19.19 0 01-.188.192h-2.953c-.144.037-1.055.313-1.048 1.292v.014c-.002.033-.041.805.675.938h2.093c.01 0 1.047.08.993 1.541a1.694 1.694 0 01-1.358 1.656l-.035.002zM33.061 14.953h-3.05c-.006 0-.013 0-.02-.002-.401-.043-1.167-.329-1.183-1.095-.018-.814.517-3.288.54-3.393.002-.009.003-.017.007-.025.018-.052.466-1.254 1.46-1.254h2.194c.017 0 .035.002.052.008.04.011.939.285.939 1.076 0 .663-.19 1.787-.2 1.834a.188.188 0 01-.182.158l-4.245.036c-.107.616-.196 1.233-.189 1.551.014.594.745.71.84.723h3.039a.19.19 0 01.187.191.192.192 0 01-.189.192zm-3.35-4.394c-.022.098-.147.685-.271 1.353l4.014-.035c.053-.333.168-1.122.168-1.61 0-.449-.527-.66-.645-.7h-2.163c-.694 0-1.061.882-1.104.992zM17.804 17.465l-.034-.003a.19.19 0 01-.15-.222l.598-3.372c.15-.844.302-1.687.416-2.32.058-.316.105-.58.14-.765.029-.153.048-.252.068-.319l-.004-.001c.211-.591.872-1.224 1.359-1.303a232.172 232.172 0 002.151-.003c.182-.004 1.155.371 1.041 1.157 0 .006 0 .014-.002.02l-.523 3.26a.095.095 0 01-.005.02c-.012.042-.287 1.004-1.202 1.285a.163.163 0 01-.048.008l-1.929.056-.022-.001c-.03-.003-.64-.07-1.13-.7-.208 1.164-.416 2.331-.542 3.045a.184.184 0 01-.182.158zm.824-3.75c.381.741.97.852 1.058.865l1.889-.055c.657-.216.895-.92.922-1.006l.52-3.236c.053-.361-.489-.747-.711-.744l-1.017.002h-.73c-.136 0-.234 0-.306-.005-.318.055-.883.57-1.058 1.05a382.72 382.72 0 00-.567 3.128z" fill="#0660AA"/><path d="M15.269 8.349a.528.528 0 01-.523.534.528.528 0 01-.523-.534.53.53 0 01.523-.535c.289 0 .523.239.523.535zM13.56 7.067a.528.528 0 00.523-.533A.528.528 0 0013.56 6a.528.528 0 00-.523.534c0 .294.234.533.523.533zM12.892 8.349a.528.528 0 01-.523.534.53.53 0 01-.524-.534.53.53 0 01.524-.535.53.53 0 01.523.535zM14.684 16.157a.528.528 0 00.524-.534.528.528 0 00-.524-.534.528.528 0 00-.523.534c0 .295.235.534.524.534zM13.557 14.451a.528.528 0 00.523-.534.528.528 0 00-.523-.533.528.528 0 00-.523.534c0 .294.234.533.523.533zM11.245 14.36c.24 0 .434-.199.434-.443a.437.437 0 00-.434-.441.437.437 0 00-.432.441c0 .244.193.442.432.442zM12.835 15.623a.438.438 0 01-.433.442.438.438 0 01-.433-.442c0-.244.194-.442.433-.442s.433.198.433.442zM11.216 17.935c.239 0 .433-.198.433-.442a.437.437 0 00-.433-.441.437.437 0 00-.433.441c0 .244.194.442.433.442zM10.094 15.965a.339.339 0 00.336-.342.339.339 0 00-.336-.342.339.339 0 00-.335.342c0 .189.15.342.335.342zM5.969 12.386a.339.339 0 00.335-.343.339.339 0 00-.335-.342.339.339 0 00-.336.342c0 .19.15.343.336.343zM6.57 10.561a.339.339 0 00.335-.342.339.339 0 00-.336-.342.339.339 0 00-.335.342c0 .19.15.342.335.342zM8.042 8.349c0 .189-.15.342-.335.342a.339.339 0 01-.336-.342c0-.189.15-.342.336-.342a.337.337 0 01.335.342zM9.196 6.574c0 .19-.15.343-.335.343a.339.339 0 01-.336-.343c0-.189.15-.342.336-.342.185 0 .335.153.335.342zM8.893 17.835a.339.339 0 00.335-.342.339.339 0 00-.335-.342.339.339 0 00-.335.342c0 .19.15.342.335.342zM7.739 15.965a.339.339 0 00.335-.342.339.339 0 00-.335-.342.339.339 0 00-.335.342c0 .189.15.342.335.342zM6.553 14.26a.339.339 0 00.336-.343.339.339 0 00-.336-.342.339.339 0 00-.335.342c0 .19.15.343.335.343zM5.92 15.8a.174.174 0 00.172-.177.174.174 0 00-.172-.176.174.174 0 00-.173.176c0 .097.077.176.173.176zM4.84 14.094a.174.174 0 00.172-.177.174.174 0 00-.173-.176.174.174 0 00-.172.176c0 .098.077.177.172.177zM4.347 12.011a.175.175 0 01-.173.177A.175.175 0 014 12.01c0-.096.078-.176.173-.176.095 0 .174.08.174.176zM4.79 10.398a.174.174 0 00.174-.176.174.174 0 00-.173-.176.174.174 0 00-.173.176c0 .097.077.176.173.176zM5.96 8.542a.174.174 0 00.172-.176.174.174 0 00-.172-.177.174.174 0 00-.173.177c0 .097.077.176.173.176zM8.877 14.36c.239 0 .433-.199.433-.443a.437.437 0 00-.433-.441.437.437 0 00-.433.441c0 .244.193.442.433.442zM7.658 12.49c.239 0 .433-.197.433-.441a.437.437 0 00-.433-.442.437.437 0 00-.433.442c0 .244.194.441.433.441zM9.293 10.22a.438.438 0 01-.433.44.438.438 0 01-.433-.44c0-.245.194-.443.433-.443.24 0 .433.198.433.442zM10.062 8.79c.239 0 .433-.197.433-.441a.437.437 0 00-.433-.442.437.437 0 00-.433.442c0 .244.194.442.433.442zM11.2 6.984c.239 0 .432-.198.432-.441A.437.437 0 0011.2 6.1a.437.437 0 00-.433.442c0 .243.194.441.433.441zM10.032 12.582a.528.528 0 00.523-.534.528.528 0 00-.523-.533.528.528 0 00-.523.534c0 .294.234.533.523.533zM11.2 10.753a.528.528 0 00.523-.534.528.528 0 00-.523-.533.528.528 0 00-.523.533c0 .295.234.534.523.534zM13.557 18.027a.528.528 0 00.523-.534.528.528 0 00-.523-.533.528.528 0 00-.523.533c0 .295.234.534.523.534z" fill="#FDB718"/><path d="M18.046 11.86h-7.75v.328h7.75v-.328zM14.024 10.056h-2.437v.328h2.437v-.328z" fill="#FDB718"/><path d="M15.071 12.169l-1.341-2.113h.374l1.341 2.113h-.374zM15.207 13.754h-1.242v.328h1.242v-.328z" fill="#FDB718"/><path d="M14.912 14.082l1.113-1.914h.32l-1.111 1.914h-.322z" fill="#FDB718"/><rect x=".5" y=".5" width="37" height="23" rx="1.5" stroke="#000" stroke-opacity=".07"/></svg>

```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Please use our provided template. The rounded corners on your icon don't match our standard.

**Comment by Maxi-TD** [comment]
Hi @Jacquesattaque, could you give me a hand with this?

**Comment by Jacquesattaque** [comment]
@adeniyiao Can you have a look and see why this is failing?

**Comment by adeniyiao** [comment]
Hi @Maxi-TD , there's a space in the parenthesis that is causing the CI Test failure. Kindly correct.

image

Screenshot 2023-07-28 at 11 00 56 AM

**Review by Maxi-TD — COMMENTED** [review]
fixed

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
