### PR TITLE
Add Biller Pay.nl Version

### PR DESCRIPTION
**Pull request by kevinverschoor**
## Why are you adding this icon?
I'm adding this icon because we at Pay. want to make a Biller payment app for Shopify and need the logo for this.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [x] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon with the black background

Screenshot from 2022-11-11 10-30-00

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
**We used to have a partner manager at Shopify but since they quit we haven't gotten anybody else to work with.**

What's the expected date of this change to deploy on Shopify?
**As soon as the logo is approved we intent to make the Payment app on Shopify**

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Our guidelines state a preference for white backgrounds on payment icons; as Biller does present its logo on a white background, please resubmit on a white background. The vectors also have some strange artifacts, so please take care to draw your icon using only the necessary vectors.

**Comment by kevinverschoor** [comment]
The background is changed to white.

**Comment by Jacquesattaque** [comment]
@kevinverschoor Did you redraw this logo yourself or get it from Biller? On close inspection the paths don't match the SVG logo they have on their site.

**Comment by kevinverschoor** [comment]
@Jacquesattaque 

Just to be sure I changed the logo in the PR. 
Took the one from their website and replaced the one we had in the SVG.

Hope it's better like this.

Screenshot from 2022-12-19 14-58-19

**Comment by Jacquesattaque** [comment]
Thanks @kevinverschoor, payment icon looks great. Just resolve conflicts and I'll approve and merge.

**Comment by kevinverschoor** [comment]
Done!

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
