### PR TITLE
RCS icon

### PR DESCRIPTION
**Pull request by onahkenneth**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by tauthomas01** [comment]
This looks good.

Can you rebase this branch off `master`?

**Comment by onahkenneth** [comment]
@tauthomas01 
Rebase done

**Comment by tauthomas01** [comment]
@onahkenneth Can you rebase it again? The `master` branch just updated. Sorry about that.

**Comment by onahkenneth** [comment]
@tauthomas01 Rebase done.

**Comment by tauthomas01** [comment]
@onahkenneth I see other files from other branches. I think the best is to recreate the PR. Can you do that?

**Comment by onahkenneth** [comment]
@tauthomas01 
New PR created

https://github.com/activemerchant/payment_icons/pull/392

**Pull request closed without merging**
