### PR TITLE
Add Simple Pay logo

### PR DESCRIPTION
**Pull request by dalindev**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
Screenshot 2023-12-15 at 5 38 05 PM

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify? ASAP 👍

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
You have some automated checks to clear. Is there a version of this icon that could be submitted on a white background?

**Comment by dalindev** [comment]
> You have some automated checks to clear. Is there a version of this icon that could be submitted on a white background?

Is it the background that the CI failed? I will ask our designer for a white background version.

**Comment by Jacquesattaque** [comment]
@dalindev No, the background wasn't causing the CI failure. I'll tag @adeniyiao to help if you can't find the source of the error.

**Comment by dalindev** [comment]
@Jacquesattaque , @adeniyiao , yeah are we able to run the test locally? Not sure what is missing, thank you

**Comment by dalindev** [comment]
@Jacquesattaque Hey 👋 , anyone can help with the CI thing? is it because of the svg or? thanks because we are going to launch with a customer in Jan, 2024 🙇

**Comment by Jacquesattaque** [comment]
cc @dannye0231 are you able to take a look?

**Comment by dannye0231** [comment]
> cc @dannye0231 are you able to take a look?

I took a look into the errors but can't seem to narrow down why exactly those tests are failing.  I'll ask @adeniyiao to take a further look with me when we're prepping for the next payment icon release.

**Comment by dalindev** [comment]
Screenshot 2024-01-02 at 9 04 55 AM
Seems the test failed before started? If we don't have a solution maybe I can re-submit this with a new branch? thanks

@adeniyiao

**Comment by adeniyiao** [comment]
Hi @dalindev , we are investigating the issue as it affects some other PR. We'll get back to you before end of week with an update.

**Comment by adeniyiao** [comment]
Hi @dalindev,  we addressed the ruby version issue causing the failure in this repo, therefore we need you to rebase your branch `real-simple-labs:simplepay` with `activemerchant/master` to fix the CI failure. Thanks.

**Comment by dalindev** [comment]
> Hi @dalindev, we addressed the ruby version issue causing the failure in this repo, therefore we need you to rebase your branch `real-simple-labs:simplepay` with `activemerchant/master` to fix the CI failure. Thanks.

I just did a rebase, could you run the CI for this one, thank you!

**Review by hellicarusprime — APPROVED** [review]

**Comment by dalindev** [comment]
@hellicarusprime, thanks for the update. When can we expect this to be merged and start using the logo? Thanks.

**Comment by hellicarusprime** [comment]
Hi @dalindev The release is scheduled for the first Wednesday of every month.

**Comment by dalindev** [comment]
@hellicarusprime, it appears that there haven't been any releases yet this month. Could you please merge this one? We're preparing for a client to go live with Simple Pay next week, and including the new logo in this month's release would be crucial for their launch, thanks for your help! 🎉 🙇

**Comment by hellicarusprime** [comment]
Cc: @adeniyiao

**Comment by adeniyiao** [comment]
Hi @dalindev , we are planning the next release for this month for early next week.

**Comment by dannye0231** [comment]
Hi @dalindev, I tried to re-base this PR for you but I do not have access to the source Git repository.  Would you be able to re-base this PR for me? 

Thank you

**Comment by dalindev** [comment]
@dannye0231 just updated, thanks!

**Comment by dalindev** [comment]
@dannye0231 👋 we have a merchant to go live next week, is this going to be merged today? We have been asking when it will be merged since last week 🤔

**Comment by dannye0231** [comment]
Hi @dalindev ,  it doesn't look like we were able to include it in time for yesterday's release.  For the sake of time, I've scheduled an ad-hoc release for next Wednesday just to get you live sooner then the Feb 7th release date.

**Comment by dalindev** [comment]
@dannye0231 appreciated the help, I also added you to our forked repo, I will be checking early next week then. thanks again! ❤️ 🙇

**Comment by dalindev** [comment]
@dannye0231 just did a rebase, let me know if this is good 🚀 , thanks

**Comment by dalindev** [comment]
@dannye0231 in the admin dashboard I can see the SimplePay icon, but in the checkout it is like this, is this normal? thanks

Screenshot 2024-01-19 at 1 40 38 PM

**Comment by dannye0231** [comment]
@dalindev are you able to try again and tell me if it now displays?  I see that the final commit into Prod occurred at 1:44pm EST.  

If its still not displaying, then can you please provide me with your test Shop ID?

**Comment by dalindev** [comment]
@dannye0231 just checked, all is good now, probably CDN cache or something. thank you! 🙇 👍

**Pull request merged**
