### PR TITLE
Add payrexx requested icons

### PR DESCRIPTION
**Pull request by sven-otziger**
## Why are you adding these icons?
I'm adding/updating these icons because we as a payment service provider are offering these payment methods and would like to offer them in Shopify as well.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines:

- https://www.figma.com/community/file/1215439650104209045/centi-brand-guidelines
- https://reka.ch/en/rekamoney/about-us/media/press
- The logo for the payment method Bank Transfer was created internally.

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
comparison_bank_transfer_black_cropped
comparison_bank_transfer_white_cropped
comparison_centi_black_cropped
comparison_centi_white_cropped
comparison_reka_black_cropped
comparison_reka_white_cropped

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
We don't have a direct contact at Shopify. We are just acting as a Shopify partner.
 

What's the expected date of this change to deploy on Shopify?
We would like the icons released at your earliest convenience.

### CODE REVIEW

**Comment by hellicarusprime** [comment]
Hi @sven-otziger, `Bank transfer` is overly generic for a name and label. Who is the payment provider? We also no longer allow underscores in names. [See our contributing guidelines](https://github.com/activemerchant/payment_icons/issues/1152#issue-2176772333).

**Comment by hellicarusprime** [comment]
Cc: @adeniyiao—what are your thoughts here?

**Comment by hellicarusprime** [comment]
> Hi @hellicarusprime @adeniyiao I updated the pointed out issues.

Hi @sven-otziger Can you please update the name of the SVG to be the same as the name entered in db/payment_icons.yml? The SVG still contains underscores.

**Review by hellicarusprime — APPROVED** [review]

**Review by Lovedanihonjin — CHANGES_REQUESTED** [review]
CI checks failed due to {:message=>"The 'centi' SVG file does not have the appropriate <title> value"}. 

Please fix the SVG format and make sure it follows the following [format](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#template).

Also, please rebase when committing your next change.

**Review by Lovedanihonjin — APPROVED** [review]
Looks great!

**Review by Lovedanihonjin — CHANGES_REQUESTED** [review]
The CI checks failed with the following errors `{:message=>"The 'payrexxbanktransfer' SVG file does not have the appropriate <title> value"}.' Please ensure that the SVG format meets the requirements and resolve.

**Review by Lovedanihonjin — CHANGES_REQUESTED** [review]
CI checks failed again with the following errors: `PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:81]:
{:message=>"The 'payrexxbanktransfer' SVG file does not have the appropriate 'id' value on the <title> tag"}.`

You can find the SVG format requirements [here.](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons)

**Review by Lovedanihonjin — APPROVED** [review]

**Comment by Lovedanihonjin** [comment]
Awesome. Thanks for your changes. Approved. Next deploy is on June 5.

**Pull request merged**
