### PR TITLE
directa24 icon added

### PR DESCRIPTION
**Pull request by Maxi-TD**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" fill="none" aria-labelledby="pi-directa24" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_10_569)"><path d="M38 0H0v24h38V0z" fill="#fff"/><path d="M18.098 16.71v-1.097a6.242 6.242 0 01-1.285-.25 3.39 3.39 0 01-1.024-.508l.453-1.218c.32.218.68.39 1.078.52.403.124.825.187 1.266.187.469 0 .805-.07 1.004-.219.21-.145.312-.324.312-.54 0-.187-.07-.339-.207-.456-.136-.121-.386-.219-.746-.29l-1.14-.241c-1.258-.266-1.887-.91-1.887-1.938 0-.558.2-1.031.59-1.414.394-.387.925-.629 1.586-.73V7.379h1.234v1.117c.367.04.715.121 1.047.25.332.125.613.297.84.508l-.457 1.137c-.516-.43-1.18-.649-1.989-.649-.394 0-.707.082-.945.242-.226.16-.34.364-.34.618 0 .187.067.335.207.449.137.113.371.207.703.281l1.133.238c1.297.274 1.946.907 1.946 1.899 0 .562-.2 1.031-.598 1.394-.395.367-.91.602-1.547.711v1.137h-1.234z" fill="#000"/><path fill-rule="evenodd" clip-rule="evenodd" d="M7.434 3.2h22.398c.91 0 1.652.718 1.652 1.6v1.688h.551V4.801c0-1.18-.988-2.133-2.203-2.133H7.434c-1.215 0-2.204.953-2.204 2.133v14.398c0 1.18.989 2.133 2.204 2.133h22.398c1.215 0 2.203-.953 2.203-2.133v-1.687h-.55v1.687c0 .883-.743 1.602-1.653 1.602H7.434c-.91 0-1.653-.719-1.653-1.602V4.801c0-.883.742-1.602 1.653-1.602z" fill="#000"/><path fill-rule="evenodd" clip-rule="evenodd" d="M27.902 11.645a.362.362 0 00-.367.355c0 .195.164.355.367.355h5.414l-1.168 1.075a.347.347 0 00-.011.504.368.368 0 00.515.011l1.836-1.687a.347.347 0 00.117-.258.348.348 0 00-.117-.258l-1.836-1.687a.368.368 0 00-.515.011.347.347 0 00.011.504l1.168 1.075h-5.414z" fill="#000"/><rect opacity=".07" x=".5" y=".5" width="37" height="23" rx="1.5" stroke="#000"/></g><defs><clipPath id="clip0_10_569"><path fill="#fff" d="M0 0h38v24H0z"/></clipPath></defs></svg>

```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by dmrkv — DISMISSED** [review]
There are some problems with the icon:
- white background all across the icon (should not be outside of border)
- border is with different color

you can check [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file for more info

**Comment by Maxi-TD** [comment]
Hi ther! @dmrkv 
I just adjusted the icon so it match the required specifications.
I hope that now it's fine.

**Comment by Maxi-TD** [comment]
Hi @dmrkv! could you help me with this?

**Comment by Jacquesattaque** [comment]
@Maxi-TD The icon looks fine — I would consider increasing the weight of the black rounded rectangle in your logo as these icons can scale down. But if you're fine with that, it's good to proceed. You have some automated checks to clear and then we can approve.

**Comment by Maxi-TD** [comment]
@Jacquesattaque, we would like to proceed directly with uploading the logo, it looks good to us. But it is not clear to me how to solve the automated check, could you give me a hand with that?

**Comment by Jacquesattaque** [comment]
@adeniyiao Can you have a look?

**Comment by adeniyiao** [comment]
Hi @Jacquesattaque , I did a re-run of the checks and all passed now.

**Review by Jacquesattaque — APPROVED** [review]

**Comment by Maxi-TD** [comment]
waiting for your approval

**Comment by Jacquesattaque** [comment]
@Maxi-TD I approved this yesterday

**Comment by Maxi-TD** [comment]
Thaks @Jacquesattaque! now I just have to wait? 
When will the logo be available on Shopify?

**Comment by Jacquesattaque** [comment]
Yes, we'll need to do a release for the icon to be available. We do these monthly, should be the first week of June.

**Comment by Maxi-TD** [comment]
Great! Thank you again!!

**Pull request merged**
