### PR TITLE
add alma icon

### PR DESCRIPTION
**Pull request by jsbalma**
Hello,
Our Alma apps are already validate by Shopify so we want to add our icon now.

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

Thanks

Resolves https://github.com/activemerchant/payment_icons/issues/621

### CODE REVIEW

**Comment by jsbalma** [comment]
Hello, could you merge it ?

**Comment by larouxn** [comment]
👋 Looks like the icon needs to be adjusted. There are some some [test failures](https://github.com/activemerchant/payment_icons/runs/6666103211?check_suite_focus=true).

Maybe we can rebuild it based on the [template](https://github.com/activemerchant/payment_icons/blob/3b558b771e1e096b8c4c23f0fef13f195563a19d/CONTRIBUTING.md#template).

**Comment by larouxn** [comment]
> Hello @larouxn, can you launch the workflow ? Thanks

Hey, sorry for the delay. Just ran the workflow again. The CI failure is `title` based.

```ruby
{:message=>"The 'alma' SVG file does not have the appropriate <title> value"}.
Expected: "Alma"
  Actual: "alma"
```

**Comment by jsbalma** [comment]
Hello @larouxn, I have updated the title. Can you update it ?

**Comment by larouxn** [comment]
👋 Hey @jsbalma, thanks for fixing the title. I see now the icons lacks a background/is transparent. Can we add one? Perhaps we can follow this [template](https://github.com/activemerchant/payment_icons/blob/17bc4291a913d3bc178b78c25bbafff0b8733401/CONTRIBUTING.md#template).
image

**Comment by jsbalma** [comment]
Ok I can add a white background

**Comment by rahilvirani** [comment]
We are in the midst of creating a better review and predictable release process for this repository moving forward. In order to facilitate this, we are requesting you to re-create your pull request using the new pull request template so that we are more informed of the nature of the change. We are sorry for the inconvenience.

**Pull request closed without merging**
