### PR TITLE
add Alma icon

### PR DESCRIPTION
**Pull request by webaaz**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: n/a

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon with the black background

image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<style> body { background: black; } </style>
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-alma" fill="none" xmlns="http://www.w3.org/2000/svg"><title id="pi-alma">Alma</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M34.0877 9.27963V10.3292C33.5231 9.56599 32.7034 9.08914 31.7301 9.08914C29.852 9.08914 28.3968 10.8596 28.3968 13.0446C28.3968 15.2296 29.852 17 31.7301 17C32.7719 17 33.6377 16.4547 34.2034 15.5956V16.8108H36V9.27963H34.0877ZM32.1966 15.1138C31.1525 15.1138 30.3068 14.1875 30.3068 13.0446C30.3068 11.9016 31.1525 10.9753 32.1966 10.9753C33.2408 10.9753 34.0865 11.9016 34.0865 13.0446C34.0865 14.1875 33.2408 15.1138 32.1966 15.1138ZM12.0648 7.18924H13.9759V16.8095H12.0648V7.18924ZM16.174 12.5416C16.174 10.4711 17.38 9.09039 19.0502 9.09039C20.0873 9.09039 20.907 9.57595 21.4007 10.4039C21.8956 9.57595 22.7142 9.09039 23.7513 9.09039C25.4214 9.09039 26.6274 10.4711 26.6274 12.5416V16.8108H24.7163V12.3237C24.7163 11.5157 24.2084 10.989 23.5363 10.989C22.8642 10.989 22.3563 11.5169 22.3563 12.3237V16.8108H20.4452V12.3237C20.4452 11.5157 19.9373 10.989 19.2652 10.989C18.5931 10.989 18.0852 11.5169 18.0852 12.3237V16.8108H16.174V12.5416ZM8.60393 9.35807C8.15154 7.57146 7.19479 7 6.28411 7C5.37342 7 4.41668 7.57146 3.96429 9.35807L2 16.812H3.93594C4.25131 15.567 5.22341 14.8735 6.28411 14.8735C7.3448 14.8735 8.3169 15.5682 8.63227 16.812H10.5694L8.60393 9.35807ZM6.28411 13.1367C5.66754 13.1367 5.10884 13.3832 4.69661 13.7829L5.80691 9.44522C5.91322 9.03063 6.07031 8.89866 6.28529 8.89866C6.50026 8.89866 6.65736 9.03063 6.76366 9.44522L7.87278 13.7829C7.46055 13.3832 6.90068 13.1367 6.28411 13.1367Z" fill="#FA5022"/></svg>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

As soon as possible, our payment extension is already used.

### CODE REVIEW

**Comment by webaaz** [comment]
Change logo (rebranding)
image

**Comment by webaaz** [comment]
@methodmissing @joshnuss @NicholasAnthony @ssoper What's the timing to merge PRs? We need our new logo as soon as possible to finalize our rebranding. Thanks

**Review by Benjamin-Freoua-Alma — APPROVED** [review]

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @lunataoo, @rahilvirani 
We created a new PR about the add a new logo.
Do you know if all is good ? You know how long we need to approved this PR.
Thanks in advance

**Comment by webaaz** [comment]
The icon with the visa 
image

**Review by Jacquesattaque — APPROVED** [review]

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @Jacquesattaque 
Thanks for the approbation.
Can you merge the PR also ?
Thanks in advance.

**Comment by Jacquesattaque** [comment]
Yup, we will. There's a queue of these we'll try to merge before the end of next week.

**Comment by webaaz** [comment]
@Jacquesattaque Can you merge it before Wednesday? Our next feature will be deployed and need this logo. Thanks

**Comment by webaaz** [comment]
I don't know the whole process. I just need my logo in my third party payment app revision

**Comment by Jacquesattaque** [comment]
Yup we're hoping to push this out tomorrow!

**Comment by webaaz** [comment]
@Jacquesattaque What's the deployment plan now? When the icon will be available for apps?

**Comment by Jacquesattaque** [comment]
@webaaz The icons were merged and deployed; repos will be updated next week.

**Pull request merged**
