### PR TITLE
Fix Thai payment icons

### PR DESCRIPTION
**Pull request by larouxn**
Seems the icons added in https://github.com/activemerchant/payment_icons/pull/393 used `href` instead of `xlink:href` which which technically works isn't to the spec. This PR replaces `href` with `xlink:href` and adds the required `xlink` definition. This approach is based on the standard set by preexisting base64 PNG icons such as [affinbank.svg](https://github.com/activemerchant/payment_icons/blob/3261572b037f8e6cd1c69367c9978046c7354fe5/app/assets/images/payment_icons/affinbank.svg).

Additionally, two of the icons (`cimbthai` and `dokuwallet`) are base64 JPEG instead of base64 PNG. These two icons need to be fixed or removed entirely. This PR currently removes said icons.
Screen Shot 2021-01-26 at 16 37 53

Resolves https://github.com/activemerchant/payment_icons/issues/396

### CODE REVIEW

**Comment by tauthomas01** [comment]
cc. @jawad-eGHL some of your icons were causing the build to fail, as a result, 2 of them have to be removed.

**Review by tauthomas01 — APPROVED** [review]
Looks good. Will wait for further updates from @jawad-eGHL if there are updates from the 2 icons.

**Comment by larouxn** [comment]
> cc. @jawad-eGHL some of your icons were causing the build to fail, as a result, 2 of them have to be removed.

Regarding this, can you supply us with either SVG or base64 PNG versions of the `cimbthai` and `dokuwallet` icons? If we have those we won't need to remove them with this PR. :)

**Comment by jawad-eGHL** [comment]
> > cc. @jawad-eGHL some of your icons were causing the build to fail, as a result, 2 of them have to be removed.
> 
> Regarding this, can you supply us with either SVG or base64 PNG versions of the `cimbthai` and `dokuwallet` icons? If we have those we won't need to remove them with this PR. :)

Hi @larouxn, do you need `cimbthai` and `dokuwallet` icons to be fixed only? I will have to check with designer to make it base64 PNG.

**Comment by larouxn** [comment]
> Hi @larouxn, do you need `cimbthai` and `dokuwallet` icons to be fixed only? I will have to check with designer to make it base64 PNG.

Hey @jawad-eGHL, yes, just `cimbthai` and `dokuwallet` (https://github.com/activemerchant/payment_icons/pull/397/commits/9cdf00b544c7585c4b0a0495fecfd9965203b66c). All others were properly encoded, just needed a little markup fix. (https://github.com/activemerchant/payment_icons/pull/397/commits/d7954c0187415163e692902b8f3bef2280e3b470)

**Comment by larouxn** [comment]
I'm going to go forward and merge this now so we can re-enable CI on fork based PRs via https://github.com/activemerchant/payment_icons/pull/400. We can re-add the `cimbthai` and `dokuwallet` in a follow-up before we cut a new release of this gem.

**Pull request merged**
