### PR TITLE
Add Cashalo Icon

### PR DESCRIPTION
**Pull request by candrasaputra**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by candrasaputra** [comment]
Hi, @larouxn Please help me review soon. Thanks

**Comment by candrasaputra** [comment]
Hi @larouxn , question, how to get approved from Shopify partners team?
My company is one of Shopify partner.
Should i ask Shopify partner to take a look on this PR?

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-01 at 13 58 53

**Review by larouxn — CHANGES_REQUESTED** [review]
Update, just realized this is an embedded PNG SVG (`data:image/png;base64`). Do we have a native SVG version? These kind of fake SVGs increase the library size a lot.

**Comment by candrasaputra** [comment]
@larouxn sorry we don't have native version.

**Comment by larouxn** [comment]
Hmm, not sure we can accept this icon. It's +14x bigger than a native SVG.
Screen Shot 2022-06-01 at 14 04 15
Screen Shot 2022-06-01 at 14 04 33

**Pull request closed without merging**
