### PR TITLE
Add Walley icon

### PR DESCRIPTION
**Pull request by loueranta-paytrail**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

Collector payment method was rebranded last fall: see [the press release](https://www-collector-fi.translate.goog/walley/?_x_tr_sl=fi&_x_tr_tl=en&_x_tr_hl=fi&_x_tr_pto=wapp) translated from Finnish.

Walley logo was sourced from [here](https://dev.walleypay.com/docs/wallify/logos/).

I'm not sure what is the correct procedure on renaming a payment service, but this PR will __replace__ Collector with Walley. If we should keep both in order to not brake anything, please edit it accordingly.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hey @loueranta-paytrail, we should probably keep the old icon as well just in case people are still using it.

Please feel free to clean up this PR to just add the new Walley icon.

**Comment by loueranta-paytrail** [comment]
@larouxn Now Collector is back and Walley is added as a new icon 👍

**Review by larouxn — APPROVED** [review]
LGTM 🎩 
Screen Shot 2022-02-01 at 20 16 30

**Review by larouxn — APPROVED** [review]
LGTM 🎩 
Screen Shot 2022-02-01 at 20 16 30

Note, I fixed a merge conflict that dropped the extra line at the end of `db/payment_icons.yml`. Feel free to drop that change if you like. 🙇‍♂️

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 @loueranta-paytrail, thanks for the contribution! Quick heads up that the icon likely won't be live for a few weeks at least since we'll be batching it with some other icons and doing the rollout after that.

**Comment by loueranta-paytrail** [comment]
@larouxn Thanks for letting me know! 

I do hope some of the other missing Finland-specific payment method icons (that I recently submitted) will find their way on to that release as well 😉

**Comment by larouxn** [comment]
👋 Hello hello, your icon(s) should be live everywhere now. Please let us know if otherwise. 🙇‍♂️

**Pull request merged**
