### PR TITLE
Added Yape icons

### PR DESCRIPTION
**Pull request by jorge-palacios-tw**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.

Link to the brand guidelines: https://www.yape.com.pe/

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon with the black background
Screen Shot 2022-10-14 at 10 31 30

Screen Shot 2022-10-14 at 10 32 07

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

**As soon as possible. We will be releasing the service by October 20th 2022.**

### CODE REVIEW

**Comment by jorge-palacios-tw** [comment]
Hello, and good day @larouxn, @rahilvirani, @tauthomas01.

Please help review the new icons for Yape. Please let me know if you have any questions or comments. Thanks in advance.

**Comment by Jacquesattaque** [comment]
These icons do not meet our guidelines. Please submit a single icon, preferably on a white background, with the appropriate rounded corners and black border. File names can only contain alphabetic characters.

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
These icons do not meet our guidelines. Please submit a single icon, preferably on a white background, with the appropriate rounded corners and black border. File names can only contain alphabetic characters.

**Comment by Jacquesattaque** [comment]
@jorge-palacios-tw Please let us know if you still require this icon. If we haven't heard back by the end of next week we'll close this issue.

**Pull request closed without merging**
