### PR TITLE
Add TreviPay icon to Shopify

### PR DESCRIPTION
**Pull request by juanda8518**
## Why are you adding this icons?
I'm adding/updating this icon(s) because our team at Trevipay is creating a payment app for Shopify which requires the icon.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

As soon as possible. We will be releasing the service in January 2023.

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
@juanda8518 Thanks for your submission. So far this looks good, but I'd recommend removing the ™ from the vector image. It's so small that it just looks like an odd dot in the icon at 100%.

**Comment by juanda8518** [comment]
@Jacquesattaque thanks for your comments. We agree having the TM mark at that size looks a bit odd, hence we removed it. Can you please review it again?

image

**Comment by Jacquesattaque** [comment]
Icon looks great, but some checks are failing. Have a look and resubmit for a review when they're clear.

**Comment by juanda8518** [comment]
@Jacquesattaque thanks. When removing the TM mark we didn't include the required tags (title, ids, etc..). Those were added in the last commit so it should be good now. Can you please run the workflow?

image

**Review by Jacquesattaque — APPROVED** [review]

**Comment by juanda8518** [comment]
@Jacquesattaque do you have an approx timeframe for when this PR will be merged?

**Comment by Jacquesattaque** [comment]
@juanda8518 We try to do a release every two weeks. We're a little delayed coming out of the holidays. Hoping we can get it done before the end of the month.

**Comment by juanda8518** [comment]
> @juanda8518 We try to do a release every two weeks. We're a little delayed coming out of the holidays. Hoping we can get it done before the end of the month.

@Jacquesattaque hope you are well. can you please confirm when the next release is scheduled? We will submit the app in the next few days and would like to include the icon as part of it.

**Pull request merged**
