### PR TITLE
feat(icons): Add logo for Escrow.com Payments

### PR DESCRIPTION
**Pull request by AdiRishi**
## Why are you adding this icons?
Escrow.com is preparing it's payments app integration with Shopify. As part of this work Escrow needs it's own branding available at checkout to provide a better experience.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.

Link to the brand guidelines: _Not available_

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon along side the example Visa icon
Screenshot 2024-04-04 at 3 30 38 pm

### CODE REVIEW

**Comment by hellicarusprime** [comment]
Hi @AdiRishi, could you please update the name to follow our [contributing guidelines on naming](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#name)?

**Comment by AdiRishi** [comment]
> Hi @AdiRishi, could you please update the name to follow our [contributing guidelines on naming](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#name)?

@hellicarusprime my apologies, I missed that requirement. Updated now 👍

**Comment by hellicarusprime** [comment]
> > Hi @AdiRishi, could you please update the name to follow our [contributing guidelines on naming](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#name)?
> 
> @hellicarusprime my apologies, I missed that requirement. Updated now 👍

No worries, we used to allow it.

**Comment by hellicarusprime** [comment]
One other small thing is that the border should be applied to the outside rather than the center.

You currently have a 37 x 23 px rectangle with the border applied to the center, but we'd prefer if the rectangle was 36 x 22 px with the border applied to the outside. I hope that makes sense.

**Comment by Jeremyhzk** [comment]
Escrow com icon

Hi @hellicarusprime , I'm Jeremy, Designer at Escrow. I made the rectangle 36 x 22 with the border on the outside. And also used the optimization tool. However, because the border is applid on the outside, the overal svg size becomes 38 x 24, please let me know if this is what you prefer.

**Review by Lovedanihonjin — CHANGES_REQUESTED** [review]
This looks great! Would you mind expanding/outlining the stroke of the SVG image?

**Comment by Jeremyhzk** [comment]
Hi @Lovedanihonjin Im not sure what you mean by expanding/outlining the stroke, did you mean making the outline thicker? or were you refering to the the shield logo of Escrow? 
Escrow com

**Comment by Lovedanihonjin** [comment]
> Hi @Lovedanihonjin Im not sure what you mean by expanding/outlining the stroke, did you mean making the outline thicker? or were you refering to the the shield logo of Escrow? Escrow com

Here is an example of outlining your stroke. You just need to make your stroke a flat vector.

**Comment by Jeremyhzk** [comment]
@Lovedanihonjin the screenshot you attatched doesn't work but I think I get what you mean, made the outline a vector too and flatten them, and put it through the optimization tool. I uploaded both optimized and non optimized version. Let me know if this work

Escrow logo optimized

Escrow logo

**Review by Lovedanihonjin — APPROVED** [review]
Looks good. Approved.

**Comment by adeniyiao** [comment]
Hi @Jeremyhzk , could you please rebase your branch against activemerchant:master to address the conflict. Thanks

**Comment by AdiRishi** [comment]
I've rebased the branch, used the updated optimized icon @Jeremyhzk provided, and added in the necessary additions like viewbox, id and title as per the contributing guidelines.

**Pull request merged**
