### PR TITLE
Add PayTo icon

### PR DESCRIPTION
**Pull request by luyx2412**
- PayTo icon

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by luyx2412** [comment]
Hi, @tauthomas01 Please check it soon. Thanks

**Review by tauthomas01 — APPROVED** [review]

**Comment by luyx2412** [comment]
Hi, @larouxn Please help me review soon. Thanks

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-05-18 at 14 41 25

**Comment by larouxn** [comment]
👋 Hello, your icon(s) have been released in the latest version of this library. The rollout process will begin within a few days. We wanted to have it/them live this week but looking more likely to be live early to mid next week. Will report back here when live. Thank you for your patience. 🙇‍♂️

**Comment by luyx2412** [comment]
Thanks for your information. Great to hear it.

**Comment by larouxn** [comment]
👋 Hello, actually your icon(s) should be live everywhere now. 🚀

**Pull request merged**
