### PR TITLE
Update mobilepay.svg

### PR DESCRIPTION
**Pull request by mniss**
[X] If this pull request is not adding new icons, you can remove this checklist.
Not adding a new icon. Just updating existing old icon.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hey @mniss, can we add the spacing/border around the new image according to [these guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance)? There's an example at the bottom of that page with the border markup we might be able to use. Though the icon will likely need to be shrunk a bit to fit.

**Comment by mniss** [comment]
Hi larouxn, I'll check with our design team today and get back to you...

**Comment by mniss** [comment]
@larouxn, I added a border to the icon as you requested.
One note: Your guideline states "0.07% opacity" for the border. I guess it should say "7%" or a "value of 0.07" :)

**Review by larouxn — APPROVED** [review]
LGTM 🙌 
Screen Shot 2021-03-26 at 16 24 35

**Comment by larouxn** [comment]
👋 @mniss, thanks for the heads up. Will be improving the contribution guide soon.
https://github.com/activemerchant/payment_icons/pull/426

**Comment by tauthomas01** [comment]
Looks good 👍 
One small comment: can we put the svg code everything in 1 line like the previous icon?

**Comment by mniss** [comment]
> One small comment: can we put the svg code everything in 1 line like the previous icon?

Yes. Please feel free to do so.

**Pull request merged**
