### PR TITLE
Add Catch payment icon

### PR DESCRIPTION
**Pull request by LevKanter**
## Why are you adding this icons?
I'm adding this icon for use in a Shopify payments app for the service [Catch](https://www.getcatch.com/).

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify?
Catch is a Shopify partner and we have been approved to develop a payments app. This app is currently in late stages of development.

What's the expected date of this change to deploy on Shopify?
As soon as possible 🙏

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Please use our provided template — the border you have here is layered on top of a white layer, resulting in a different final hex value for the border than our other icons. In addition, increase the amount of white space you have to the left and right of the logo. It feels pretty tight right now.

**Comment by LevKanter** [comment]
> Please use our provided template — the border you have here is layered on top of a white layer, resulting in a different final hex value for the border than our other icons. In addition, increase the amount of white space you have to the left and right of the logo. It feels pretty tight right now.

Sorry about that. Pushed revisions in https://github.com/activemerchant/payment_icons/pull/791/commits/1f140fe9b8d86820d8818876c5913aa3fc82be67

**Review by Jacquesattaque — APPROVED** [review]

**Comment by Jacquesattaque** [comment]
@LevKanter It turns out the label Catch can't be used as it's a reserved word in Javascript and it's causing some issues. May we rename to catchpayments or something like that?

**Comment by LevKanter** [comment]
> @LevKanter It turns out the label Catch can't be used as it's a reserved word in Javascript and it's causing some issues. May we rename to catchpayments or something like that?

@Jacquesattaque oh sorry about that. Will submit a fix shortly. Just to clarify, is it the `label` "Catch" in `db/payment_icons.yml` that's causing the problem (not technically a reserved word in js) or the `name` "catch" (is a reserved word), or are both problematic? If it's the `name` specifically, would it be ok to change the `name` to "catchpayments" (and update the attributes in the svg itself accordingly) but keep the `label` as is?

**Comment by Jacquesattaque** [comment]
@LevKanter It's both actually since they have to match. I think we can do the fix on our end for you if you're OK using catchpayments for both.

**Comment by LevKanter** [comment]
@Jacquesattaque ok, thank you. If it's "catchpayments" for the name, and "Catch Payments" for the label, that's fine.

For what it's worth, it looks like their are currently various examples in `db/payment_icons.yml` where the name and labels don't match (e.g. "laybuy" and "Lay-Buy Powered By PayPal" or "seveneleven" and "7-Eleven")...not sure if I'm misunderstanding something.

My one concern here is that the actual `<title>` tag in the svg markup itself remains "Catch" (ideally), since that will manifest as a user-facing tooltip/manifest to screen readers, and our preference would be for end users to still see just "Catch".

**Comment by Jacquesattaque** [comment]
@LevKanter  Yeah hoping we can keep these changes to just the YML file and SVG name and find a way to display Catch to merchants and buyers. Let me sync up with the team and I'll get back to you. You're right about the label and name not needing to match as well — I think it might be the title, but I'll confirm.

**Comment by Jacquesattaque** [comment]
@LevKanter It's the name and icon, not the label. So it will display as catchpayments for the name and Catch as the label.

**Comment by LevKanter** [comment]
@Jacquesattaque ok sounds good. Thank you.

**Pull request merged**
