### PR TITLE
Add a `viewBox` attribute to all icons:

### PR DESCRIPTION
**Pull request by Edouard-chin**
- The viewBox is set to `0 0 38 24`, without this the icon doesn't render properly if inlined

@AnthonyClark

### CODE REVIEW

**Comment by AnthonyClark** [comment]
They don't render correctly if the container has height and width specified?

**Comment by Edouard-chin** [comment]
>  They don't render correctly if the container has height and width specified?

Yep that's correct, if they are displayed inline, they won't render correctly. The AMEX one for example would not fit into the viewbox and the icon would be stripped

**Comment by AnthonyClark** [comment]
Can you add this into the PR template and contribution guidelines for future icons to adhere to?

**Comment by Edouard-chin** [comment]
done

**Pull request merged**
