### PR TITLE
add qasitli

### PR DESCRIPTION
**Pull request by ahmada3mar**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" role="img" aria-labelledby="pi-qasitli" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 38 24" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" style="background-color:#fff"><title id="pi-qasitli">Qasitli</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><g transform="matrix(.01613 0 0 .01531 .425 3.922)"><ellipse rx="484.485" ry="474.524" transform="matrix(.99252 0 0 1.0105 585.107 527.5)" fill="#e3302d"/><ellipse rx="314.236" ry="313.33" transform="matrix(1.01153 0 0 1.03035 590.54 527.5)" fill="#fff"/><ellipse rx="271.674" ry="266.24" transform="matrix(.8628 0 0 .87953 589.937 527.5)" fill="#e3302d"/><rect width="329.329" height="322.984" rx="0" ry="0" transform="translate(598.525 527.5)" fill="#e3302d"/><ellipse rx="41.772" ry="41.166" transform="matrix(1.10283 0 0 1.11311 855.345 615.36)" fill="#fff"/><ellipse rx="41.772" ry="41.166" transform="matrix(1.10283 0 0 1.11311 679.507 791.184)" fill="#fff"/><path d="M675.395 559.152l-56.733 56.207 232.482 235.474 61.05-59.65-236.8-232.031z" fill="#fff"/><ellipse rx="46.162" ry="43.364" transform="matrix(1.01344 0 0 1.06566 1690.865 506.282)" fill="#e3302d"/><ellipse rx="46.162" ry="43.364" transform="matrix(1.01344 0 0 1.0729 2151.534 512.626)" fill="#e3302d"/><path d="M1319.36 791.184v45.822h34.18V587.743h-27.186l-2.369 45.945-79.424-45.945q-67.22-16.992-126.003 50.129s-47.42 105.263 28.224 173.148c0 0 25.214 21.91 86.31 25.986 0 0 52.088-8.441 86.268-45.822z" fill="#8b8e8e"/><ellipse rx="85.826" ry="91.645" transform="matrix(1.09321 0 0 1.03997 1229.456 710.667)" fill="#fff"/><path d="M1591.6 633.688q-51.295-26.768-94.528-18.329s-35.906.403-44.699 37.018c0 0-7.327 26.403 28.578 31.509 0 0 118.709 25.647 109.916 33.707.732 0 16.853 10.992 22.715 36.639 0 0 5.862 40.188-35.173 68.147 0 0-48.362 24.55-115.777 6.595 0 0-46.897-14.49-49.828-23l14.655-26.095q25.647 21.05 69.613 26.096s48.363 3.841 76.208-14.791c0 0 16.854-24.65 0-45.823 0 0-12.457-12.048-83.536-23.371 0 0-85-13.772-68.147-74.01 0 0-2.931-34.44 41.035-52.759 0 0 24.181-14.308 76.208-10.893 0 0 45.432 8.34 67.415 19.686l-14.656 29.674z" fill="#8b8e8e"/><rect width="37.961" height="247.679" rx="0" ry="0" transform="translate(1675.216 589.327)" fill="#8b8e8e"/><rect width="37.961" height="247.679" rx="0" ry="0" transform="translate(2128.156 589.327)" fill="#8b8e8e"/><path d="M1985.804 486.66v288.157q5.176 59.816 77.647 59.816s25.882.936 31.058-5.659l-.862-23q-20.706 6.139-46.589 0s-33.647-8.177-27.607-51.742V486.66h-33.647zM1797.276 527.5v259.16q5.176 53.797 77.647 53.797s25.882.843 31.058-5.089l-.862-20.685q-20.706 5.52-46.588 0s-33.647-7.355-27.608-46.536V527.5h-33.647z" fill="#8b8e8e"/><rect width="72.763" height="30.707" rx="0" ry="0" transform="matrix(1 0 0 1.04764 1829.218 583.19)" fill="#8b8e8e"/></g></svg>


```
image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Comment by ahmada3mar** [comment]
Hello @Jacquesattaque, the fill removed.
Can you check again please ?

**Review by Jacquesattaque — APPROVED** [review]

**Comment by Jacquesattaque** [comment]
@ahmada3mar The icon looks good. Please clear the automated check failures.

**Comment by ahmada3mar** [comment]
@Jacquesattaque i could not clear the failure checks, any advice ?

**Comment by Jacquesattaque** [comment]
@adeniyiao May you have a look?

**Comment by ahmada3mar** [comment]
@Jacquesattaque  sorry, it's my bad. i had a misunderstanding.

 All checks have passed, can you check again please ?

**Comment by Jacquesattaque** [comment]
All looks good, thanks!

**Comment by ahmada3mar** [comment]
Hello @Jacquesattaque,

When will this PR merged ?

**Comment by Jacquesattaque** [comment]
@ahmada3mar We do a monthly release, typically on the first Wednesday of the month. Our next release is tentatively scheduled for Wednesday, November 1.

**Pull request merged**
