### PR TITLE
Add Satispay icon

### PR DESCRIPTION
**Pull request by stvnmsh**

### CODE REVIEW

**Comment by larouxn** [comment]
👋  Hey @stvnmsh, thanks for the contribution! Icon looks pretty good so far. I think we just need to remove the white fill background, which can be seen here.
Screen Shot 2021-04-16 at 12 18 05

I think the following might work. I removed the `<path fill="#fff" d="M0 0h38v24H0z"/>`.
```SVG
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-satispay"><title id="pi-satispay">Satispay</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M35 0H3a2.946 2.946 0 00-3 3v18a3.009 3.009 0 003 3h32a2.946 2.946 0 003-3V3a3.009 3.009 0 00-3-3z" fill="#f94c43"/><path d="M23.774 4.226a.129.129 0 00.028-.144A.127.127 0 0023.68 4h-3.474l1.9 1.9zM18.42 14.431l-2.426-2.426 2.426-2.426-2.522-2.523-4.856 4.855a.132.132 0 000 .188l4.856 4.854zm3.683 3.681L20.219 20h3.456a.133.133 0 00.093-.227z" fill="#fff"/><path d="M19.087 4.039a.135.135 0 00-.09-.038h-4.676a.127.127 0 00-.122.082.129.129 0 00.028.144l7.78 7.78-7.773 7.767a.133.133 0 00.093.227h4.672a.141.141 0 00.1-.038l7.864-7.864a.135.135 0 000-.188z" fill="#fff"/></svg>
```
Screen Shot 2021-04-16 at 12 28 53

**Comment by stvnmsh** [comment]
👋🏼 Hi @larouxn, I've removed the white fill background as suggested

**Review by tauthomas01 — APPROVED** [review]
Looks good.

**Review by larouxn — APPROVED** [review]
Thanks for fixing up the icon!

**Pull request merged**
