### PR TITLE
#473

### PR DESCRIPTION
**Pull request by smart--petea**
## Why are you adding this icons?
We're creating a payment app at billink.nl. We need our application be eligible through payment methods at install time

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: [one](https://developers.billink.nl/branding) [two](https://developers.billink.nl/branding-en)

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<style> body { background: black; } </style>
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-billink_method"><title id="pi-billink_method">Billink</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#F28D20" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M5.973 9.172c-.915 0-1.755.345-2.393.9.158-.375.458-.682.833-.847v-.338c0-.735-.6-1.335-1.335-1.335-.053 0-.105 0-.158.008v-.007h-.585v5.242c0 2.01 1.628 3.63 3.63 3.63 2.01 0 3.63-1.628 3.63-3.63a3.62 3.62 0 0 0-3.622-3.623zm4.725 1.403h1.68v5.865h-1.68zm1.642-2.573a1.313 1.313 0 0 0-.36-.24 1.076 1.076 0 0 0-.435-.09c-.157 0-.3.03-.435.09s-.255.143-.352.24c-.098.098-.18.218-.24.353a1.05 1.05 0 0 0-.09.435c0 .158.03.3.09.435s.135.255.24.353c.097.097.217.18.352.24.135.06.285.09.435.09a1.164 1.164 0 0 0 .795-.33 1.05 1.05 0 0 0 .24-.353 1.102 1.102 0 0 0-.24-1.223zm1.313-.037h1.68v8.475h-1.68zm2.955 0h1.68v8.475h-1.68zm4.597.037a1.313 1.313 0 0 0-.36-.24 1.076 1.076 0 0 0-.435-.09c-.157 0-.3.03-.435.09s-.255.143-.352.24c-.098.098-.18.218-.24.353a1.05 1.05 0 0 0-.09.435c0 .158.03.3.09.435s.135.255.24.353c.097.097.217.18.352.24.135.06.285.09.435.09a1.164 1.164 0 0 0 .795-.33 1.05 1.05 0 0 0 .24-.353 1.102 1.102 0 0 0-.24-1.223zm-1.642 2.573h1.68v5.865h-1.68zm7.957.045a2.835 2.835 0 0 0-.93-.63 2.885 2.885 0 0 0-2.197-.03 3.105 3.105 0 0 0-.915.562l-.548-.637h-.405v6.555h1.673v-3.743c0-.172.03-.33.097-.487.068-.15.158-.285.27-.398a1.277 1.277 0 0 1 .9-.367c.173 0 .33.03.48.097.15.068.285.158.398.27.112.113.202.248.27.398.067.15.097.315.097.487v3.743h1.673v-3.743c0-.405-.075-.787-.233-1.14a2.905 2.905 0 0 0-.63-.937zm8.145-.72h-1.927l-2.49 3.158V7.965h-1.68v8.475h1.68v-.84l1.162-1.537 1.328 2.377h1.927l-2.175-3.81 2.175-2.73" fill="#FFF"/><path d="M7.923 12.803v-.015h-3.9v.014a1.95 1.95 0 0 0 3.9 0z" fill="#F28D20"/></svg>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name). I'm Petru Badarau, employeed at billink.nl.

What's the expected date of this change to deploy on Shopify? It should be already deployed.

### CODE REVIEW

**Review by rahilvirani — CHANGES_REQUESTED** [review]
@smart--petea There is an [existing](https://github.com/activemerchant/payment_icons/blob/3780f08005eb8f5a669f0fae6d3925048716a955/db/payment_icons.yml#L870) Billink icon. Do you mind updating the existing as compared to creating a new one?

**Comment by smart--petea** [comment]
Hi @rahilvirani . We need a new icon for our own use.

**Comment by rahilvirani** [comment]
@smart--petea I'm good with creating the new icon since the [existing one](https://github.com/activemerchant/payment_icons/pull/347) is use for added for pay.nl. I will create an issue internally to rename the label of the exiting icon so that it can be distinguished properly.

The tests are failing, once you have fixed the test. I will review the PR and merge it

**Review by smart--petea — COMMENTED** [review]
added viewBox attribute

**Review by rahilvirani — APPROVED** [review]
image

looks good!

**Comment by smart--petea** [comment]
Hi @rahilvirani . When master branch is expected to be released?

**Comment by Jacquesattaque** [comment]
Should be available before the end of next week.

**Pull request merged**
