### PR TITLE
added apple pay icon

### PR DESCRIPTION
**Pull request by amir-s**
** Checklist **
- [x] All icons include ~~`width="28" height="24"`~~  `width="38" height="24"` in their attributes
- [x] All icons have solid white backgrounds
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I am confident that all icons are clear and easy to read/understand

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by vernalkick** [comment]
@jiangster the border-radius doesn't match the other icons:


It looks like it's 2.5 right now, but it should be 3. 😉 

@amir-s once you have the final icon, run it through `svgo` to optimize it and reduce its file size 😃

**Comment by amir-s** [comment]
Thanks @vernalkick @jiangster .

Done.

**Comment by vernalkick** [comment]
Didn't 🎩 but LGTM!

**Comment by bdewater** [comment]
LGTM too!

**Pull request merged**
