### PR TITLE
Add ask svg

### PR DESCRIPTION
**Pull request by o-vartan**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by o-vartan** [comment]
@tauthomas01 tell me why the pull request failed?

**Comment by PolinaSalimyanova** [comment]
@tauthomas01 @larouxn 
Could you provide more details for the reason to decline our pool request?
We meet all the check list, but still can't pass review

**Comment by tauthomas01** [comment]
Hi,

The errors said:

- The 'ask' SVG file should have a 'viewBox' attribute on the root <svg> tag
- The 'ask' SVG file should have a single <title> tag"

All the instructions are available in the [contribution guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md)

**Comment by larouxn** [comment]
Seems the added title should be `ASK`, not `Ask`. ([CI](https://travis-ci.org/github/activemerchant/payment_icons/jobs/738144145))

**Comment by larouxn** [comment]
Apparently there are a few more issues. They can be seen by clicking here.
Screen Shot 2020-10-23 at 18 04 39
Screen Shot 2020-10-23 at 18 04 48
Screen Shot 2020-10-23 at 18 04 59

**Review by tauthomas01 — APPROVED** [review]
Looks good. I'll let @larouxn review as well.

**Review by larouxn — APPROVED** [review]
Thanks for fixing it up. LGTM 👍 
Screen Shot 2020-10-24 at 09 52 48

**Pull request merged**
