### PR TITLE
Add Solana Pay

### PR DESCRIPTION
**Pull request by rramsden**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

Here is the branding guidelines for Solana Pay
https://solanapay.com/branding

### CODE REVIEW

**Review by larouxn — CHANGES_REQUESTED** [review]
It looks like the icon is lacking the 0.7 opacity border. Should be visible in the red screenshot below. Perhaps we can try rebuilding the icon with the [template](https://github.com/activemerchant/payment_icons/blob/b2ebb1241bc8bb7da0d2a196c7576696d7a0bfe4/CONTRIBUTING.md#template).
Screenshot 2022-04-21 195308
Screenshot 2022-04-21 195329
Screenshot 2022-04-21 195344

**Comment by rramsden** [comment]
Thanks for the review @larouxn 🙏 

Uploaded a new version using the white version which I think looks a lot better with the transparent border. Could you take a second look?

image

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screenshot 2022-04-24 162228

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Hello, your icon(s) should be available everyone now. Please let us know if otherwise.

**Pull request merged**
