### PR TITLE
Tpay and Pekao logos

### PR DESCRIPTION
**Pull request by kwojc**
## Why are you adding this icons?
We're adding this icon(s) because we just released our Tpay  (https://apps.shopify.com/tpay?locale=pl) payment app on Shopify App Store <3 

Pekao logo is attached because they are co-owner of Tpay, and its Installments are also available in our payment gateway.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

image

**If the icons are intended for use by Shopify, please provide the following info:**
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
_Bryan | Shopify Partner Specialist_

What's the expected date of this change to deploy on Shopify?
_Our payment app is live, so the earliest opportunity available would be great._

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
The Tpay icon looks good. The Raty Pekao icon could be reduced in file size by simplifying the paths in the text. It looks like these were perhaps traced. Could you take a look and see if you can reduce the file size here by simplifying the icon?

**Comment by kwojc** [comment]
> The Tpay icon looks good. The Raty Pekao icon could be reduced in file size by simplifying the paths in the text. It looks like these were perhaps traced. Could you take a look and see if you can reduce the file size here by simplifying the icon?

We modified Raty Pekao icon, because that red bar with "RATY" was unreadable in this size. Right now, logo is much simpler.

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Thanks for simplifying the icon. I think it could still be reduced in file size. Many of these points aren't necessary to draw the letters. You also have some failing checks to clear.

Screenshot 2023-10-10 at 8 54 07 AM

**Comment by kwojc** [comment]
> Thanks for simplifying the icon. I think it could still be reduced in file size. Many of these points aren't necessary to draw the letters. You also have some failing checks to clear.
> 
> Screenshot 2023-10-10 at 8 54 07 AM

Yea, missing viewbox.
"Bank Pekao" is registered trademark one of the biggest polish bank. We cannot modify logo, because it will slightly modify letters curves which is unacceptable by our partner. 
Here is logo history (unfortunatelly in polish, but you can translate it in google): https://www.pekao.com.pl/o-banku/historia-logo.html

**Comment by Jacquesattaque** [comment]
Got it, no problem on the logo then if it's what you received from the partner. Just clear the failing checks and I'll approve.

**Comment by kwojc** [comment]
> Got it, no problem on the logo then if it's what you received from the partner. Just clear the failing checks and I'll approve.

Previous test has a strange behaviour cuz there was a proper prefix in ID, in change I just fixed order of attributes (maybe ruby 3.1 has a problem with parsing xml?)

**Comment by kwojc** [comment]
@Jacquesattaque Could you accept a workflow?

**Comment by kwojc** [comment]
@Jacquesattaque fixed, pleace accept workflow.

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
