### PR TITLE
add Atone icon

### PR DESCRIPTION
**Pull request by uetoshi**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
🎩 Looks good to me 🎩 
Screen Shot 2022-01-28 at 09 20 57

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 @uetoshi, thanks for the contribution! Quick heads up that the icon likely won't be live for a few weeks at least since we'll be batching it with some other icons and doing the rollout after that.

**Comment by uetoshi** [comment]
@larouxn Thank you so much for your support. I wait for the rollout.

**Comment by larouxn** [comment]
👋 Hello hello, your icon(s) should be live everywhere now. Please let us know if otherwise. 🙇‍♂️

**Pull request merged**
