### PR TITLE
Add kakebaraidotcom icon 

### PR DESCRIPTION
**Pull request by trustring**
Add new record to db/payment_icons.yml

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the border is covering part of the icon. We need to fix this before merge.
Screen Shot 2022-06-01 at 13 54 31

Please refer to the [template](https://github.com/activemerchant/payment_icons/blob/3b558b771e1e096b8c4c23f0fef13f195563a19d/CONTRIBUTING.md#template).

**Comment by trustring** [comment]
@larouxn Thanks for your review. 
I have submitted new commit to fix the issue. 
Please review again.
Thank you!

**Review by larouxn — APPROVED** [review]
Looks good to me :tophat: 
image

**Comment by trustring** [comment]
@tauthomas01 Thanks for your review!
@larouxn It seems to have been passed all checked. Please merge this pull request when you have time. Thank you!

**Comment by larouxn** [comment]
👋 Hello, actually your icon(s) should be live everywhere now. 🚀

**Pull request merged**
