### PR TITLE
[Przelewy24] updated icon and naming fix

### PR DESCRIPTION
**Pull request by kfalkiewicz**
## Why are you adding this icon?
I'm updating this icon because the current version is not the correct Przelewy24 provider logo, but some kind of "creative work" that doesn't align with official provider branding. The name is also misspelled.

This fix is for the https://github.com/activemerchant/payment_icons/pull/836 with proper icon and setup clean up.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly, and they have provided the icons.
- [ ] I'm associated with the brand, and I've read all the brand icon’s guidelines.
- [X] I'm an individual, and I've read all the brand icon’s guidelines.

Link to the brand guidelines: https://www.przelewy24.pl/en/download?#materialy-graficzne

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team, it may not receive review nor merger.

## Attach a screenshot of the icon alongside the example Visa icon
Screenshot 2023-06-29 at 12 09 27

### CODE REVIEW

**Comment by kfalkiewicz** [comment]
@Jacquesattaque Hmm run once again SVG through SVGO. I hope it should be ok now.

**Comment by kfalkiewicz** [comment]
@Jacquesattaque Can you run pipeline once again? All the issues should be fixed (the ones visible in pipeline logs).

**Comment by kfalkiewicz** [comment]
Can anyone run pipeline for this PR? This is an only way to actually check if it is valid. I don't have permission to do this.

@Jacquesattaque @santoso87

**Review by Jacquesattaque — APPROVED** [review]

**Comment by kfalkiewicz** [comment]
Any plans for merging this?

**Comment by Jacquesattaque** [comment]
We do a monthly release so this will be released in the first week of August.

**Pull request merged**
