### PR TITLE
Modify Visa V Pay icon

### PR DESCRIPTION
**Pull request by tauthomas01**
This is a replacement of the Visa V Pay icon from https://github.com/activemerchant/payment_icons/pull/200 because the gem generates errors from this icon: https://github.com/activemerchant/payment_icons/issues/206

I asked my designer to rebuild the icon and made local testing to make sure the gem works.

cc. @Korri Can you validate this? I can't put you as a reviewer.

### CODE REVIEW

**Comment by Korri** [comment]
Thanks for the update!

Comparing the two it looks like the radius on the new one is slightly bigger.

I also find the "Pay" text a bit to small especially when displayed at a 100% zoom.

EDIT: Looking closer it looks like the radius is indeed a bit different, I had the same issue when designing it originally:
Screen Recording 2019-11-05 at 11 44 51

I ended up using the Shopify Pay icon as a base for this design (might be what created some issues).

**Comment by tauthomas01** [comment]
@Korri When I submitted my PR, I also noticed the borders were different. In fact, the original Visa V Pay border icon was not correct, as seen in this video : https://screenshot.click/05-50-j2i8b-zublk.mp4 (my mistake for not reviewing throughly)

I'll ask my designer if he could increased the icon's size.

**Comment by Korri** [comment]
> [...] (my mistake for not reviewing throughly)

You did, you actually asked me to change it to what it is now: https://github.com/activemerchant/payment_icons/pull/200#discussion_r329112444

You know better then me which one is the right one, but interac and Shopify Pay do not match:
Screen Recording 2019-11-05 at 15 25 47

**Comment by tauthomas01** [comment]
After comparing several icons to see the border radius, it looks like the borders of the Shopify Pay icon is incorrect. Thank you for finding this!

I created an [issue](https://github.com/activemerchant/payment_icons/issues/208) so that we don't forget.

**Comment by Guillaumegranger1** [comment]
Thanks for the feedback @Korri 
According to [our guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons), the border width must have a 2px radius (outside stroke). Which is the case here, but not on the Shopify Pay icon which border is a **center stroke**. I updated the Vpay icon to make its text bigger, without changing its radius. It will be uploaded shortly. I'll update the Shopify Pay icon accordingly to avoid the same issue to occure again. 
CC @tauthomas01

**Comment by tauthomas01** [comment]
Thank you @Korri for your feedback, this is looking better 👍 
I'll create a separate PR for the Shopify Pay icon.

**Pull request merged**
