### PR TITLE
Add Fairstone icon

### PR DESCRIPTION
**Pull request by Daniel-Nordby**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hey @Daniel-Nordby, the icons has some outstanding fixes that need to be done. ([CI logs](https://github.com/activemerchant/payment_icons/runs/6483577822?check_suite_focus=true))

For example the title value is a bit off.
```
Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:78]:
{:message=>"The 'fairstone_payments' SVG file does not have the appropriate <title> value"}.
Expected: "Fairstone Payments"
  Actual: "Fairstone"

rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:61
```

You can run these tests locally with `bundle exec rails test`.

**Comment by Daniel-Nordby** [comment]
> wave Hey @Daniel-Nordby, the icons has some outstanding fixes that need to be done. ([CI logs](https://github.com/activemerchant/payment_icons/runs/6483577822?check_suite_focus=true))
> 
> For example the title value is a bit off.
> 
> ```
> Failure:
> PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:78]:
> {:message=>"The 'fairstone_payments' SVG file does not have the appropriate <title> value"}.
> Expected: "Fairstone Payments"
>   Actual: "Fairstone"
> 
> rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:61
> ```
> 
> You can run these tests locally with `bundle exec rails test`.

Thanks @larouxn - I will give this a shot

**Comment by larouxn** [comment]
> I _was_ able to test and fix the SVG (and presumably any other issues) with just `rake` - will that have executed all the necessary tests?

`rake` should also work fine to run the tests, I think.

**Comment by Daniel-Nordby** [comment]
Thanks @larouxn - I think this is completed then...what are my next steps to have this merged in for use? :)

**Comment by Daniel-Nordby** [comment]
@larouxn sorry to pester - any update on next steps? Thanks!

**Review by larouxn — CHANGES_REQUESTED** [review]
We need to add a background (likely white) for this icon. Additionally the border and shape are incorrect.
Screen Shot 2022-06-01 at 13 48 09

Please refer to the [template](https://github.com/activemerchant/payment_icons/blob/3b558b771e1e096b8c4c23f0fef13f195563a19d/CONTRIBUTING.md#template).

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-23 at 18 28 24

**Review by tauthomas01 — APPROVED** [review]

**Comment by Daniel-Nordby** [comment]
@larouxn and @tauthomas01 thanks for the merge + support!

Any visibility on how long it takes for the icon to show up as an active option in the payment methods dropdown? Thanks!

**Comment by larouxn** [comment]
Hello @Daniel-Nordby, we will need to release a new version of this library and roll it out across all the different areas icons appear. Earliest I'm expecting this icon to be live is mid to late next week.

**Comment by Daniel-Nordby** [comment]
Makes plenty of sense - thanks for setting expectations and clarifying @larouxn!

**Comment by larouxn** [comment]
👋 Apologies, forgot to post here, the Fairstone Payments icons should be live everywhere as of last Friday. 🚀

**Comment by Daniel-Nordby** [comment]
Confirmed! Thank @larouxn

**Pull request merged**
