### PR TITLE
Fixing markup of Dokuwallet and CIMBThai icons adding new icon i.e. truemoneywallet

### PR DESCRIPTION
**Pull request by jawad-eGHL**
** Checklist **
- [✓] All icons have a corresponding entry in `db/payment_icons.yml`
- [✓] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [✓] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [✓] I am confident that all icons are clear and easy to read/understand
- [✓] I have provided a link to the brand icon’s brand guidelines whenever possible.

Icon refs:
https://www.doku.com/en/
https://www.cimbthai.com/en/personal/index.html
https://www.truemoney.com/

### CODE REVIEW

**Comment by jawad-eGHL** [comment]
@tauthomas01 and @larouxn  Please review
For dokuwallet and cimbthai I have fixed the markup by appending :xlink to href

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
The tests are failing. Please fix the icons format, which currently are formatted in base64 JPG instead of base64 PNG. ([old PR reference](https://github.com/activemerchant/payment_icons/pull/397))

image

Also, since you previously added those icons, this time will most likely be the last time to use base64 icons because the files are getting too heavy since the [last PR](https://github.com/activemerchant/payment_icons/pull/393) you pushed.

Just to compare with Visa icon, the file size difference is quite big:
[alt](https://screenshot.click/19-46-kc1zk-ik643.png)

Issue: https://github.com/activemerchant/payment_icons/issues/407

**Comment by jawad-eGHL** [comment]
Hi @tauthomas01 , Thanks for your reply.
Basically, the icons are created by our designer and they are not sure how to create the icons with the specification you require e.g. visa.svg. 
Also the icons are to be created by the images available on the internet so it has to be either base64/jpg or base 64/png. Base64/jpg is much smaller in size than base64/png.
It would be great if you can highlight the tools and specification to be used for creating svg icons according to your requirement.
Following are the specifications defined by our designer to generate an icon in adobe illustrator. 
image

**Comment by larouxn** [comment]
👋 @jawad-eGHL, is it possible to generate actual SVGs instead of base64 encoded images? SVGs would be even smaller.

**Comment by rahilvirani** [comment]
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

**Pull request closed without merging**
