### PR TITLE
Wallet icons

### PR DESCRIPTION
**Pull request by jawad-eGHL**
** Checklist **
- [✓] All icons have a corresponding entry in `db/payment_icons.yml`
- [✓] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [✓] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [✓] I am confident that all icons are clear and easy to read/understand
- [✓] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

- https://en.wikipedia.org/wiki/Big_C
- https://www.myboost.com.my/
- https://www.doku.com/en/
- https://www.ecpay.com.ph/
- https://www.maybank2u.com.my/maybank2u/malaysia/en/personal/services/digital_banking/maybank_qrpay_consumer.page
- http://newbackend.mcash.my/
- https://pay.line.me/portal/th/main
- https://en.wikipedia.org/wiki/Tesco_Lotus
- https://www.touchngo.com.my/

### CODE REVIEW

**Comment by jawad-eGHL** [comment]
@tauthomas01 Please review.

**Comment by jawad-eGHL** [comment]
Hi @tauthomas01 , 
the CI checks have failed. 
May I know the reason? 
Is there anything to be done from my side?

**Comment by tauthomas01** [comment]
Hi @jawad-eGHL , the test failed because of this

`test_Payment_icon_SVGs_with__or_<image>_tags_base64-encode_PNG_image_data`

Although I'm not sure what it means but I assume the image tag has some data that CI doesn't like.

Can you convert those `<image>` base64 code into real SVG elements like `<path>`?

**Comment by jawad-eGHL** [comment]
> Hi @jawad-eGHL , the test failed because of this
> 
> `test_Payment_icon_SVGs_with__or_<image>_tags_base64-encode_PNG_image_data`
> 
> Although I'm not sure what it means but I assume the image tag has some data that CI doesn't like.
> 
> Can you convert those `<image>` base64 code into real SVG elements like `<path>`?
> 
> Actually, it would be the best if we avoid `<image>` tags because they're heavy and don't utilize native SVG elements.

Hi @tauthomas01, thanks for the response I will try to convey this to our designer.

**Comment by jawad-eGHL** [comment]
Hi @tauthomas01, I can see that many other icons were accepted by CI having base64 in <image> tag converting to the path may not be possible as the designer has to creat icon through already existing images.

**Comment by tauthomas01** [comment]
Hi @jawad-eGHL , can you try and rebase your branch off `master`?

**Comment by jawad-eGHL** [comment]
Hi @tauthomas01, I have sent a new PR i.e https://github.com/activemerchant/payment_icons/pull/393 so please ignore this one.

**Pull request closed without merging**
