### PR TITLE
Add pei icon

### PR DESCRIPTION
**Pull request by tomaskolbeinn**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

image
```
<!-- Change background color if needed to showcase your icon better -->


<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
<svg width="38" height="24" aria-labelledby="pi-pei" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><title id="pi-pei">Pei</title><defs><path id="a" d="M0 0h38v24H0z"/></defs><clipPath id="b"><use xlink:href="#a" overflow="visible"/></clipPath><g clip-path="url(#b)"><path d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z" opacity=".07"/><path d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32z" fill="#fff"/><path d="M9.7 8.9h2.5v.8c.3-.4.9-1 2-1 1.8 0 3.4 1.6 3.4 3.7 0 2.6-1.5 4.2-3.7 4.2-.9 0-1.5-.4-1.7-.6v3.1H9.7V8.9zm4 2.4c-.8 0-1.4.6-1.4 1.4 0 .8.6 1.4 1.4 1.4.8 0 1.4-.6 1.4-1.4 0-.8-.6-1.4-1.4-1.4zM28 8.9h-2.5v7.5H28V8.9zm-1.3-4c-.9 0-1.6.7-1.6 1.6s.7 1.6 1.6 1.6 1.6-.7 1.6-1.6-.7-1.6-1.6-1.6zm-2.1 8.3c-.5.5-1.5 1.1-2.3 1.1-.4 0-.7-.1-.9-.2l3.8-2.7c-.3-.9-.9-2.7-3.3-2.7-1.7 0-3.9 1.3-3.9 4 0 3.1 2.5 3.9 3.7 3.9 1.4 0 2.4-.5 3-.8v-2.6zm-4.3-.9c0-.9.6-1.4 1.3-1.4.2 0 .7.1.8.3l-2 1.5c-.1-.1-.1-.3-.1-.4z" fill="#ff5338"/></g></svg>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
Andi W | Partner Support Specialist

What's the expected date of this change to deploy on Shopify?
The solution is already in production so as soon as possible would be great.

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
Icon and YML changes look good, but some automated checks are failing. Please resolve these and then I'll aprove.

**Comment by tomaskolbeinn** [comment]
@Jacquesattaque I reuploaded the icon

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Screenshot 2023-02-01 at 8 43 02 AM

I actually don't think there was an issue with the icon before, but there is now. The main paths were moved to the right by 0.27px and now the border is being cut off. Please update a new icon.

**Comment by tomaskolbeinn** [comment]
@Jacquesattaque It's hopefully been fixed now, the svgo command apparently added transform=translate(0.269) which shifted the image to the right by 0.27px. I replaced 0.27 with 0 so it should not be shifted.

**Comment by Jacquesattaque** [comment]
@tomaskolbeinn Nope, still cut off.

**Comment by tomaskolbeinn** [comment]
I looked at it on figma and it appeared to not be shifted so I hope it works now.

**Comment by Jacquesattaque** [comment]
@tomaskolbeinn Icon looks good! You've got some failing automated checks and conflicts to resolve. Once those are clear I'll approve.

**Comment by Jacquesattaque** [comment]
@tomaskolbeinn Please resolve conflicts and I'll approve

**Comment by tomaskolbeinn** [comment]
@Jacquesattaque I have resolved the conflicts

**Comment by Jacquesattaque** [comment]
@tomaskolbeinn Still have some failing checks to resolve.

**Comment by tomaskolbeinn** [comment]
I tested locally and all the tests passed

**Pull request merged**
