### PR TITLE
Link Pay Icon for new Payment Method

### PR DESCRIPTION
**Pull request by amritlink**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by amritlink** [comment]
Can we please review this PR.

**Comment by fjmarcos98** [comment]
Hello, can we please have this PR reviewed.

**Review by larouxn — CHANGES_REQUESTED** [review]
👋 Hello, can we please run the [SVGO optimization](https://github.com/activemerchant/payment_icons/blob/1718930efb56ba4853bb4a4961cb75dc34996533/CONTRIBUTING.md) (step 5)/ensure the SVG is a single line? ([CI logs](https://github.com/activemerchant/payment_icons/runs/7738490972?check_suite_focus=true))

**Comment by amritlink** [comment]
@larouxn : We have updated the PR based on review comments. Please help review. Thank you.

**Comment by fjmarcos98** [comment]
@larouxn We have updated the PR based on your feedback. Please help review. Thanks!

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-08-17 at 9 57 01

**Comment by larouxn** [comment]
Icon has been merged but still needs to be released and rolled out. Targeting live this week.

**Comment by larouxn** [comment]
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

**Comment by fjmarcos98** [comment]
Thank you @larouxn !! Appreciate the help

**Pull request merged**
