### PR TITLE
Svea Ostukonto

### PR DESCRIPTION
**Pull request by aleahon**
## Why are you adding this icons?
I'm adding/updating this icon(s) because I'm working for Svea Payments

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: https://sveapayments.atlassian.net/wiki/spaces/DOCS/pages/786489/Svea+Payments+Brand+Guide

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon with the black background

```
<style> body { background: black; } </style>
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>
@@ -0,0 +1 @@
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" aria-labelledby="pi-sveaOstukonto"><title id="pi-sveaOstukonto">Svea Ostukonto</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path fill="#002c50" d="M14.64 15.05c-.25 0-.28-.13-.28-.23 0-.2.1-.29.36-.29h1.35v-.6h-1.43c-.64 0-.94.27-.94.84 0 .54.28.79.89.79h.58c.26 0 .35.06.35.26 0 .16-.06.25-.38.25h-1.42v.6h1.51c.64 0 .94-.27.94-.83s-.25-.78-.87-.78M18.34 13.97l-.76 1.87-.74-1.87h-.73l1.17 2.73h.63l1.12-2.73h-.69zM21.05 14.47l.05-.53h-.95c-.86 0-1.27.45-1.27 1.41 0 .5.14.85.42 1.08s.54.24.83.24h.97v-.6h-.9c-.37 0-.52-.14-.53-.51h1.43v-.6h-1.52c.03-.34.21-.5.55-.5M22.6 14.67l.31.8h-.61l.3-.8zm-.3-.73l-1.14 2.73h.73l.22-.6h1.01l.23.6h.75l-1.15-2.73h-.64z"/><path fill="#00abc8" d="M23.87 17.87H13.84c-.07 0-.12-.05-.13-.12v-.44c0-.07.06-.13.13-.13h10.07c.07 0 .13.06.13.13v.44c0 .07-.06.13-.13.13"/><path fill="#00325c" d="M5.75 9.97c-.33-.37-.5-.9-.5-1.59s.17-1.22.5-1.59.81-.56 1.43-.56 1.09.19 1.42.56.5.9.5 1.59-.17 1.22-.5 1.59c-.33.37-.8.55-1.42.55s-1.1-.19-1.43-.55zm2.15-.58c.16-.23.25-.57.25-1.01s-.08-.78-.25-1.01-.41-.35-.73-.35-.56.12-.73.35-.25.57-.25 1.01.08.78.25 1.01.41.35.73.35.56-.12.73-.35zM9.87 10.41c-.21-.08-.31-.17-.31-.29 0-.08.04-.18.11-.29.08-.11.14-.17.2-.17.03 0 .08.02.13.05.08.04.16.06.23.09.07.02.15.03.24.03.11 0 .2-.02.26-.07.06-.04.09-.11.09-.19 0-.07-.02-.13-.07-.17s-.09-.08-.14-.1-.15-.06-.31-.12c-.2-.08-.37-.18-.5-.31s-.19-.32-.19-.59c0-.31.1-.55.29-.72.2-.17.46-.26.8-.26.21 0 .42.03.61.09s.29.15.29.26c0 .08-.03.17-.09.29-.06.12-.12.18-.17.18-.02 0-.07-.02-.17-.06a.897.897 0 00-.34-.06c-.21 0-.32.07-.32.21 0 .09.04.16.1.2.07.05.18.1.33.16.02.01.06.03.11.05.05.02.1.04.13.06.16.08.29.18.38.31s.14.3.14.52c0 .31-.1.56-.31.75s-.5.28-.86.28c-.25 0-.48-.04-.68-.11zM12.31 9.55V8.04h-.1c-.06 0-.11-.02-.14-.07-.03-.05-.04-.12-.04-.23v-.1c0-.1.01-.18.04-.23.03-.05.07-.07.14-.07h.1l.08-.57c.02-.13.13-.19.32-.19h.19c.2 0 .3.06.3.19v.57h.29c.06 0 .11.02.14.07.03.05.04.12.04.23v.1c0 .1-.01.18-.04.23-.03.05-.07.07-.14.07h-.29v1.52c0 .09.02.16.05.2.03.04.09.06.17.06.02 0 .05 0 .08-.01.03 0 .06-.01.08-.01.04 0 .07.03.1.09s.05.13.07.2c.02.07.02.12.02.14 0 .2-.19.29-.58.29-.58 0-.88-.32-.88-.97zM14.47 10.29c-.14-.16-.22-.4-.22-.73V7.53c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v1.9c0 .12.03.22.08.28.06.06.15.09.28.09.11 0 .2-.03.29-.1.08-.07.15-.15.2-.24V7.53c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v1.9c0 .18 0 .32.02.42 0 .1.02.2.04.32.01.05.02.1.02.13 0 .06-.08.11-.24.14-.16.03-.3.05-.43.05-.07 0-.12-.03-.15-.09a.603.603 0 01-.06-.19.783.783 0 00-.03-.14 1.135 1.135 0 01-.89.45c-.3 0-.52-.08-.67-.24zM20.34 10.4c0 .06-.11.09-.34.09h-.25c-.2 0-.32-.04-.36-.11L18.56 9h-.02v1.3c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19V6.15c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v2.38h.02l.73-1.08s.08-.08.13-.09.13-.02.23-.02h.22c.22 0 .34.03.34.09 0 .03-.02.07-.05.12l-.83 1.19.98 1.55s.05.09.05.13zM20.99 10.11c-.25-.28-.37-.68-.37-1.2s.12-.92.37-1.2.61-.41 1.09-.41.84.14 1.08.41.37.68.37 1.2-.12.92-.37 1.2c-.25.28-.61.42-1.08.42s-.84-.14-1.09-.42zm1.5-.52c.09-.15.13-.38.13-.69s-.04-.53-.13-.68c-.09-.15-.23-.23-.42-.23s-.33.08-.42.23c-.09.15-.14.38-.14.68 0 .61.19.92.56.92.19 0 .33-.08.42-.23zM24.15 10.3V8.4c0-.18 0-.31-.01-.4-.01-.09-.02-.2-.04-.31-.01-.06-.02-.1-.02-.13 0-.06.08-.11.24-.14.16-.03.3-.05.43-.05.07 0 .12.03.15.08s.05.11.06.18c.01.06.02.11.03.13.1-.13.22-.24.38-.32.16-.09.33-.13.51-.13.3 0 .52.08.67.24.14.16.22.4.22.74v2.03c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19v-1.9c0-.12-.03-.22-.08-.28-.06-.06-.15-.09-.28-.09-.11 0-.2.04-.29.1-.08.07-.15.15-.2.24v1.93c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19zM27.59 9.55V8.04h-.1c-.06 0-.11-.02-.14-.07-.03-.05-.04-.12-.04-.23v-.1c0-.1.01-.18.04-.23.03-.05.07-.07.14-.07h.1l.08-.57c.02-.13.13-.19.32-.19h.19c.2 0 .3.06.3.19v.57h.29c.06 0 .11.02.14.07.03.05.04.12.04.23v.1c0 .1-.01.18-.04.23-.03.05-.07.07-.14.07h-.29v1.52c0 .09.02.16.05.2.03.04.09.06.17.06.02 0 .05 0 .08-.01.03 0 .06-.01.08-.01.04 0 .07.03.1.09s.05.13.07.2c.02.07.02.12.02.14 0 .2-.19.29-.58.29-.58 0-.88-.32-.88-.97zM29.8 10.11c-.25-.28-.37-.68-.37-1.2s.12-.92.37-1.2.61-.41 1.09-.41.84.14 1.08.41.37.68.37 1.2-.12.92-.37 1.2c-.25.28-.61.42-1.08.42s-.84-.14-1.09-.42zm1.5-.52c.09-.15.13-.38.13-.69s-.04-.53-.13-.68c-.09-.15-.23-.23-.42-.23s-.33.08-.42.23c-.09.15-.14.38-.14.68 0 .61.19.92.56.92.19 0 .33-.08.42-.23z"/></svg>
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" aria-labelledby="pi-sveaCreditAccount"><title id="pi-sveaCreditAccount">Svea Credit account</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path fill="#002c50" d="M14.64 15.05c-.25 0-.28-.13-.28-.23 0-.2.1-.29.36-.29h1.35v-.6h-1.43c-.64 0-.94.27-.94.84 0 .54.28.79.89.79h.58c.26 0 .35.06.35.26 0 .16-.06.25-.38.25h-1.42v.6h1.51c.64 0 .94-.27.94-.83s-.25-.78-.87-.78M18.34 13.97l-.76 1.87-.74-1.87h-.73l1.17 2.73h.63l1.12-2.73h-.69zM21.05 14.47l.05-.53h-.95c-.86 0-1.27.45-1.27 1.41 0 .5.14.85.42 1.08s.54.24.83.24h.97v-.6h-.9c-.37 0-.52-.14-.53-.51h1.43v-.6h-1.52c.03-.34.21-.5.55-.5M22.6 14.67l.31.8h-.61l.3-.8zm-.3-.73l-1.14 2.73h.73l.22-.6h1.01l.23.6h.75l-1.15-2.73h-.64z"/><path fill="#00abc8" d="M23.87 17.87H13.84c-.07 0-.12-.05-.13-.12v-.44c0-.07.06-.13.13-.13h10.07c.07 0 .13.06.13.13v.44c0 .07-.06.13-.13.13"/><path fill="#00325c" d="M11.67 5.22c-.32-.35-.48-.9-.48-1.63 0-1.42.67-2.14 2-2.14.2 0 .4.02.61.06s.37.1.49.17c.1.06.16.12.16.19 0 .06-.02.13-.07.22-.04.09-.1.17-.16.24-.06.07-.12.1-.17.1-.01 0-.06-.02-.14-.05-.08-.04-.19-.07-.31-.1s-.26-.04-.43-.04c-.35 0-.61.11-.78.34-.17.22-.25.56-.25 1.01 0 .91.34 1.37 1.03 1.37.18 0 .34-.02.47-.05s.26-.08.38-.14c.06-.03.11-.05.13-.05.06 0 .12.03.17.1.05.07.1.15.13.23.03.09.05.15.05.19 0 .1-.07.2-.21.28-.13.08-.31.13-.52.17-.22.04-.42.06-.61.06-.67 0-1.17-.17-1.49-.52zM15 5.51v-1.9c0-.18 0-.31-.01-.4-.01-.09-.02-.2-.04-.31-.01-.06-.02-.1-.02-.13 0-.06.08-.11.24-.14.16-.03.3-.05.43-.05.07 0 .12.03.15.08s.05.11.06.18c.01.06.02.11.03.13.08-.14.17-.25.27-.33.1-.08.23-.12.39-.12.13 0 .22.03.27.1s.08.14.08.23-.02.19-.05.31-.08.19-.13.19c-.02 0-.07 0-.13-.02s-.11-.02-.16-.02c-.11 0-.2.03-.29.09s-.15.13-.2.21v1.93c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19zM17.46 5.32c-.26-.28-.39-.67-.39-1.17 0-.56.13-.98.39-1.24s.62-.4 1.07-.4.77.14.98.43.31.66.31 1.12c0 .05-.04.12-.12.21-.08.09-.14.14-.18.14h-1.53c.02.23.09.39.2.49.12.1.28.14.49.14.11 0 .21-.01.31-.04s.19-.06.29-.1c.06-.03.11-.05.13-.05.04 0 .08.03.13.09s.09.12.13.2c.03.07.05.13.05.17 0 .09-.06.17-.19.24s-.27.12-.44.15-.32.05-.45.05c-.53 0-.92-.14-1.18-.42zm1.5-1.5c0-.18-.04-.33-.11-.44a.361.361 0 00-.32-.17c-.3 0-.48.2-.54.61h.97zM20.85 5.55c-.17-.13-.3-.31-.4-.55-.1-.24-.14-.54-.14-.88 0-.5.11-.89.33-1.18s.53-.44.93-.44c.24 0 .44.06.61.19V1.36c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v3.28c0 .18 0 .32.02.42 0 .1.02.2.04.32.01.05.02.1.02.13 0 .06-.08.11-.24.14-.16.03-.3.05-.43.05-.07 0-.12-.03-.15-.09s-.05-.12-.06-.19-.02-.11-.03-.13a.82.82 0 01-.32.32c-.14.08-.3.13-.48.13-.22 0-.41-.06-.58-.19zm1.33-.89V3.32a.825.825 0 00-.42-.11c-.37 0-.56.3-.56.91s.16.89.49.89c.19 0 .36-.12.49-.35zM23.8 1.94v-.43c0-.15.15-.22.44-.22s.44.07.44.22v.43c0 .15-.15.23-.44.23s-.44-.08-.44-.23zm0 3.58V2.74c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v2.78c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19zM25.5 4.77V3.26h-.1c-.06 0-.11-.02-.14-.07-.03-.05-.04-.12-.04-.23v-.1c0-.1.01-.18.04-.23.03-.05.07-.07.14-.07h.1l.08-.57c.02-.13.13-.19.32-.19h.19c.2 0 .3.06.3.19v.57h.29c.06 0 .11.02.14.07.03.05.04.12.04.23v.1c0 .1-.01.18-.04.23-.03.05-.07.07-.14.07h-.29v1.52c0 .09.02.16.05.2.03.04.09.06.17.06.02 0 .05 0 .08-.01.03 0 .06-.01.08-.01.04 0 .07.03.1.09s.05.13.07.2c.02.07.02.12.02.14 0 .2-.19.29-.58.29-.58 0-.88-.32-.88-.97zM8.84 10.5c-.14-.16-.21-.37-.21-.64 0-.32.12-.59.35-.8.23-.21.69-.32 1.37-.32v-.2c0-.12-.04-.2-.11-.26s-.19-.08-.36-.08a1.322 1.322 0 00-.63.14c-.08.04-.13.05-.14.05-.04 0-.08-.03-.13-.09a1.07 1.07 0 01-.13-.21.407.407 0 01-.05-.18c0-.07.05-.13.15-.2.1-.06.24-.12.41-.16.18-.04.37-.06.58-.06.45 0 .78.09.98.27.2.18.31.42.31.73v1.13c0 .18 0 .32.01.42 0 .1.02.2.04.32.01.05.02.1.02.13 0 .06-.08.11-.24.14-.16.03-.31.05-.43.05-.07 0-.12-.03-.15-.09s-.05-.12-.06-.19-.02-.11-.03-.14c-.02.04-.07.1-.14.17s-.17.13-.3.19-.27.09-.44.09c-.31 0-.53-.08-.67-.24zm1.29-.57c.1-.07.17-.16.22-.27v-.33c-.56 0-.84.15-.84.44 0 .08.03.14.08.19s.13.07.22.07c.11 0 .22-.04.32-.11zM12.27 10.35c-.25-.26-.37-.66-.37-1.2s.12-.95.38-1.23.64-.41 1.17-.41c.24 0 .47.04.68.11.21.07.32.18.32.3 0 .06-.04.15-.12.28s-.15.19-.2.19c-.02 0-.05-.01-.11-.04-.08-.04-.16-.07-.24-.1-.08-.02-.17-.04-.29-.04-.24 0-.41.07-.52.22-.11.15-.16.38-.16.69s.05.54.15.69c.1.15.26.23.49.23.1 0 .2-.01.28-.03s.15-.04.2-.06.09-.03.1-.04c.06-.02.1-.04.11-.04.04 0 .08.03.13.09s.09.12.13.2.05.13.05.17c0 .1-.07.18-.2.25-.13.06-.29.11-.45.13-.17.03-.3.04-.4.04-.51 0-.89-.13-1.14-.39zM15.18 10.35c-.25-.26-.37-.66-.37-1.2s.12-.95.38-1.23.64-.41 1.17-.41c.24 0 .47.04.68.11.21.07.32.18.32.3 0 .06-.04.15-.12.28s-.15.19-.2.19c-.02 0-.05-.01-.11-.04-.08-.04-.16-.07-.24-.1-.08-.02-.17-.04-.29-.04-.24 0-.41.07-.52.22-.11.15-.16.38-.16.69s.05.54.15.69c.1.15.26.23.49.23.1 0 .2-.01.28-.03s.15-.04.2-.06.09-.03.1-.04c.06-.02.1-.04.11-.04.04 0 .08.03.13.09s.09.12.13.2.05.13.05.17c0 .1-.07.18-.2.25-.13.06-.29.11-.45.13-.17.03-.3.04-.4.04-.51 0-.89-.13-1.14-.39zM18.09 10.33c-.25-.28-.37-.68-.37-1.2s.12-.92.37-1.2.61-.41 1.09-.41.84.14 1.08.41.37.68.37 1.2-.12.92-.37 1.2c-.25.28-.61.42-1.08.42s-.84-.14-1.09-.42zm1.5-.52c.09-.15.13-.38.13-.69s-.04-.53-.13-.68c-.09-.15-.23-.23-.42-.23s-.33.08-.42.23c-.09.15-.14.38-.14.68 0 .61.19.92.56.92.19 0 .33-.08.42-.23zM21.45 10.51c-.14-.16-.22-.4-.22-.73V7.75c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v1.9c0 .12.03.22.08.28.06.06.15.09.28.09.11 0 .2-.03.29-.1.08-.07.15-.15.2-.24V7.75c0-.13.12-.19.36-.19h.17c.24 0 .36.06.36.19v1.9c0 .18 0 .32.02.42 0 .1.02.2.04.32.01.05.02.1.02.13 0 .06-.08.11-.24.14-.16.03-.3.05-.43.05-.07 0-.12-.03-.15-.09a.603.603 0 01-.06-.19.783.783 0 00-.03-.14 1.135 1.135 0 01-.89.45c-.3 0-.52-.08-.67-.24zM24.6 10.51v-1.9c0-.18 0-.31-.01-.4-.01-.09-.02-.2-.04-.31-.01-.06-.02-.1-.02-.13 0-.06.08-.11.24-.14.16-.03.3-.05.43-.05.07 0 .12.03.15.08s.05.11.06.18c.01.06.02.11.03.13.1-.13.22-.24.38-.32.16-.09.33-.13.51-.13.3 0 .52.08.67.24.14.16.22.4.22.74v2.03c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19v-1.9c0-.12-.03-.22-.08-.28-.06-.06-.15-.09-.28-.09-.11 0-.2.04-.29.1-.08.07-.15.15-.2.24v1.93c0 .13-.12.19-.36.19h-.17c-.24 0-.36-.06-.36-.19zM28.03 9.77V8.26h-.1c-.06 0-.11-.02-.14-.07-.03-.05-.04-.12-.04-.23v-.1c0-.1.01-.18.04-.23.03-.05.07-.07.14-.07h.1l.08-.57c.02-.13.13-.19.32-.19h.19c.2 0 .3.06.3.19v.57h.29c.06 0 .11.02.14.07.03.05.04.12.04.23v.1c0 .1-.01.18-.04.23-.03.05-.07.07-.14.07h-.29v1.52c0 .09.02.16.05.2.03.04.09.06.17.06.02 0 .05 0 .08-.01.03 0 .06-.01.08-.01.04 0 .07.03.1.09s.05.13.07.2c.02.07.02.12.02.14 0 .2-.19.29-.58.29-.58 0-.88-.32-.88-.97z"/></svg>
```
image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? 
- @aleahon

What's the expected date of this change to deploy on Shopify?
- soon as possible. Shop that uses payment method is already online.

### CODE REVIEW

**Comment by rahilvirani** [comment]
@aleahon is there a reason to not middle align vertically for `Credit Account - SVEA` icon?

**Comment by aleahon** [comment]
yeah. Marketing wants to keep svea on same line. Luckily Ostukonto is primary image. I'm not even sure if english version is goin to be used.

**Comment by rahilvirani** [comment]
@aleahon few of the tests are failing, once you've fixed them I can review the svgs

**Comment by aleahon** [comment]
@rahilvirani I added roles back to image. Strange that svg lost role and viewbox after I run SVGO from instructions. 

Last failing test wasn't our image.
{:message=>"The 'bbvacie' SVG file does not have the appropriate <title> value"}.
Expected: "Bbvacie"
  Actual: "BBVA CIE"

**Comment by aleahon** [comment]
@rahilvirani is our images now ready to merge?

**Pull request merged**
