### PR TITLE
Add DirectPay icon

### PR DESCRIPTION
**Pull request by eoeoms**
I couldn't find where I'm supposed to provide the brand guidelines link.
Here's the [link for our icon's brand guideline](https://drive.google.com/file/d/1hCwBZ8jZrS69tSVcHgyBU05jtN6LOza1/view), but please let me know if there's a more appropriate place for it.

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
LGTM 🎩 
Screen Shot 2022-01-06 at 21 00 06

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 @eoeoms, we'll try to get this icon live within the month. Will report back here when it's live.

**Comment by eoeoms** [comment]
@larouxn Sounds good, thanks!

**Comment by larouxn** [comment]
👋 @eoeoms, the DirectPay icon should now be available everywhere.

**Pull request merged**
