### PR TITLE
Add acuotaz icon

### PR DESCRIPTION
**Pull request by andyapurata**
## Why are you adding this icons?
I'm adding/updating this icon(s) because I am adding a new offsite payment method

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: N/A

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

Captura de pantalla 2023-09-11 210307

#### If the icons are intended for use by Shopify, please provide the following info:
We have some merchants interested in using our payment method and their stores are on Shopify.

What's the expected date of this change to deploy on Shopify?
We hope that it can be deployed as soon as possible, since the integration is already completed and we need the logo to launch it into production

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
The icon appears to have been resized inside the frame and as a result is too small. Please check the icon and resubmit.

**Comment by andyapurata** [comment]
I updated the SVG , this is a preview
Captura de pantalla 2023-09-13 120929

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
The icon still isn't the correct size (it's now 37.71 px x 23.81px) — please use our template to ensure the icon and the border are the right size. You can find the template in the contribution guidelines.

**Comment by andyapurata** [comment]
We remade the logo again. We believe that now they have the correct sizes.
Captura de pantalla 2023-09-13 163749

**Comment by Jacquesattaque** [comment]
That code draws the frame, which is the right size, but there must be a transform happening somewhere in your code that's moving the icon within the frame. If you open the icon in any imaging software you'll see this:
Screenshot 2023-09-13 at 4 18 53 PM

**Comment by andyapurata** [comment]
We believe that we have already found the problem, we have already push the change

**Comment by andyapurata** [comment]
Hello @Jacquesattaque, I just updated the title in the svg due to an error that I saw in the executed jobs.

**Comment by andyapurata** [comment]
I solved the problem with linear gradient id

**Review by Jacquesattaque — APPROVED** [review]

**Comment by andyapurata** [comment]
Thanks for the approval @Jacquesattaque , what should I do now and when would the logo be available?

**Comment by Jacquesattaque** [comment]
We do a monthly release on the first Wednesday of every month. The next release is tentatively scheduled for October 4.

**Pull request merged**
