### PR TITLE
Update kakao_pay.svg

### PR DESCRIPTION
**Pull request by yguan06**
Our Company is AsiaBill which is one of Shopify partners.
We accept a new payment method-Kakao Pay recently（The gateway name is Kakao Pay (Alipay+™ Partner) ）but our partner Alipay+™ challenge the background color of the Kakao pay  icon isn't correct：it should be in yellow but now it is in white.
This pr is to update kakao_pay.svg by changing the background color.

image 
image

### CODE REVIEW

**Review by larouxn — COMMENTED** [review]
Generally this change makes sense as I'm seeing Kakao Pay _is_ yellow according to https://www.kakaocorp.com/page/service/service/KakaoPay. However, I'm curious, how did we choose the yellow here? Looks like the yellow on Kakao Corp's website is different. Should we use that yellow instead?
Screenshot from 2021-09-21 09-18-13

**Comment by yguan06** [comment]
Using color picker to choose the yellow on Kakao Corp's website and update.

**Comment by yguan06** [comment]
🆒

**Review by larouxn — APPROVED** [review]

**Comment by yguan06** [comment]
🆒

**Comment by yguan06** [comment]
Hi @tauthomas01，could you help me to merge my pr？ Thanks a lot！

**Review by tauthomas01 — APPROVED** [review]
Looks good

**Comment by larouxn** [comment]
👋  Ran into a few release pipeline issues. Hoping to have this live by end of next week, potentially sooner.

**Comment by larouxn** [comment]
👋 Hello again, your update icon should be live everywhere now.

**Pull request merged**
