### PR TITLE
Add AstraPay

### PR DESCRIPTION
**Pull request by ikanyu**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by andykim** [comment]
HI @larouxn Can you review this PR? Thanks

**Comment by ikanyu** [comment]
@larouxn Can you review this PR? Thanks! 🙂

**Comment by larouxn** [comment]
👋 Hello all. Looks like some adjustments need to be made.

https://github.com/activemerchant/payment_icons/runs/7738486912?check_suite_focus=true

**Comment by ikanyu** [comment]
@larouxn Fixed :) Please review again

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the shape of the icon is off. Perhaps the [template](https://github.com/activemerchant/payment_icons/blob/1718930efb56ba4853bb4a4961cb75dc34996533/CONTRIBUTING.md#template) might help.
Screenshot from 2022-08-09 20-33-08

**Comment by ikanyu** [comment]
@larouxn I've rectified it 🙂

**Comment by larouxn** [comment]
👋 @ikanyu, can we shrink the icon a bit? It's currently touching the sides.
Screen Shot 2022-08-17 at 11 02 37

**Comment by ikanyu** [comment]
@larouxn Shrinked the icon. Please review again 😉

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
image

**Pull request merged**
