### PR TITLE
adds underpay logo icon

### PR DESCRIPTION
**Pull request by dimatarasenko1**
## Why are you adding this icons?
I'm adding/updating this icon because we are publishing the Underpay payment gateway app for review and distribution.

#### Help us identify yourself
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.

Link to the brand guidelines: N/A

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? Payment Partner Account ID: 3007420

What's the expected date of this change to deploy on Shopify? App adding the Underpay payment method submitted for approval

### CODE REVIEW

**Comment by Bar-underpay** [comment]
> Please use our template for the SVG. The rounded corners are different here and the border presents as a different shade the way it's stacked in your file.

Hi @Jacquesattaque, I have updated the border of the logo. Can you please check again?

**Comment by Jacquesattaque** [comment]
Looks like the black border was adjusted, but the white vector underneath wasn't. Please use the template we provide to avoid these issues.

Screenshot 2023-10-17 at 1 51 36 PM

**Comment by Bar-underpay** [comment]
Sure @Jacquesattaque. Now I have used the provided template.

Can you please check again?

**Comment by Bar-underpay** [comment]
@Jacquesattaque Any update here?

**Comment by Jacquesattaque** [comment]
@Bar-underpay You still have failing automated checks to clear.

**Comment by Bar-underpay** [comment]
@Jacquesattaque I have fixed checks errors. Can you please check again?

**Review by Jacquesattaque — APPROVED** [review]

**Comment by dimatarasenko1** [comment]
@Jacquesattaque Hi. Do you have a read on when this will be merged and how it will propagate to our payment method? 

Here is the approved app link, we're just starting to onboard merchants so it's important to have the icon pulling through on the checkout page soon. [https://apps.shopify.com/underpay](https://apps.shopify.com/underpay)

Thank you!

**Comment by Jacquesattaque** [comment]
@dimatarasenko1 Icons are updated in a monthly release, usually the first Wednesday of every month. The next release is tentatively scheduled for next Wednesday, November 1.

**Comment by adeniyiao** [comment]
Hi @dimatarasenko1 

Could you please rebase this branch with activemerchant/master to resolve the conflicts.

**Comment by Bar-underpay** [comment]
Hi @adeniyiao 

I have rebased the branch. Can you please merge now? 

Thank you!

**Comment by dimatarasenko1** [comment]
@Jacquesattaque or @adeniyiao - now that this is merged, do you have any info for how to get this to propagate to be displayed next to our payment option on the checkout page? 
Many thanks!

**Comment by Jacquesattaque** [comment]
@dimatarasenko1 If you add the payment methods to your app in the partner dashboard, they should show up in admin and on checkout. Let us know if you have any issues.

**Pull request merged**
