### PR TITLE
Add icon for EPOS Kantan Kessai

### PR DESCRIPTION
**Pull request by zuccamia**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
(Brand guidelines are not available for this icon)

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 @zuccamia, thanks for the contribution! Quick heads up that the icon likely won't be live for a few weeks at least since we'll be batching it with some other icons and doing the rollout after that.

**Comment by zuccamia** [comment]
Got it, thanks for the headsup @larouxn ! I've accounted in the time 👍

**Comment by zuccamia** [comment]
Hi @larouxn, may I know the estimated time for the next version release?

**Comment by larouxn** [comment]
👋 @zuccamia, I would expect the next release and icon rollout to be completed within this month. At the earliest by end of next week.

**Comment by zuccamia** [comment]
Got it, thanks @larouxn ! It's probably a long shot but do you happen to know about how long it would take after the icon release until the payment method is available for Shopify payments extension?

**Comment by larouxn** [comment]
I expect the icons will be live within this week. At the latest next week. Hoping to release [v1.7.11](https://github.com/activemerchant/payment_icons/pull/553) tomorrow.

**Comment by larouxn** [comment]
👋 Hello hello, your icon(s) should be live everywhere now. Please let us know if otherwise. 🙇‍♂️

**Comment by zuccamia** [comment]
Thanks so much @larouxn ! We were able to add the new payment methods today 🎉

**Pull request merged**
