### PR TITLE
Giftcard

### PR DESCRIPTION
**Pull request by JoostMollie**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hello @JoostMollie, looks like we already have a giftcard icon over here.
https://github.com/activemerchant/payment_icons/blob/8cc69fcbdf8c73e0ccef9010982587227825bf4f/app/assets/images/payment_icons/gift-card.svg

I recommend you either use that icon or propose a change to it. We should not have both `gift-card` and `giftcard`.

CC @tauthomas01

**Comment by JoostMollie** [comment]
Ah I didn't see that one. But that one is not showing up in the list of payment methods for the Payment extension. 

Screenshot 2021-12-02 at 16 22 16
t

**Comment by larouxn** [comment]
> Ah I didn't see that one. But that one is not showing up in the list of payment methods for the Payment extension.

Ah I see. Might need to look into adding support for the gift card method in there.

**Comment by JoostMollie** [comment]
When can we expect to have the existing gift-card added as a payment method?

**Comment by larouxn** [comment]
> When can we expect to have the existing gift-card added as a payment method?

I'm hoping to have gift-card as an option by end of next week at the latest.

**Comment by larouxn** [comment]
👋 @JoostMollie, we have some changes lined up to make "gift card" available in all places. Should be ready this week.

**Comment by larouxn** [comment]
👋 @JoostMollie, the gift card icon should be available everywhere now. Have a great day! ☀️

**Comment by JoostMollie** [comment]
It is not showing up in the payment extensions for me. 

Screenshot 2021-12-15 at 11 31 18

**Comment by larouxn** [comment]
> It is not showing up in the payment extensions for me.
> 
> Screenshot 2021-12-15 at 11 31 18

Hmm, can you confirm for me where are you not seeing it? Is that in the Partner dashboard?

**Comment by JoostMollie** [comment]
Yes, partner dashboard. In the new Payment extensions for Apps.

For example:
https://partners.shopify.com/523801/apps/6164685/extensions/payments/3933885/version/edit

**Comment by larouxn** [comment]
> Yes, partner dashboard. In the new Payment extensions for Apps.

I see I see. I think we know the root cause of that unexpected behaviour. Looking into it now. Hoping to get it fixed soon.

**Comment by larouxn** [comment]
We have shipped a potential fix for the missing `Gift Card` issue. @JoostMollie, can you take a look again? Thank you.

**Comment by JoostMollie** [comment]
Yes it is showing up now! :)

**Comment by larouxn** [comment]
👋 @JoostMollie, as it appears the gift card icon issue has been resolved, I'm closing this PR. Feel free to re-open and/or open an issue if something still doesn't look right. Thank you as always for your collaboration.

**Pull request closed without merging**
