### PR TITLE
Update ada.svg

### PR DESCRIPTION
**Pull request by ptrdsh**
## Why are you adding this icons?
I'm updating this icon because the previous version was not very well identifiable ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: https://cardanofoundation.org/en/trademark-policy

## Attach a screenshot of the icon along side the example Visa icon
image

### CODE REVIEW

**Review by hellicarusprime — APPROVED** [review]

**Comment by adeniyiao** [comment]
Hi @ptrdsh ,


Kindly address the issues with the checks.

image

Regards

**Comment by ptrdsh** [comment]
Thanks @adeniyiao and sorry for the oversight!
added now.

**Comment by adeniyiao** [comment]
> Thanks @adeniyiao and sorry for the oversight! added now.

No worries, could you please fix this new issue. Thanks

```
{:message=>"The 'ada' SVG file should have a <title> tag as first child of the root <svg> tag"}.
Expected: "title"
  Actual: "g"
```
image

**Comment by ptrdsh** [comment]
I hope its ok now @adeniyiao - thanks for your patience and effort :)

**Comment by ptrdsh** [comment]
@adeniyiao - its been an odd ride of back and forth, for which im terribly sorry, but could you look into this once more? 🙏

**Review by hellicarusprime — APPROVED** [review]

**Review by hellicarusprime — APPROVED** [review]

**Comment by ptrdsh** [comment]
@hellicarusprime - first off.. thanks a lot and sorry for the back and forth!

I please kindly need help on this error - i tried resolving it, but as evident above, it didnt work.. I now plainly copy-pasted the attributes from the svg that worked previously and compared them to other new svg change PRs (like the recent AmEx change), but to no avail either.. by now im clueless what the problem is. 

Thanks for your help!

```
Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:89]:
{:message=>"The 'a' ID should be pi-ada-a (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "a".
```

**Comment by hellicarusprime** [comment]
@ptrdsh It might be because this `<clipPath id="a"><path fill="#fff" d="M0 0h38v24H0z"></path></clipPath>` is missing the `pi-` for the id. It should probably be `<clipPath id="pi-a">...`

**Comment by ptrdsh** [comment]
AH! there is another id reference in the end 🤦 
i hope this is it. 

Thank you @hellicarusprime !!

**Pull request merged**
