### PR TITLE
add mode icon and db entry

### PR DESCRIPTION
**Pull request by Rikmorn**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
Hi,

Please follow the [contributions](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) guideline:
- The border of the icon is missing

You can follow this [example icon](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/visa.svg) as a reference.

[video demonstration](https://screenshot.click/26-52-cyr0o-fzyy6.mp4)

**Comment by Rikmorn** [comment]
Thanks @tauthomas01 will add

**Comment by Rikmorn** [comment]
@tauthomas01 We've added the missing border

**Review by larouxn — APPROVED** [review]
🎩 Looks good to me now 🎩 
Screen Shot 2022-01-29 at 09 47 44

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 @Rikmorn, the icon looks good. Can you rebase this PR against latest master to resolve the merge conflicts?

**Comment by Rikmorn** [comment]
@larouxn all done

**Comment by larouxn** [comment]
👋 @Rikmorn, terribly sorry, seems there are some more conflicts due to some other icons that were just merged. If you can fix this up once more we'll get it merged right away. 🙇‍♂️ 

(tip, it helps to place your `payment_icons.yml` entry above the bottom/towards the middle of the file)

**Comment by Rikmorn** [comment]
Hi @larouxn no problem, I've placed the DB entry somewhere in middle so hopefully there should be no more conflicts.

**Comment by larouxn** [comment]
👋 @Rikmorn, thanks for the contribution! Quick heads up that the icon likely won't be live for a few weeks at least since we'll be batching it with some other icons and doing the rollout after that.

**Comment by Rikmorn** [comment]
No problem @larouxn thanks for merging.

**Comment by larouxn** [comment]
👋 Hello hello, your icon(s) should be live everywhere now. Please let us know if otherwise. 🙇‍♂️

**Pull request merged**
