### PR TITLE
New crypto icons

### PR DESCRIPTION
**Pull request by bubblebees**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by bubblebees** [comment]
@larouxn hello! let me know if there are any issues with this set of icons.

**Comment by rahilvirani** [comment]
@bubblebees the icons are not following the markup according to the [contributing guidelines here to add a new icon](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons). Here are few of the things I noticed:
- `viewBox` and `role` attributes are missing in the svg tag
- `<title>` tag is missing
- `id` attributes are missing the prefix `pi-*`

**Comment by bubblebees** [comment]
@rahilvirani thanks - I'm starting from scratch with reformatting the svgs. I think I lost something in multiple rounds of formats

**Comment by bubblebees** [comment]
@rahilvirani I'm going to resubmit the svgs with changes. would you like me to drop ApeCoin since it's been approved in another MR (https://github.com/activemerchant/payment_icons/pull/594)

**Review by rahilvirani — APPROVED** [review]
👍 I'm aiming to cut a new release version by 16th Sept

**Pull request merged**
