### PR TITLE
synchrony icon

### PR DESCRIPTION
**Pull request by rahulk7-fj**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by rahulk7-fj** [comment]
Hi @larouxn Could you please review and let us know it anything need to be fixed

**Comment by larouxn** [comment]
👋 Hello @rahulk7-fj, looks like the new icon's shape needs to be adjusted quite a bit. Maybe we can use [this template](https://github.com/activemerchant/payment_icons/blob/8cc69fcbdf8c73e0ccef9010982587227825bf4f/CONTRIBUTING.md#template)?
Screenshot 2021-12-04 112900

**Comment by larouxn** [comment]
👋 Looks like there there's still a background fill the goes outside of the border.

```svg
<rect width="100%" height="100%" fill="#fff"/>
```

Screen Shot 2021-12-07 at 14 54 17

**Comment by rahulk7-fj** [comment]
@larouxn Yeah made changes. Could you please verify !

**Comment by larouxn** [comment]
Thanks for the fixes. Icon is looking a lot better.
Screen Shot 2021-12-07 at 15 26 57

Looks like we're missing a `<title>` though. Need to add that. ([logs](https://github.com/activemerchant/payment_icons/runs/4440360018?check_suite_focus=true))
```
{:message=>"The 'synchrony' SVG file should have a single <title> tag"}
```

**Comment by rahulk7-fj** [comment]
Thank you @larouxn . For helping us on this.

**Comment by rahulk7-fj** [comment]
FYI..
https://www.synchronybusiness.com/platforms-integrations.html
https://apps.shopify.com/synchrony-digital-buy

**Review by larouxn — APPROVED** [review]
LGTM 🎩 
Screen Shot 2021-12-07 at 18 03 25

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Aiming to release a new version of this gem soon. Hoping to have this new icon live by end of next week at the latest.

**Comment by rahulk7-fj** [comment]
Hi @larouxn, We were unable to see our icon in the payment method list in Shopify.
image

**Comment by larouxn** [comment]
👋 Hello @rahulk7-fj, that is expected. The icon is not live yet. Should be live this week. I will comment here when it is.

**Comment by larouxn** [comment]
👋 @rahulk7-fj, your icon should be available everywhere now. Have a great day! ☀️

**Pull request merged**
