### PR TITLE
Add Inbank logo to Shopify

### PR DESCRIPTION
**Pull request by martin-lougas**
## Why are you adding this icons?
I'm adding this icon because we provide a [Shopify Payment App](https://apps.shopify.com/inbank-pay-later) and need to show the logo on the checkout page.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon with the black background
image

What's the expected date of this change to deploy on Shopify?
As soon as possible, as the payment method application is already approved and the only issue for us going live is a missing logo in checkout page.

### CODE REVIEW

**Comment by lunataoo** [comment]
Hi @martin-lougas, the [Shopify Payment App](https://apps.shopify.com/inbank-1) link you provided is not found. 
The icon itself looks good.
SVG Editor:Viewer Online 2022-11-10 13-44-31

Question - should the group be `bank_transfers` or `other`?

**Comment by martin-lougas** [comment]
@lunataoo  Hello!
Changed the link to the new one, we asked it to be changed, but I've forgotten to update it.
As for the group, it should be other, because we are not an actual bank, but a consumer financing company.

**Review by lunataoo — CHANGES_REQUESTED** [review]
There are errors in your SVG that's not passing our test, please take a look at them and update accordingly. Thank you!

**Comment by martin-lougas** [comment]
Hi @lunataoo, I fixed the error 
> The 'inbank' SVG file should have a <title> tag as first child of the root <svg> tag
Could you run the tests again, please?

**Comment by martin-lougas** [comment]
Hi @lunataoo, I saw that somehow the title was capitalized. Fixed it now.

**Comment by martin-lougas** [comment]
Hi @lunataoo sorry for making you run the tests so many times. I've gone ahead and looked at other SVG files and saw that Inbank image had clipPath items in it which weren't doing anything. I've removed them all and the logo is looking the same.

**Comment by martin-lougas** [comment]
@lunataoo Hi!
What are the next steps with this? At what point will the logo be visible in Shopify? When is the next release planned?

**Comment by Jacquesattaque** [comment]
@martin-lougas We're hoping to have a release in the next week or two. Thanks for your patience.

**Pull request merged**
