### PR TITLE
Atobaraidotcom add payment_icon

### PR DESCRIPTION
**Pull request by trustring**
Add SVGOptimized
Add atobaraidotcom config

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hello @trustring, can you fill out the PR description checklist and rebase your PR to fix the merge conflicts? I recommend placing the `payment_icons.yml` entry somewhere towards the middle of the file.

**Review by larouxn — APPROVED** [review]
Looks good to me. 🎩 
Screen Shot 2022-02-14 at 11 41 42

Thanks for fixing the merge conflicts!

**Comment by trustring** [comment]
Hello @larouxn, thanks for your reply.
I just filled out the PR description checklist and also rebased our PR using
```
$ git merge-base atobaraidotcom master (return hash)
$ git rebase -i ${HASH}
```
As your recommendation, I also placed our entry to the middle of the file. Please take a look again when you have time. 

Thanks for your cooperation!

**Comment by trustring** [comment]
> Looks good to me. 🎩 Screen Shot 2022-02-14 at 11 41 42
> 
> Thanks for fixing the merge conflicts!

Thanks for your quick response

**Comment by larouxn** [comment]
👋 Thanks @trustring! Will try to get this merged in soon and include it in the [v1.7.11 release](https://github.com/activemerchant/payment_icons/pull/553).

**Comment by trustring** [comment]
> 👋 Thanks @trustring! Will try to get this merged in soon and included it in the [v1.7.11 release](https://github.com/activemerchant/payment_icons/pull/553).

@larouxn Thanks for letting me know and we will wait to hear from you.

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Hello hello, your icon(s) should be live everywhere now. Please let us know if otherwise. 🙇‍♂️

**Pull request merged**
