### PR TITLE
* add new przelewy24 icons

### PR DESCRIPTION
**Pull request by santoso87**
## Why are you adding this icons?
I'm adding/updating this icon(s) because "Przelewy24" the existing one is not for Przelewy24 bank_transfers and we want to use it for our payment app that provides "Przelewy24" payment initiation service as a payment method.

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
@adeniyiao So looks like we have an icon for `przelew24`, but it's very wrong, and we have an icon for `przelewytwofourpaynlversion` that's correct. This seems to be another version. @santoso87 Is there a reason you would want to use the icon you submitted vs. the `przelewytwofourpaynlversion` version? I feel like we should just have one icon called `przelewy24` (spelled correctly, unlike our current icon) that we use everywhere.

Here's the icon, for reference:
Screenshot 2023-03-09 at 3 22 22 PM

**Comment by Jacquesattaque** [comment]
@santoso87 Do you still need this icon? If not, I will close the issue.

**Comment by santoso87** [comment]
hi @Jacquesattaque  i still need this logo, this logo is for different with Yours given, that's the way i need it

**Comment by Jacquesattaque** [comment]
Is there a reason you couldn't submit this PR to replace our existing `przelew24` icon?

**Comment by kfa-spyro** [comment]
@Jacquesattaque 
Icon provided by @santoso87 is correct branding logo for Przelewy24 here in Poland. The `przelewytwofourpaynlversion` version is the "short version" not commonly used in the stores. The `przelew24` version is way not correct one (never saw it in Polish shops). [Here](https://www.przelewy24.pl/en/download?#materialy-graficzne) you can see proper logos used by this payment provider.

**Comment by kfa-spyro** [comment]
> Is there a reason you couldn't submit this PR to replace our existing `przelew24` icon?

I think `przelew24` icon was added by Mollie developers and is currently used by their integration. Cleanup of this mess would be beneficial for everyone.

**Comment by kfa-spyro** [comment]
@santoso87 Please remove clip-paths as they break icon when icon is used few times on same page.

Proper code
`<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-przelewy24"><path d="M35 .001H3c-1.7 0-3 1.3-3 3v18C0 22.7 1.4 24 3 24h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3v.001z" fill="#000" fill-opacity=".07"/><path d="M35 1c1.1 0 2.001.9 2.001 2v18a2.006 2.006 0 01-2 2H3A2.007 2.007 0 011 21V3c0-1.1.9-2 2.001-2h32z" fill="#fff"/><path d="M3 15.576l.81-4.581h2.087c.514 0 .847.1.999.299.152.199.18.572.083 1.117-.093.524-.253.88-.482 1.071-.228.19-.61.285-1.147.285l-.201.004H3.833l-.319 1.805H3zm.91-2.242h1.22c.51 0 .845-.052 1.007-.157.163-.105.277-.347.344-.725.078-.443.08-.723.003-.84-.076-.118-.295-.177-.658-.177l-.197-.004H4.247l-.336 1.904zm3.528-.966h.467l-.112.369.009.01c.238-.302.57-.453.995-.453.588 0 .828.304.72.913l-.042.221h-.461l.024-.08c.022-.085.035-.142.04-.171.058-.33-.09-.494-.447-.494-.52 0-.839.324-.953.97l-.34 1.923h-.467l.567-3.208zm2.488 0h2.3l-.08.456-2.321 2.363h1.903l-.069.39H9.2l.078-.447 2.33-2.373h-1.75l.069-.39zm4.6 2.239h.477l-.017.117c-.06.333-.201.566-.426.7-.225.133-.59.2-1.096.2-.588 0-.954-.109-1.1-.325-.145-.215-.157-.669-.035-1.36.114-.64.282-1.07.505-1.29.224-.218.605-.328 1.144-.328.588 0 .956.095 1.105.285.149.19.17.59.061 1.202l-.044.251h-2.298c-.09.506-.092.828-.009.967.084.139.324.208.72.208.376 0 .626-.033.75-.099s.206-.208.245-.428l.018-.1zm.161-.913l.023-.152c.061-.346.044-.572-.05-.676-.096-.104-.331-.156-.708-.156-.378 0-.634.061-.768.183s-.238.389-.31.8h1.813zm1.973-2.699l-.81 4.582h-.467l.81-4.582h.467zm2.218 3.612h.477l-.017.117c-.06.333-.201.566-.426.7-.225.133-.59.2-1.096.2-.588 0-.954-.109-1.1-.325-.145-.215-.157-.669-.035-1.36.113-.64.282-1.07.505-1.29.224-.218.605-.328 1.144-.328.588 0 .956.095 1.105.285.149.19.17.59.061 1.202l-.044.251h-2.298c-.09.506-.092.828-.009.967.084.139.324.208.72.208.376 0 .626-.033.75-.099s.206-.208.245-.428l.018-.1zm.16-.913l.024-.152c.062-.346.045-.572-.05-.676-.096-.104-.331-.156-.708-.156-.378 0-.634.061-.768.183s-.238.389-.31.8h1.813zm5.352-1.326l-1.462 3.208h-.695l-.112-1.782-.034-.543-.012-.272-.016-.272h-.01l-.111.272-.112.272-.226.543-.746 1.782h-.708l-.297-3.208h.49l.138 1.775.041.557.018.279.017.279h.014l.113-.279.116-.279.231-.553.752-1.78h.681l.12 1.783.035.554.015.275.014.278h.01l.12-.278.115-.279.24-.557.76-1.776h.502zm2.354 0l-.613 1.43-.306.711-.147.36-.15.355h-.013l-.06-.356-.057-.359-.122-.712-.238-1.43h-.497l.64 3.487-.073.159c-.197.422-.42.627-.67.614a1.015 1.015 0 01-.159-.024l-.069.39c.09.015.162.023.22.023.288 0 .524-.09.71-.268.187-.18.386-.508.597-.987l1.505-3.393h-.498z" fill="#CF4545"/><path d="M30.236 15.169l-.076.432h-3.205l.15-.855c.085-.48.23-.793.44-.942.208-.148.662-.263 1.36-.343.56-.062.905-.146 1.038-.253.133-.106.238-.382.317-.828.068-.39.049-.644-.058-.76-.107-.117-.374-.176-.802-.176-.535 0-.88.047-1.038.142-.156.094-.266.321-.33.68l-.052.34h-.493l.045-.236c.096-.544.271-.906.528-1.087.257-.18.723-.271 1.4-.271.6 0 .985.097 1.158.293.172.195.208.575.109 1.141-.095.544-.255.907-.48 1.09-.224.183-.664.307-1.318.371-.576.058-.927.138-1.053.24-.127.102-.232.391-.316.868l-.027.153h2.703zm4.218-4.11l-.537 3.061h.665l-.076.433h-.665l-.184 1.048h-.502l.184-1.048h-2.49l.105-.602 2.724-2.893h.776zm-1.039 3.061l.48-2.732h-.01l-2.547 2.732h2.077zM13.586 9.607a16.448 16.448 0 013.119-1.414l-.2-1.131a22.046 22.046 0 00-4.011 1.714l1.092.831zm12.371-.617l3.853-2.112c-1.596-.504-3.625-.864-6.174-.878h-.025l-.881 1.772c1.133.23 2.223.642 3.227 1.218zm-14.445.363c-1.693 1.058-2.58 1.957-2.58 1.957h2.144a23.47 23.47 0 011.54-1.104l-1.104-.853zm10.855-3.327c-1.85.087-3.524.38-5.012.785l.148 1.148c1.616-.423 3.071-.478 4.34-.329l.524-1.604zm9.495 1.675L26.868 9.58c.462.337.705.579.705.579H35S34.16 8.85 31.862 7.7z" fill="#AEB2BA"/></svg>`

**Comment by kfalkiewicz** [comment]
@Jacquesattaque @santoso87 This can be closed ad is doing exactly same thing as https://github.com/activemerchant/payment_icons/pull/886 (with is approved and ready for merge)

**Pull request closed without merging**
