### PR TITLE
octopus icon

### PR DESCRIPTION
**Pull request by zeo-rap**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
Hi,

Can you please convert the `base64` format into real SVG elements?
We are avoiding `base64` format due to the big filesize compared to SVG elements.

Issue for more information: https://github.com/activemerchant/payment_icons/issues/407

**Comment by zeo-rap** [comment]
Hi,

Currently we dont have a pure svg version of this icon. I can see other icon files also have base64 contained svg. And our file size is only 106 KB.

**Comment by larouxn** [comment]
> Currently we dont have a pure svg version of this icon. I can see other icon files also have base64 contained svg. And our file size is only 106 KB.

Sorry @zeo-rap but going forward we're really trying to limit non-SVG additions. True that `106 KB` is not a lot but if 10 `106 KB` icons are added the total size will increase quite a bit. 🙇‍♂️

**Comment by rahilvirani** [comment]
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

**Pull request closed without merging**
