### PR TITLE
Add Sika icons

### PR DESCRIPTION
**Pull request by emma-sika**
## Why are you adding these icons?
I'm adding these icons because Sika is a Shopify Payments Partner for HSA/FSA spending.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

We don't have public brand guidelines, but you can see our HSA/FSA card branding live on merchant websites:
sikabranding

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
Screen Shot 2023-04-12 at 7 51 38 AM
Screen Shot 2023-04-12 at 7 49 46 AM

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name) 
Adeniyi Adeyemi

What's the expected date of this change to deploy on Shopify?
When our app is approved (currently in review)

### CODE REVIEW

**Comment by emma-sika** [comment]
> Icons look good; we have a preference for these to appear on a white background. Do you have inverted icons you can submit?

Hi @Jacquesattaque, thanks for reviewing. I've updated the color schema of the icons- let me know what you think.

**Comment by Jacquesattaque** [comment]
Icons look good — just clear the failing checks and I'll approve.

**Comment by emma-sika** [comment]
> Icons look good — just clear the failing checks and I'll approve.

Done- mind triggering the checks again?

**Comment by emma-sika** [comment]
I'm a little confused about the failures here- it seems the checks want the FSA title to be 'Sikafsa' and the HSA title to be 'Sika HSA'. I've made these updates but I'm wondering if there is an issue with the check more generally.

**Comment by Jacquesattaque** [comment]
@adeniyiao If you have a chance could you take a look and diagnose the failure here for us?

**Comment by adeniyiao** [comment]
Hi @emma-sika , the checks have passed now. Thanks.

@Jacquesattaque do you mind review again. Thank you

**Comment by adeniyiao** [comment]
@emma-sika And also the SVG filename should have no underscore.

**Comment by emma-sika** [comment]
Ah sorry ya'll, forgot that requirement while trying to fix these failures. This most recent update is passing locally- although I'm still not sure why 'Sika HSA' and 'Sikafsa' is the specific combo that works. 

Thanks for your help on this!

**Comment by emma-sika** [comment]
@Jacquesattaque @adeniyiao bumping this when you get a chance- I corrected the underscores.

**Review by Jacquesattaque — APPROVED** [review]

**Comment by adeniyiao** [comment]
Hi @emma-sika , the next release date is May 3rd, and you will be able to add Sika payment icon afterwards

**Comment by emma-sika** [comment]
Thanks @adeniyiao! We'll mark our calendar.

**Comment by adeniyiao** [comment]
Hi @emma-sika , 

Apologies for the back and forth. Could you please make a quick correction to the title of the sikafsa SVG. For some reason the check failed again. Thanks

image

**Comment by emma-sika** [comment]
@adeniyiao done!

**Pull request merged**
