### PR TITLE
Adding MoMoPay & ZaloPay icons for Vietnam region

### PR DESCRIPTION
**Pull request by prashant-chai**
## Why are you adding this icons?
I'm adding/updating this icon(s) because
- we have an approved Payments App and we want to support these payment methods in the Vietnam region as these are widely popular also we have active merchants who are waiting for these methods to be added in Shopify. 
- as advised by Shopify Partner Support Specialist

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: 
- [MoMoPay guidelines](https://developers.momo.vn/v3/docs/payment/branding/brand-usage-agreement)
- [ZaloPay guidelines](https://static.zalopay.com.vn/stc/quydinh/ver180612/download/ZaloPay_Guideline.pdf)

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon with the black background

momo
zalo

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
- We were told to add the methods and icons here by a Partner Support Specialist named "Adam W"

What's the expected date of this change to deploy on Shopify?
- As soon as possible after the review is completed as we are ready to support the method.

### CODE REVIEW

**Review by rahilvirani — DISMISSED** [review]
@prashant-chai both the height and width are incorrect. 

image

**Comment by prashant-chai** [comment]
@rahilvirani We've updated the icons size, can you please check again

**Comment by prashant-chai** [comment]
@rahilvirani Can you please take a look.

**Comment by Jacquesattaque** [comment]
The sizes look good here but the icons are missing a 1px border, #000 at 7% transparency (0.07).

**Comment by Jacquesattaque** [comment]
@prashant-chai Please let us know if you still require these icons. If we haven't heard back by the end of next week we'll close this issue.

**Comment by prashant-chai** [comment]
Hi @Jacquesattaque , we still require these icons and we'll add the 1px border as mentioned

**Comment by prashant-chai** [comment]
@Jacquesattaque We have made the changes as requested

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Icons look good! Please resolve conflicts and we'll need to run the automated checks once more before we approve. Thanks!

**Comment by prashant-chai** [comment]
@Jacquesattaque Conflicts resolved

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
