### PR TITLE
Add rcs icon

### PR DESCRIPTION
**Pull request by onahkenneth**
** Checklist **
- [*] All icons have a corresponding entry in `db/payment_icons.yml`
- [*] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [*] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [*] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

Brand icon guidelines not required.

### CODE REVIEW

**Comment by onahkenneth** [comment]
@tauthomas01 
Rebased and the build is passing. Can you merge?

**Comment by tauthomas01** [comment]
@onahkenneth I merged your other branch so this caused conflicts in 1 file. Could you fix it?

**Comment by onahkenneth** [comment]
> @onahkenneth I merged your other branch so this caused conflicts in 1 file. Could you fix it?

I have fixed the conflicts.

**Comment by tauthomas01** [comment]
Hi @onahkenneth, could you rebase your branch off master?
Thank you

**Comment by tauthomas01** [comment]
Hi @onahkenneth ,

I'm closing this as there are no activities.
Feel free to open a new pull request again if you would like to contribute.

Regards

**Pull request closed without merging**
