### PR TITLE
Cashew icon added

### PR DESCRIPTION
**Pull request by rixwansyed**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_963_69)"><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z" fill="#000"/><path d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32z" fill="#E4DAFC"/><path d="M15.61 14.766c-.445 0-.817-.093-1.118-.277a1.511 1.511 0 01-.667-.803l.66-.227a.777.777 0 00.365.433c.194.121.452.178.76.178s.545-.064.731-.206a.536.536 0 00.23-.462v-.007a.45.45 0 00-.044-.198c-.021-.043-.078-.086-.15-.128a1.717 1.717 0 00-.373-.157 6.018 6.018 0 00-.595-.156 5.888 5.888 0 01-.473-.113 4.11 4.11 0 01-.387-.128 1.174 1.174 0 01-.366-.213l-.014-.014a.96.96 0 01-.222-.313.948.948 0 01-.086-.44c0-.398.164-.731.48-.959.287-.206.66-.312 1.104-.312.466 0 .86.107 1.168.327.316.22.524.54.631.944l-.68.163a.889.889 0 00-.352-.546c-.186-.128-.437-.192-.76-.192-.294 0-.53.057-.688.177-.136.1-.194.228-.194.412 0 .057.008.1.03.142a.355.355 0 00.056.085.63.63 0 00.151.086l.014.007c.1.042.201.078.301.1.1.027.251.063.438.106.28.064.494.113.66.17.171.057.336.128.494.213.193.107.337.242.43.405v.007c.086.163.129.348.122.54 0 .411-.172.766-.502 1.008-.301.234-.688.348-1.154.348zm-7.162-1.214l.51.504-.058.057a2.25 2.25 0 01-1.169.617 2.356 2.356 0 01-1.319-.127A2.259 2.259 0 015 12.515a2.26 2.26 0 011.412-2.088c.416-.17.875-.213 1.32-.127.444.085.845.298 1.168.617l.057.057-.509.504-.057-.056a1.577 1.577 0 00-2.409.227 1.538 1.538 0 00-.265.859c0 .305.093.604.265.859.172.256.416.454.703.568.286.12.602.15.903.085.301-.064.58-.206.803-.426l.057-.042zm24.703-3.217v2.769c0 .192-.035.383-.093.56a1.61 1.61 0 01-.337.562c-.043.042-.086.092-.129.127a1.66 1.66 0 01-1.133.426c-.193 0-.387-.035-.566-.092a1.629 1.629 0 01-.695-.461c-.029-.036-.057-.064-.079-.1l-.079.1c-.043.042-.086.092-.129.127a1.66 1.66 0 01-1.133.426 1.89 1.89 0 01-.566-.092 1.63 1.63 0 01-.695-.461 1.62 1.62 0 01-.43-1.122v-2.805h.702v2.805c0 .17.043.34.13.49.085.149.214.27.358.362.3.17.688.17.99 0 .15-.085.271-.213.365-.362a.986.986 0 00.129-.49v-2.805h.71v2.805c0 .17.042.34.128.49.087.149.215.27.359.362.301.17.688.17.99 0a.983.983 0 00.487-.852v-2.77h.716zm-11.785 1.597v2.805h-.702v-2.805c0-.17-.043-.34-.13-.49a.97.97 0 00-.365-.354 1.021 1.021 0 00-.99 0c-.15.085-.271.213-.365.355a.934.934 0 00-.129.39v2.904h-.717V9h.717v1.57a1.91 1.91 0 01.416-.22 1.7 1.7 0 012.158 1.022c.072.177.107.369.107.56zm4.323 1.03l-.015.036a.897.897 0 01-.064.156 1.523 1.523 0 01-.803.774 1.478 1.478 0 01-.516.12 1.565 1.565 0 01-.76-.142 1.536 1.536 0 01-.495-.355c-.036-.042-.079-.085-.114-.135l3.49-1.476-.02-.071a2.142 2.142 0 00-.222-.518 4.915 4.915 0 00-.159-.242 2.33 2.33 0 00-.831-.668 2.366 2.366 0 00-.71-.206 2.555 2.555 0 00-.617.008 2.349 2.349 0 00-1.053.447c-.165.128-.309.27-.438.433-.093.12-.172.256-.236.384a2.297 2.297 0 00-.2 1.314c.028.19.085.375.157.546a2.3 2.3 0 00.287.497 2.317 2.317 0 00.831.667 2.366 2.366 0 00.71.206c.093.014.186.014.28.014.114 0 .229-.007.336-.028.194-.028.38-.078.552-.156a2.367 2.367 0 00.94-.725 2.34 2.34 0 00.236-.383 2.312 2.312 0 00.208-.703l.014-.142-.788.348zm-3.047-.199l-.021-.17a1.522 1.522 0 01.143-.753 1.527 1.527 0 01.803-.774c.165-.07.344-.113.516-.12.036 0 .072-.008.1-.008a1.52 1.52 0 01.66.15c.186.085.351.206.494.355.036.042.072.092.108.142l-2.803 1.178z" fill="#000"/><path d="M13.459 12.522a2.278 2.278 0 00-2.28-2.272 2.282 2.282 0 00-2.28 2.272 2.278 2.278 0 003.836 1.654v.561h.717V12.7c.007-.056.007-.113.007-.177zm-2.273 1.555c-.48 0-.91-.22-1.197-.568-.021-.021-.036-.05-.057-.071a17.708 17.708 0 01-.043-.064c-.007-.007-.007-.014-.015-.014a1.497 1.497 0 01-.258-.852 1.557 1.557 0 013.112-.064v.085c0 .05 0 .1-.008.15 0 .013 0 .02-.007.035-.007.035-.007.078-.021.113 0 .014-.008.036-.008.05-.007.021-.007.035-.014.057a.405.405 0 01-.028.085c-.008.028-.022.057-.036.092-.015.029-.022.057-.036.085v.008l-.043.085a.15.15 0 01-.029.042c-.007.014-.021.029-.028.043 0 .007-.008.014-.015.021a1.507 1.507 0 01-1.269.682z" fill="#000"/></g><defs><clipPath id="clip0_963_69"><path fill="#fff" d="M0 0h38v24H0z"/></clipPath></defs></svg>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Comment by rixwansyed** [comment]
it again failed any urgent help why its doing. I have fresh forked and cloned repo and created new branch and pull request

**Comment by adeniyiao** [comment]
Hi @rixwansyed, it failed due to a different issue as highlighted in the screenshot 

image

**Comment by rixwansyed** [comment]
My Pull request has passed all the checks, What is the next step to our icon published in Shopify?

**Comment by rixwansyed** [comment]
> Hi @rixwansyed, it failed due to a different issue as highlighted in the screenshot
> 
> image

We have resolved all issues, can you guide how the changes will be merged?

**Comment by rixwansyed** [comment]
Any update or help is appreciated @adeniyiao

**Comment by rixwansyed** [comment]
hi @adeniyiao still waiting for the update, any idea when this will be merged as all the checks has been passed.

**Comment by adeniyiao** [comment]
Hi @rixwansyed , we are scheduling another delta release this Wednesday, we will include this PR

**Comment by adeniyiao** [comment]
Hi @rixwansyed , I can't add this yet as PR needs to be reviewed and approved.

cc @hellicarusprime

**Comment by rixwansyed** [comment]
> Hi @rixwansyed , I can't add this yet as PR needs to be reviewed and approved.
> 
> cc @hellicarusprime

Is there any estimated time, as my management is asking for estimated time.

**Comment by hellicarusprime** [comment]
> > Hi @rixwansyed , I can't add this yet as PR needs to be reviewed and approved.
> > cc @hellicarusprime
> 
> Is there any estimated time, as my management is asking for estimated time.

Hi @rixwansyed I've just approved this.

cc @adeniyiao

**Comment by rixwansyed** [comment]
any update when the next PR is happening @adeniyiao

**Comment by adeniyiao** [comment]
Hi @rixwansyed , the next release is schedule for Feb 7

**Comment by rixwansyed** [comment]
I can not see our icon in the Payment methods in our payment extension. @adeniyiao can you guide what is the next step.

Screenshot 2024-02-08 at 9 54 58 AM
Screenshot 2024-02-08 at 9 54 44 AM

**Comment by adeniyiao** [comment]
Hi @rixwansyed , apologies for the delay,  the release process is not fully completed, there's a pending deployment that should be done by EOD today and the icon will show up after.

**Comment by rixwansyed** [comment]
thank @adeniyiao for the update, looking forward

**Comment by adeniyiao** [comment]
Hi @rixwansyed , it's now deployed. Please check and confirm. Regards

**Comment by rixwansyed** [comment]
Thanks @adeniyiao for the update, we are able to see the icon now.

**Pull request merged**
