### PR TITLE
Add SEPA Direct Debit

### PR DESCRIPTION
**Pull request by sakifutamura**
## Why are you adding this icons?
I'm adding this icon because this gem currently has an icon for SEPA Bank Transfer, but not for SEPA Direct Debit ([context](https://github.com/activemerchant/payment_icons/pull/1108#issuecomment-1847347994))

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [x] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: [<Link>](https://www.europeanpaymentscouncil.eu/document-library/other/sepa-logo-visual-identity-guidelines)

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.
image

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" role="img" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-sepadirectdebit"><title id="pi-sepadirectdebit">SEPA Direct Debit</title><rect x="1" y="1" width="36" height="22" rx="2" fill="#fff"/><rect x=".5" y=".5" width="37" height="23" rx="2.5" stroke="#000" stroke-opacity=".07"/><path d="M28.37 15l-.305-1.037h-2.13L25.647 15h-1.65l1.78-6h2.406l1.803 6H28.37zm-1.368-4.806l-.726 2.6h1.473l-.747-2.6zm-3.86 3.217c-.07.012-.367.023-.89.031l-.265.01h-.95V15h-1.595V9h2.97c.409 0 .72.034.932.102.49.155.817.472.986.952.087.25.13.63.13 1.136 0 .61-.048 1.046-.143 1.313-.19.526-.583.83-1.176.908zm-.377-2.774c-.057-.172-.194-.277-.412-.314a2.902 2.902 0 00-.309-.01h-1.007v1.746h.993c.316-.011.508-.037.577-.074.094-.053.157-.158.189-.316.02-.105.03-.26.03-.468 0-.253-.02-.441-.06-.564zM11.747 14.93c-.242.046-.611.069-1.11.069-.83 0-1.41-.05-1.737-.15-.401-.124-.665-.374-.792-.75-.072-.21-.108-.559-.108-1.046h1.484v.124c0 .261.074.429.222.503a.86.86 0 00.37.082h.545c.279 0 .457-.016.533-.045a.434.434 0 00.269-.262c.023-.075.034-.17.034-.29 0-.264-.095-.424-.286-.482-.07-.023-.402-.054-.991-.095a11.956 11.956 0 01-.988-.1c-.486-.092-.81-.28-.971-.568-.142-.244-.214-.613-.214-1.107 0-.377.04-.679.116-.905a.984.984 0 01.371-.517c.25-.181.57-.287.96-.318.36-.03.72-.045 1.08-.044.622 0 1.066.036 1.33.108.647.175.969.667.969 1.476 0 .066-.005.166-.014.298h-1.484c0-.246-.029-.412-.085-.496-.089-.125-.332-.187-.73-.187-.389 0-.646.036-.77.107-.126.072-.189.229-.189.47 0 .22.056.363.167.432.08.048.185.077.317.086l.3.021c.64.043 1.04.074 1.2.091.507.052.874.188 1.103.41.18.172.286.398.32.677.02.166.03.355.03.564 0 .483-.046.837-.137 1.062-.166.41-.536.67-1.114.78v.002z" fill="#0054A5"/><path d="M17.14 9.845c-.777 0-1.454.428-1.82 1.065h3.297l-.396.858h-3.174c-.017.178-.013.357.012.533h2.917l-.396.86h-2.197a2.093 2.093 0 001.758.965c.629 0 1.193-.281 1.579-.725v1.053a2.994 2.994 0 01-1.681.512 2.989 2.989 0 01-2.752-1.804h-1.05l.396-.86h.434a2.902 2.902 0 01-.004-.533H13.2l.397-.86h.67a2.987 2.987 0 012.773-1.856 2.995 2.995 0 012.077.831l-.345.747a2.09 2.09 0 00-1.63-.788l-.003.002z" fill="#FEC10E"/></svg>



<br>
<!-- TODO: insert your icon here -->
<svg width="38" height="24" role="img" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-sepadirectdebit"><title id="pi-sepadirectdebit">SEPA Direct Debit</title><rect x="1" y="1" width="36" height="22" rx="2" fill="#fff"/><rect x=".5" y=".5" width="37" height="23" rx="2.5" stroke="#000" stroke-opacity=".07"/><path d="M28.37 15l-.305-1.037h-2.13L25.647 15h-1.65l1.78-6h2.406l1.803 6H28.37zm-1.368-4.806l-.726 2.6h1.473l-.747-2.6zm-3.86 3.217c-.07.012-.367.023-.89.031l-.265.01h-.95V15h-1.595V9h2.97c.409 0 .72.034.932.102.49.155.817.472.986.952.087.25.13.63.13 1.136 0 .61-.048 1.046-.143 1.313-.19.526-.583.83-1.176.908zm-.377-2.774c-.057-.172-.194-.277-.412-.314a2.902 2.902 0 00-.309-.01h-1.007v1.746h.993c.316-.011.508-.037.577-.074.094-.053.157-.158.189-.316.02-.105.03-.26.03-.468 0-.253-.02-.441-.06-.564zM11.747 14.93c-.242.046-.611.069-1.11.069-.83 0-1.41-.05-1.737-.15-.401-.124-.665-.374-.792-.75-.072-.21-.108-.559-.108-1.046h1.484v.124c0 .261.074.429.222.503a.86.86 0 00.37.082h.545c.279 0 .457-.016.533-.045a.434.434 0 00.269-.262c.023-.075.034-.17.034-.29 0-.264-.095-.424-.286-.482-.07-.023-.402-.054-.991-.095a11.956 11.956 0 01-.988-.1c-.486-.092-.81-.28-.971-.568-.142-.244-.214-.613-.214-1.107 0-.377.04-.679.116-.905a.984.984 0 01.371-.517c.25-.181.57-.287.96-.318.36-.03.72-.045 1.08-.044.622 0 1.066.036 1.33.108.647.175.969.667.969 1.476 0 .066-.005.166-.014.298h-1.484c0-.246-.029-.412-.085-.496-.089-.125-.332-.187-.73-.187-.389 0-.646.036-.77.107-.126.072-.189.229-.189.47 0 .22.056.363.167.432.08.048.185.077.317.086l.3.021c.64.043 1.04.074 1.2.091.507.052.874.188 1.103.41.18.172.286.398.32.677.02.166.03.355.03.564 0 .483-.046.837-.137 1.062-.166.41-.536.67-1.114.78v.002z" fill="#0054A5"/><path d="M17.14 9.845c-.777 0-1.454.428-1.82 1.065h3.297l-.396.858h-3.174c-.017.178-.013.357.012.533h2.917l-.396.86h-2.197a2.093 2.093 0 001.758.965c.629 0 1.193-.281 1.579-.725v1.053a2.994 2.994 0 01-1.681.512 2.989 2.989 0 01-2.752-1.804h-1.05l.396-.86h.434a2.902 2.902 0 01-.004-.533H13.2l.397-.86h.67a2.987 2.987 0 012.773-1.856 2.995 2.995 0 012.077.831l-.345.747a2.09 2.09 0 00-1.63-.788l-.003.002z" fill="#FEC10E"/></svg>


</br>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Why so many changes to the YML file? Should just be adding a single payment method, but I see changes to many rows.

**Comment by sakifutamura** [comment]
@Jacquesattaque Sorry! My text editor was automatically removing trailing whitespace on save

**Review by Jacquesattaque — APPROVED** [review]

**Review by bargenson — APPROVED** [review]

**Comment by adeniyiao** [comment]
Hi @sakifutamura,  we addressed a ruby version issue causing the test failure with this PR , therefore we need you to rebase your branch `sakifutamura:sepa-dd` with `activemerchant/master` to fix the CI failure. Thanks.

**Comment by sakifutamura** [comment]
@adeniyiao Done! thanks!

**Pull request merged**
