### PR TITLE
Add Fintecture icon

### PR DESCRIPTION
**Pull request by hugofintecture**
Hello,
We will release soon our payment app for Shopify so we would like to have our icon available for this release :)
Our website : https://www.fintecture.com

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

### CODE REVIEW

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the icon shape is a bit off. Perhaps we can rebuild it with the [template](https://github.com/activemerchant/payment_icons/blob/edc00a06ccd5bba6388bd9311974061a07135688/CONTRIBUTING.md#template)?
Screen Shot 2022-05-18 at 15 02 25

**Comment by hugofintecture** [comment]
@larouxn Thanks, should be way better :)

**Comment by hugofintecture** [comment]
@tauthomas01 maybe you can re-review this MR? Thanks in advance :)

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-01 at 10 30 05

**Comment by larouxn** [comment]
👋 Hello, your icon(s) have been released in the latest version of this library. The rollout process will begin within a few days. We wanted to have it/them live this week but looking more likely to be live early to mid next week. Will report back here when live. Thank you for your patience. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, actually your icon(s) should be live everywhere now. 🚀

**Comment by hugofintecture** [comment]
Thanks! Can confirm it :)

**Pull request merged**
