### PR TITLE
Optimized Tandym payment icon

### PR DESCRIPTION
**Pull request by NicholasAnthony**
** Checklist **
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by NicholasAnthony** [comment]
Went through the contributing doc again and everything looks like it should be g2g this time 🤞🏽

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the icon border is on the outside, while it should be in the inside, if I recall correctly. Maybe the [template](https://github.com/activemerchant/payment_icons/blob/c344b9cd6c9a103f7aa278f0dcb4772ee67f948a/CONTRIBUTING.md#template) can help.

Screen Shot 2022-06-23 at 18 27 18

**Review by larouxn — DISMISSED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-23 at 18 28 24

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the icon border is on the outside, while it should be in the inside, if I recall correctly. Maybe the [template](https://github.com/activemerchant/payment_icons/blob/c344b9cd6c9a103f7aa278f0dcb4772ee67f948a/CONTRIBUTING.md#template) can help.

Screen Shot 2022-06-23 at 18 27 18

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
image

**Comment by larouxn** [comment]
👋 @tauthomas01, have a look when you have a moment. 🙇‍♂️

**Comment by NicholasAnthony** [comment]
@larouxn @tauthomas01 does this require anything else? We've been trying to keep an eye on this / close it out.

**Review by tauthomas01 — APPROVED** [review]
Sorry about this. I thought I already approved.

**Comment by larouxn** [comment]
👋 We batch our icon updates, so you can expect this icon to be live within a few weeks/within the month. We will update here again, letting you know, when the updated/added icon is available. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, we're working on the [v1.7.16](https://github.com/activemerchant/payment_icons/pull/702) release now. It will likely go live next week.

Apologies for the wait. Will report back here when it's live. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

**Pull request merged**
