### PR TITLE
Add clip icon

### PR DESCRIPTION
**Pull request by Maxi-TD**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" viewBox="0 0 38 24" aria-labelledby="pi-clip" role="img" fill="#fff" xmlns="http://www.w3.org/2000/svg"><title id="pi-clip">Clip</title><rect x=".5" y=".5" width="37" height="23" rx="2.5" stroke="#000" stroke-opacity=".07"/><path fill-rule="evenodd" clip-rule="evenodd" d="M30.4 4.72C30.39 2.664 28.698 1 26.612 1c-.518 0-1.026.097-1.461.289l-13.8 5.783C9.382 7.892 8 9.816 8 12.052v7.314c0 2.064 1.695 3.737 3.788 3.737.53 0 1.035-.108 1.494-.303l13.742-5.757c1.98-.815 3.376-2.745 3.376-4.991V4.72z" fill="#FC4C02"/><path fill-rule="evenodd" clip-rule="evenodd" d="M17.703 14.988c-.16 0-.29-.143-.29-.318V7.943c0-.176.13-.318.29-.318.161 0 .292.142.292.318v6.727c0 .175-.13.318-.292.318zM20.236 14.688v-5.26c0-.178-.13-.322-.292-.322-.16 0-.29.144-.29.322v5.26c0 .178.13.322.29.322.161 0 .292-.144.292-.322zM20.236 7.92v-.016c0-.154-.13-.28-.292-.28-.16 0-.29.126-.29.28v.016c0 .155.13.28.29.28a.286.286 0 00.292-.28zM15.68 14.279a.317.317 0 000-.456.333.333 0 00-.466 0c-.95.93-2.495.93-3.445 0a2.353 2.353 0 010-3.373 2.447 2.447 0 011.722-.699c.651 0 1.263.248 1.723.699a.334.334 0 00.466 0 .318.318 0 000-.457 3.107 3.107 0 00-2.189-.887c-.826 0-1.603.315-2.188.887a2.989 2.989 0 000 4.286c.603.59 1.395.886 2.188.886.793 0 1.585-.295 2.189-.886zM22.548 16.302V12.13c0-1.312 1.084-2.38 2.416-2.38 1.333 0 2.417 1.068 2.417 2.38 0 1.312-1.084 2.38-2.417 2.38-.768 0-1.288-.29-1.292-.291a.33.33 0 00-.447.114.32.32 0 00.116.441c.027.016.669.38 1.623.38 1.693 0 3.07-1.357 3.07-3.024s-1.377-3.023-3.07-3.023c-1.693 0-3.07 1.356-3.07 3.023v4.173c0 .178.147.322.327.322.18 0 .327-.144.327-.322z" fill="#fff"/><path fill-rule="evenodd" clip-rule="evenodd" d="M30.343 18.438a.935.935 0 01-.942.928.935.935 0 01-.94-.928c0-.513.42-.929.94-.929s.942.416.942.929zm-.149 0a.792.792 0 10-1.582 0 .792.792 0 001.582 0zm-.397.508h-.167l-.236-.416h-.156v.416h-.143v-1.019h.35c.18 0 .326.134.326.306 0 .148-.094.24-.221.28l.247.433zm-.172-.713c0-.103-.08-.18-.195-.18h-.192v.357h.192c.114 0 .195-.075.195-.177z" fill="#FC4C02"/></svg>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
You've got a double border in the icon. Please fix and resubmit.

**Comment by Maxi-TD** [comment]
hi @Jacquesattaque, I've already corrected the border, can you help me with failed checks?

**Comment by Jacquesattaque** [comment]
cc @dannye0231 are you able to take a look?

**Comment by Maxi-TD** [comment]
Hi @dannye0231! Could you take a look at it?

**Comment by adeniyiao** [comment]
Hi @Maxi-TD , we addressed a ruby version issue in this repo, therefore we need you to rebase your branch `Maxi-TD:clip` with `activemerchant/master` to fix the CI failure. Thanks.

**Comment by Maxi-TD** [comment]
It's already solved. Thanks @adeniyiao

**Review by hellicarusprime — APPROVED** [review]

**Comment by hellicarusprime** [comment]
Hey @Maxi-TD, I just noticed that you still have the double border issue that you said you fixed. Apologies, I assumed it was done. Can you please update?

**Comment by Maxi-TD** [comment]
@hellicarusprime I'm sorry about that, I'm going to fix it.
Thanks!

**Comment by hellicarusprime** [comment]
@Maxi-TD Can you please make the necessary changes as soon as possible?

**Pull request merged**
