### PR TITLE
add truemoney pay icon

### PR DESCRIPTION
**Pull request by Felix-Liu**
** Checklist **

- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — COMMENTED** [review]
👋 Hey @Felix-Liu, any chance we can use an actual SVG? The icon looks blurry on higher resolution (HiDPI) screens.
Screenshot 2021-12-01 193648

**Comment by tauthomas01** [comment]
👋 Also we shouldn't allow `image/png;base64` image. The icon must strictly use SVG element tags (`path`, `circle`, etc.) only.

**Comment by Felix-Liu** [comment]
I have improved, please review again. @larouxn , @tauthomas01

**Review by tauthomas01 — APPROVED** [review]

**Review by larouxn — APPROVED** [review]
LGTM 🎩 
Screen Shot 2021-12-07 at 09 25 23

**Comment by larouxn** [comment]
👋 Aiming to release a new version of this gem soon. Hoping to have this new icon live by end of next week at the latest.

**Comment by Felix-Liu** [comment]
OK, thanks!

**Comment by larouxn** [comment]
👋 @Felix-Liu, your icon should be available everywhere now. Have a great day! ☀️

**Pull request merged**
