### PR TITLE
Adds RuPay icon

### PR DESCRIPTION
**Pull request by captn3m0**
RuPay is the Indian domestic card network maintained by the National Payments Corporation of India. More details are the wiki page: https://en.wikipedia.org/wiki/RuPay.

### CODE REVIEW

**Comment by andrewpaliga** [comment]
@captn3m0 the size of the icon will need to be restricted to`38 by 24 pixels`, looks good other than that.

**Comment by captn3m0** [comment]
Just to note, the icon size should be fixed now.

**Comment by millingab** [comment]
@captn3m0 I see this line in the svg file ```width="37" height="23"```. Please make sure that the size is 38 by 24 pixels

**Comment by captn3m0** [comment]
It seems the export in sketch only fixes the viewbox?

/cc @vikalp02

**Comment by captn3m0** [comment]
`<svg width="38px" height="24px" viewBox="0 0 38 24"`

38x24 this time, for sure.

**Pull request merged**
