### PR TITLE
Add ShopBack Icon

### PR DESCRIPTION
**Pull request by zarniwang**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

To be used in our Payment app.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: n/a

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon with the black background
Screenshot 2022-11-01 at 2 35 26 PM

Screenshot 2022-11-01 at 2 36 00 PM

### CODE REVIEW

**Comment by zarniwang** [comment]
Can anyone review this PR please? Thank you.

**Comment by zarniwang** [comment]
hi @Jacquesattaque thank you for the feedback. Our brand guidelines prefer a black background, and for legal reasons at this time we need to use "Powered by Hoolah" but will be able to remove this in the future.

**Comment by Jacquesattaque** [comment]
Thanks @zarniwang, just resolve the conflicts in the yml file and I'll approve this.

**Comment by zarniwang** [comment]
hi @Jacquesattaque conflicts have been resolved. ready to merge, thank you. 🙂

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
