### PR TITLE
Add aeropay as payment provider

### PR DESCRIPTION
**Pull request by ocruse7**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

BEFORE SPACING UPDATE

image

AFTER SPACING UPDATE

image

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" width="38" height="24" role="img" aria-labelledby="pi-Aeropay"><title id="pi-Aeropay">AeroPay</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path fill="#24C3D2" d="M13.693 12.474c.723-.392 9.478-5.533 9.784-5.692.086-.086.245-.123.368-.184.122-.062.269-.025.368.024.169.042.122.208.085.331-.06.086-.122.208-.245.269-.159.099-9.512 5.849-10.051 6.18-.368.245-.699.49-.723.968-.024.246.086.43.245.601.147.122.406.175.601.208.194.033.472.039.68.029.813-.04 1.237.445 1.273.499.724.849.794 1.279 1.119 1.991.042.158.516 1.052 1.091 1.079l-.005.003.183.006c.454.025.846-.392 1.128-.784 1.213-1.57 7.796-12.186 8.226-12.885.146-.245.122-.699-.306-.76-.294-.061-14.102 3.954-14.919 4.195l-1.094.353c-.086.025-.184.061-.27.086l-.254.088c-.181.064-.354.115-.52.187a9.436 9.436 0 00-1.138.423c-.098.061-.22.123-.27.209-.086.086-.087.226-.087.348 0 .27.238.486.52.598.367.147.469.213 1.127.429.732.241 1.266.411 1.711 1.041.135.19.259.334.491.368.184.026.367 0 .552-.061l.33-.147z"/></svg>

```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name).
Aeropay is a company developing a payments gateway and use our own system to facilitate bank transfers. We are both the payment gateway and provider therefore were told to upload here in order to be added to the list of providers. We have had multiple contacts with various people via Shopify Partners, but Sunjay Chopra on the Partners team has been our main contact point at Shopify.

What's the expected date of this change to deploy on Shopify?

As soon as possible. We are submitting for our first review on 12/12 but will most likely have more development work for a short while after. Preferably by the new year if possible.

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
Hi Owen — the icon is created properly, but I would recommend making the logo smaller within the icon. You can see how the Visa icon has plenty of white space around the logo while yours only has 1px.

**Comment by ocruse7** [comment]
Went ahead and resized that icon and re-optimized the svg. Hope this should be good to go!

**Review by Bernis245 — APPROVED** [review]

**Comment by ocruse7** [comment]
Fixed merge conflicts for submission

**Comment by ocruse7** [comment]
re-merged to fix conflicts

**Comment by ocruse7** [comment]
CI failed, looking into cause

**Comment by ocruse7** [comment]
Removed the  tag from the SVG as no base64 image data is present, and changed the title text from 'AeroPay' to 'Aeropay' as this was causing tests to fail.

**Comment by ocruse7** [comment]
Changed the id in <title> tag to lowercase as well as the 'aria-labelledby' tag to lowercase to fix CI issues

**Comment by ocruse7** [comment]
One last fix pushed

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
