### PR TITLE
new viabill icon

### PR DESCRIPTION
**Pull request by ugurviabill**
** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by ugurviabill** [comment]
I have changed title name from "Viabill" to "ViaBill".  That was the error I was getting.

image

**Comment by larouxn** [comment]
👋 @ugurviabill, can we adjust this new icon to match the same shape/size as Visa and other icons? We can probably use the [template](https://github.com/activemerchant/payment_icons/blob/62017ee4bd124d8dc0eea23868f5c49ee84f4aa6/CONTRIBUTING.md#template).

Screen Shot 2022-02-25 at 15 48 05

**Comment by larouxn** [comment]
👋 Hmm, icon still looks to be too big and now there are some unrelated files in the PR. Can we adjust and cleanup?
Screen Shot 2022-02-25 at 17 06 46
Screen Shot 2022-02-25 at 17 06 59

**Comment by ugurviabill** [comment]
I have deleted the auto created idea folder. Mine's width - height are also 38 24. But I deleted an extra <g tag. And I looked from browser too. It seems they have the same dimensions right now, can you check again?

image

image

**Comment by larouxn** [comment]
:wave: @ugurviabill, looks like the icon is still a bit bigger than expected. I think https://github.com/activemerchant/payment_icons/pull/567#issuecomment-1055450102 over in this other PR might be helpful. Pretty sure it's a border related issue.
Screenshot from 2022-03-02 22-53-18

We'll also want to SVGO clean this SVG up / shrink down to a single line. ([step 5 in this guide](https://github.com/activemerchant/payment_icons/blob/292b73b1a133a10777ae76f400e244fb60fe172f/CONTRIBUTING.md#contributing))

**Comment by ugurviabill** [comment]
Alright, this time it can be it.

image

**Review by larouxn — APPROVED** [review]
Looks good to me 🙌 
Screen Shot 2022-03-10 at 10 40 34

**Review by tauthomas01 — APPROVED** [review]

**Comment by ugurviabill** [comment]
Hello. It is merged but the particular image did not change. Below image should have been updated right? In payment section, or store's payment provider section.

image

**Comment by larouxn** [comment]
👋 Hey @ugurviabill, the updated icon first needs to be removed then rolled out. You can follow the release over here: https://github.com/activemerchant/payment_icons/pull/589.

I'd expect the update icon will be live next week.

**Comment by larouxn** [comment]
👋 We're planning to have this updated icon live this week. Will update here when it's available.

**Comment by larouxn** [comment]
👋 Hello there, your updated icon should be live everywhere now.

**Pull request merged**
