### PR TITLE
Add UangMe icon

### PR DESCRIPTION
**Pull request by andykim**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by andykim** [comment]
Hi @larouxn

I fixed my icon and push again. Please review it. Thank you.

**Comment by andykim** [comment]
Hi @larouxn

I fixed my icon. Please review it again. Thanks so much

**Review by larouxn — CHANGES_REQUESTED** [review]
The icon needs to be adjusted. Please refer to the [template](https://github.com/activemerchant/payment_icons/blob/86555a6350b165b0387299430b0896687c2199bf/CONTRIBUTING.md#template).
image

(likely the border is inverted or something)

**Comment by andykim** [comment]
> The icon needs to be adjusted. Please refer to the [template](https://github.com/activemerchant/payment_icons/blob/86555a6350b165b0387299430b0896687c2199bf/CONTRIBUTING.md#template). image
> 
> (likely the border is inverted or something)

Hi @larouxn 

I removed the border. Can you review it again?

Thank you :pray:

**Review by larouxn — CHANGES_REQUESTED** [review]
👋 @andykim, does this SVG icon need to be as complex as it is? It's over 1/3 of a megabyte even as straight SVG. Nearly 100x larger than the standard Visa icon.

Screen Shot 2022-06-09 at 16 52 24Screen Shot 2022-06-09 at 16 52 04

GitHub literally won't let me include the SVG in my review cause it's too large. 😅 
Screen Shot 2022-06-09 at 17 03 25

According to https://github.com/activemerchant/payment_icons/pull/632#issuecomment-1143121915, embedding a PNG (which we don't allow for the same size concerns/reasons) seems like it might even be lighter. 🤔

**Comment by andykim** [comment]
Hi @larouxn 

I optimized the icon size. can you please review it again? thanks :pray:

**Comment by larouxn** [comment]
Icon does look nice but it is still quite big. Still about 42x bigger than the Visa icon. 🤔 
Screen Shot 2022-06-09 at 16 52 24Screen Shot 2022-06-14 at 15 28 12

@tauthomas01, any thoughts on this icon and its size?

**Comment by andykim** [comment]
Hi @larouxn.  I see, it's because this icon has some effect on logo styles. But I have reduced its size from > 300kb to 164kb.

**Review by larouxn — APPROVED** [review]
Do with the icon was even more compact as it's still many times larger than the Visa icon, for reference, but in the end it's likely alright.
Screen Shot 2022-06-23 at 18 24 56

**Comment by andykim** [comment]
Hi @tauthomas01 @larouxn I followed the instruction and added the border for icon 
Can you please review it again?

Thanks 

Screenshot from 2022-06-27 13-37-28

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the border is off. Maybe we can base the icon on the [template](https://github.com/activemerchant/payment_icons/blob/c9d880d52728e6e3a2af1be9a81ec5f55b841803/CONTRIBUTING.md#template)?
image

I think the issue might be the border is supposed to be on the inside. :thinking:

**Comment by andykim** [comment]
Hi @larouxn I changed the border again. Looks like it's the same as visa icon.

Screenshot from 2022-06-27 22-11-41

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-28 at 17 31 39

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 We batch our icon updates, so you can expect this icon to be live within a few weeks/within the month. We will update here again, letting you know, when the updated/added icon is available. 🙇‍♂️

**Comment by andykim** [comment]
Thanks @larouxn :pray :pray :pray

**Comment by larouxn** [comment]
👋 Hello, we're working on the [v1.7.16](https://github.com/activemerchant/payment_icons/pull/702) release now. It will likely go live next week.

Apologies for the wait. Will report back here when it's live. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

**Comment by andykim** [comment]
> wave Hello, your new/updated icon(s) should now be live everywhere. sparkles

Thanks @larouxn :pray:

**Pull request merged**
