### PR TITLE
Add Indonesia payment method

### PR DESCRIPTION
**Pull request by omarxp**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by omarxp** [comment]
Hi team, kindly help to review this PR, thank you.

**Comment by omarxp** [comment]
Hi Shopify team! @larouxn @tauthomas01 
same as a concern [here](https://github.com/activemerchant/payment_icons/pull/567#issuecomment-1063096874), we are also preparing our new payment app to be released and waiting for the icons in this PR to be approved and merged.
kindly help to check this, thank you.

**Comment by omarxp** [comment]
Hi Shopify team! @larouxn @tauthomas01
kindly help to review and approve this PR, thank you.

**Comment by omarxp** [comment]
Hi Shopify team! @larouxn @tauthomas01
please help to check, we need the icons to add to our payment app extension  on the Shopify partner account
Screen Shot 2022-04-13 at 12 02 29
please reply, so we know if there is a thing that we need to update, thank you

**Comment by larouxn** [comment]
👋 Hey @omarxp, sorry for the delay. We can take a look at these new icons soon.

**Comment by omarxp** [comment]
thank you for the prompt response, really appreciated
waiting for the feedback, thank you

**Review by larouxn — APPROVED** [review]
All icons generally look good to me. 🎩 
Screen Shot 2022-04-14 at 14 21 03
Screen Shot 2022-04-14 at 14 21 32
Screen Shot 2022-04-14 at 14 22 00
Screen Shot 2022-04-14 at 14 22 36
Screen Shot 2022-04-14 at 14 22 58
Screen Shot 2022-04-14 at 14 23 15
Screen Shot 2022-04-14 at 14 23 33
Screen Shot 2022-04-14 at 14 23 49

Only one that's a little odd is `brimo` since it's a square inside the rectangle but that seems to be their logo according to https://promo.bri.co.id/main/product/main/brimo_e_payment.

**Comment by omarxp** [comment]
yes, I use `brimo` logo based on it.

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
:wave: The icon has been merged. We usually batch icons, release, and then rollout across Shopify about once a month.

I'd expect this be live within April, perhaps in the next few weeks.

**Comment by larouxn** [comment]
👋 Hello, your icon(s) should be available everyone now. Please let us know if otherwise.

**Comment by omarxp** [comment]
Hi @larouxn thank you, now I can search and use the icons 👍 
Screen Shot 2022-04-28 at 17 06 28
Screen Shot 2022-04-28 at 17 10 02

**Pull request merged**
