### PR TITLE
Add wave mobile money icon

### PR DESCRIPTION
**Pull request by tolu-paystack**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by tolu-paystack** [comment]
Hey @hellicarusprime is this a new requirement? I see several older icons in the yml file have underscores in their names
Screenshot 2024-02-12 at 09 24 14

**Comment by adeniyiao** [comment]
@tolu-paystack , previously this was this case for older PRs. However, going forward, the image file name and `name` in the `yml` file should be same and must be lowercase alpha characters only.

**Comment by tolu-paystack** [comment]
Ah gotcha @adeniyiao. I've made the required changes

**Comment by tolu-paystack** [comment]
@hellicarusprime please re-review

**Review by hellicarusprime — APPROVED** [review]

**Comment by adeniyiao** [comment]
Hi @tolu-paystack ,  could you please rebase your branch `tolu-paystack:wave_mobile_money` with `activemerchant/master ` to resolve the conflicts. 

Thanks

**Comment by tolu-paystack** [comment]
Hey @adeniyiao I messed up the rebase and somehow closed this PR. I'll just create a new branch and submit a new PR

**Pull request closed without merging**
