### PR TITLE
Release v1.7.14

### PR DESCRIPTION
**Pull request by larouxn**
### New Icons
* Add Maya Bank icon by @hyubs in https://github.com/activemerchant/payment_icons/pull/614
* Add PayTo icon by @luyx2412 in https://github.com/activemerchant/payment_icons/pull/618
* Add Fintecture icon by @hugofintecture in https://github.com/activemerchant/payment_icons/pull/622
* Add Kredivo Icon by @candrasaputra in https://github.com/activemerchant/payment_icons/pull/630
* Add Palawa Icon by @candrasaputra in https://github.com/activemerchant/payment_icons/pull/631
* Add Hello Clever icon by @luyx2412 in https://github.com/activemerchant/payment_icons/pull/639
* Add Divido icon by @andivido in https://github.com/activemerchant/payment_icons/pull/623
* Add BSI icon by @candrasaputra in https://github.com/activemerchant/payment_icons/pull/629
* Add BNB Chain, Polygon and DePay icons by @spape in https://github.com/activemerchant/payment_icons/pull/634
* Add kakebaraidotcom icon by @trustring in https://github.com/activemerchant/payment_icons/pull/627
* Add GrailPay icon by @AnoopChauhan97 in https://github.com/activemerchant/payment_icons/pull/617
* Add Fortiva icon by @dinesh-mobi in https://github.com/activemerchant/payment_icons/pull/647
* Add UPI icon by @Kartik84094 in https://github.com/activemerchant/payment_icons/pull/601

### Updated Icons
* Update Sofort, Bancontact, and iDeal icons by @mseal-shopify in https://github.com/activemerchant/payment_icons/pull/644

### Maintenance
* Bump rails from 7.0.2.4 to 7.0.3 by @dependabot in https://github.com/activemerchant/payment_icons/pull/626
* [Security] Bump rack from 2.2.3 to 2.2.3.1 by @larouxn in https://github.com/activemerchant/payment_icons/pull/635
* Bump frozen_record from 0.23.0 to 0.24.1 by @dependabot in https://github.com/activemerchant/payment_icons/pull/651
* Bump frozen_record from 0.24.1 to 0.25.4 by @dependabot in https://github.com/activemerchant/payment_icons/pull/653

## New Contributors
* @hyubs made their first contribution in https://github.com/activemerchant/payment_icons/pull/614
* @hugofintecture made their first contribution in https://github.com/activemerchant/payment_icons/pull/622
* @andivido made their first contribution in https://github.com/activemerchant/payment_icons/pull/623
* @spape made their first contribution in https://github.com/activemerchant/payment_icons/pull/634
* @mseal-shopify made their first contribution in https://github.com/activemerchant/payment_icons/pull/644
* @AnoopChauhan97 made their first contribution in https://github.com/activemerchant/payment_icons/pull/617
* @dinesh-mobi made their first contribution in https://github.com/activemerchant/payment_icons/pull/647
* @Kartik84094 made their first contribution in https://github.com/activemerchant/payment_icons/pull/601

**Full Changelog**: https://github.com/activemerchant/payment_icons/compare/v1.7.13...v1.7.14

### CODE REVIEW

**Comment by hugofintecture** [comment]
Hello! I think we've have fixed our PR (#622) according to your review. Would be awesome if it could be merge in this release :) Thanks in advance.

**Comment by larouxn** [comment]
Potential additional icons we can get into this release.
- https://github.com/activemerchant/payment_icons/pull/623
- https://github.com/activemerchant/payment_icons/pull/630
- https://github.com/activemerchant/payment_icons/pull/631
- https://github.com/activemerchant/payment_icons/pull/639

**Comment by luyx2412** [comment]
Hi @zbriscoe Please review this release. Thanks

**Comment by larouxn** [comment]
> Hi @zbriscoe Please review this release. Thanks

Actually, we're waiting as I'm hoping to merge in a few other in-review icons. This release will likely go out next week.

**Comment by larouxn** [comment]
Looks like we'll be more or less ready to go after the following two PRs. 👀 
- https://github.com/activemerchant/payment_icons/pull/647
- https://github.com/activemerchant/payment_icons/pull/617

Will cut release and draft rollout PRs tomorrow/Monday and have it all live by mid to late next week.

**Pull request merged**
