### PR TITLE
Add LBC icon

### PR DESCRIPTION
**Pull request by candrasaputra**
## Why are you adding this icons?
We provide a [Shopify Payment App](https://apps.shopify.com/payments-by-xendit) and need to show the logo in the checkout page.

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon with the black background
Screen Shot 2022-10-11 at 08 43 55

### CODE REVIEW

**Review by yanoandri — APPROVED** [review]

**Comment by candrasaputra** [comment]
hi @rahilvirani please help to review

**Comment by candrasaputra** [comment]
hi @rahilvirani please help to review

**Comment by douglas** [comment]
Hello @candrasaputra! Can you fix the conflicts on your PR? I'm in charge of reviewing it 👍

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
The size and everything look good, but the file size is high because there are a lot of vectors in this image that aren't adding any visual information but are taking up file space. May you remove these and resubmit? It should bring the file size down considerably.

**Comment by Jacquesattaque** [comment]
@candrasaputra Please let us know if you still require this icon. If we haven't heard back by the end of next week we'll close this issue.

**Comment by candrasaputra** [comment]
updated

**Comment by andykim** [comment]
hi @Jacquesattaque I just optimized the icon size. Can you please help to review it again? Thanks :pray:

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
