### PR TITLE
Added the fam payment icon

### PR DESCRIPTION
**Pull request by urvesh-vasani**
## Why are you adding this icons?
I'm adding/updating this icon(s) because we are a new approved Shopify Payments partner that provides a unique platform for consumers to make payments and merchants to receive payments. Therefore, we would like to have our unique branded icon appear on the checkout payment method options that are easily recognizable by a customer.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
Screenshot from 2023-10-11 17-06-19

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Please use our template for the icon. It's missing the border.

**Comment by dipenshivlab** [comment]
Hi @Jacquesattaque 

I've updated the icon to include the required border.
## Attached a screenshot of the icon along side the example Visa icon

Screenshot from 2023-10-12 17-28-40

**Comment by urvesh-vasani** [comment]
Hi @Jacquesattaque 

I've updated the icon to include the required border.

## Attach a screenshot of the icon along side the example Visa icon
Screenshot from 2023-10-12 17-28-40

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Icon looks good; you need to resolve conflicts and ensure the automated checks clear before we can approve.

**Comment by urvesh-vasani** [comment]
Hi @Jacquesattaque,

I resolved the Conflicts.

**Comment by urvesh-vasani** [comment]
Hi @Jacquesattaque,

We're having some trouble understanding whether there are any remaining issues with the icon after resolving conflicts. Could you please provide some clarification or guidance on this matter?

**Comment by Jacquesattaque** [comment]
There are. You're failing some automated checks. @adeniyiao Are you able to take a look?

**Comment by adeniyiao** [comment]
Hi @urvesh-vasani ,

Please see below error regarding the svg. Kindly check and address. Thanks

```
{:message=>"The 'clip0_1998_12701' ID should be pi-fam-clip0_1998_12701 (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "clip0_1998_12701".
```

**Comment by dipenshivlab** [comment]
Thanks

Let us have a look

**Comment by urvesh-vasani** [comment]
Hi @Jacquesattaque @adeniyiao 

Thanks, Set the pi prefix in id as per requirement in fam SVG icon.

**Comment by urvesh-vasani** [comment]
HI @Jacquesattaque 

Everything looks great – no conflicts and all checks have passed. Is there anything else we should consider?

**Pull request merged**
