### PR TITLE
updated revolut icon

### PR DESCRIPTION
**Pull request by ismayilmusayev**
** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

Revolut brand guidelines: https://brandfolder.com/revolut/facelift-basics

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
Thanks for the update! Looks good to me. 🎩 
Screen Shot 2022-08-09 at 12 27 01

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
Aiming to have this icon live within the week. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

**Comment by ismayilmusayev** [comment]
Hi there , the new icon appears everywhere but only in the checkout page we still see the old version. 

I tried by clearing the browser cache but still the result is same. 

Could you please double check the update and let us know if any further action required on our side to ensure that the icon updated everywhere ?

Partner account Extension page: 🟢 

image

Shopify store admin payment app page: 🟢

image

Shopify store checkout page: 🔴 
image

**Comment by larouxn** [comment]
> Hi there , the new icon appears everywhere but only in the checkout page we still see the old version. 
> 
> I tried by clearing the browser cache but still the result is same. 
> 
> Could you please double check the update and let us know if any further action required on our side to ensure that the icon updated everywhere ?
> 
> Partner account Extension page: 🟢 
> 
> image
> 
> Shopify store admin payment app page: 🟢
> 
> image
> 
> Shopify store checkout page: 🔴 
> image
> 
> 
> 

Hello hello, thank you for bringing this to our attention. Will see if we can get that fixed up shortly. Should be a relatively simple fix. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello @ismayilmusayev, we just shipped a potential fix for the final Revolut icon. Please let us know it looks.

**Comment by ismayilmusayev** [comment]
Hello @larouxn now it is updated on checkout page as well. Thanks so much !

**Pull request merged**
