### PR TITLE
Pay by Bank with Cashback

### PR DESCRIPTION
**Pull request by burgaard**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon along side the example Visa icon

Screenshot 2023-10-11 at 11 39 25 PM

Screenshot 2023-10-11 at 11 39 43 PM

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

Marlena Spidalieri

What's the expected date of this change to deploy on Shopify?

As soon as possible. Our payment app is already live in the Shopify App Store

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
This looks like it's advertising a feature of the payment method, not an icon for the payment method itself. There are other ways to indicate a discount like this in checkout that would be in the merchant's control.

**Comment by Jacquesattaque** [comment]
@bcurran58 Thanks for the context. It's clear that we need to enable functionality to promote a payment method in this way, but a payment icon isn't the way to do it. The intention of this public repo is to host payment method icons. What you're proposing isn't the icon for a payment method, but a way to advertise a feature of the payment method. We'll take this back as a feature request.

**Comment by bcurran58** [comment]
@Jacquesattaque - understood. Thanks for taking as a feature request. We'll submit our Pay by bank logo. @burgaard

**Comment by burgaard** [comment]
PR with Pay by Bank logo @Jacquesattaque: https://github.com/activemerchant/payment_icons/pull/943

**Pull request closed without merging**
