### PR TITLE
Souhoola, Aman, Forsa (Egypt) payment methods

### PR DESCRIPTION
**Pull request by wajihkm**
## Why are you adding this icons?
I'm adding/updating these icons because our Payment gateway supports them and want to show the icons to our merchants.

#### Help us identify yourself
- I'm associated with the brand and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

image

#### If the icons are intended for use by Shopify, please provide the following info:
PayTabs payment gateway company [PayTabs](https://site.paytabs.com)

What's the expected date of this change to deploy on Shopify?
ASAP

### CODE REVIEW

**Comment by hellicarusprime** [comment]
Hi @wajihkm the icons look fine from a contributing guidelines perspective, but I wanted to mention that the one for Aman looks a little off with the space at the top and bottom.

**Comment by wajihkm** [comment]
Hi @hellicarusprime , regarding Aman, yes I see this, but I can't change the Logo since it is the official one from Aman company.
I should obey to the same dimensions.

**Comment by hellicarusprime** [comment]
Hi @wajihkm—apologies for not getting back to you sooner. The best option would be to change the white background to match the icon color. The icon remains the same, but it would be better suited to the dimensions we ask for. Here's an example of what I'm talking about.
image

**Comment by wajihkm** [comment]
Hi @hellicarusprime , I have updated the logo as suggested, please review.

**Review by hellicarusprime — APPROVED** [review]

**Comment by adeniyiao** [comment]
Hi @wajihkm 
Kindly address the error below and rebase your PR against  activemerchant:master

```
Failure:
PaymentIconTest#test_Payment_icon_SVGs_are_a_single_line [test/unit/payment_icon_test.rb:127]:
The 'aman' SVG file should contain a single line of markup, optionally terminated by an empty line
```

Thanks

**Pull request closed without merging**
