### PR TITLE
Snap Checkout Icon

### PR DESCRIPTION
**Pull request by spatel-snap**
** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by spatel-snap** [comment]
I have already added the "pi" prefix in the image name. find the screenshot for more details.
pi-snap_checkout
Let me know what is missing anything from my side?
Please elaborate it

**Comment by spatel-snap** [comment]
Hello,

I have updated the "pi-snap_checkout-" prefix of each ids value.
please check and let me know if there is missing anything.

**Comment by spatel-snap** [comment]
Hello,
Updated the svg in single-line format

**Comment by larouxn** [comment]
:wave: @spatel-snap, I just took a look at the icon. I see it is an embedded png. As we're trying to keep the gem size from increasing much further, we're only looking to incorportate SVG icons at this point if possible. Any chance we can fix up this icon with a proper SVG?

Screenshot from 2022-02-22 21-03-47

**Comment by spatel-snap** [comment]
> we're only looking to incorportate SVG icons a
Let me share the incorporated SVG icon, How can I share it again? Because this PR is approved now

**Comment by larouxn** [comment]
> Let me share the incorporated SVG icon, How can I share it again? Because this PR is approved now

We can update this PR or create a new PR. Regarding approval, actually this PR is not yet approved, it's just passing automatic tests.
Screenshot 2022-02-23 085658

**Comment by spatel-snap** [comment]
Hello,
Updated the proper svg icon

**Comment by spatel-snap** [comment]
Hey,

Can you please review this commit?

**Comment by spatel-snap** [comment]
@larouxn Can you please review this svg image updated

**Comment by spatel-snap** [comment]
@larouxn I need to live my application as soon as possible. Please review and approve this svg if this is correct? Let me know if there is missing anything from my side?

**Comment by larouxn** [comment]
👋 @spatel-snap, I will take a look at https://github.com/activemerchant/payment_icons/pull/567.

**Pull request closed without merging**
