### PR TITLE
Add Acima Leasing, Checkout Finance, Echelon Finance, Synchrony Pay, SatisFi icons

### PR DESCRIPTION
**Pull request by Eduard-CA**
** Checklist **
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — CHANGES_REQUESTED** [review]
👋 @Eduard-CA, can we update these new icons with the rounded design like other icons? There's a template available for use over [here](https://github.com/activemerchant/payment_icons/blob/43e4df86ac2a4b604650dafb615ce8f68d75da26/CONTRIBUTING.md#template) in the contribution guide.
Screen Shot 2022-02-01 at 20 10 56

**Comment by Eduard-CA** [comment]
@larouxn Thanks. We updated the template for icons

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-02-03 at 11 35 59

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 @Eduard-CA, thanks for the contribution! Quick heads up that the icon likely won't be live for a few weeks at least since we'll be batching it with some other icons and doing the rollout after that.

**Comment by larouxn** [comment]
👋 Hello hello, your icon(s) should be live everywhere now. Please let us know if otherwise. 🙇‍♂️

**Pull request merged**
