### PR TITLE
Add Scalapay payment icon

### PR DESCRIPTION
**Pull request by luxifel**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — COMMENTED** [review]
👋@luxifel, looks like the icon might have it's border inverted or something. The icon is showing up larger than default. Maybe we can base it on this template [here](https://github.com/activemerchant/payment_icons/blob/d88e79e3fc7ce7801530571baaaf95e326487f13/CONTRIBUTING.md#template).
Screenshot 2022-02-15 065849

**Comment by luxifel** [comment]
Thx I'll take a look

**Comment by luxifel** [comment]
@larouxn hi, icon should be correct now

**Comment by larouxn** [comment]
👋 Hey @luxifel, it looks like the icon is still a bit too big. Additionally, it looks like it's missing the 0.7% opacity border as outlined in the [contribution guide](https://github.com/activemerchant/payment_icons/blob/ee8a3334fb4a24f8c3bef6f9fc3c7eb81e0972d6/CONTRIBUTING.md#appearance). Will also need to `svgo` optimize it down to a single line as well. ([step 5](https://github.com/activemerchant/payment_icons/blob/ee8a3334fb4a24f8c3bef6f9fc3c7eb81e0972d6/CONTRIBUTING.md#contributing))

```svg
# something like this
<path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/>
```

Screen Shot 2022-02-17 at 08 03 05

**Comment by luxifel** [comment]
@larouxn should be fixed tight now. Used svgo online cause the library in the doc is deprecated and the disable option is no more available in new version. Added border now it should be ok.

**Review by larouxn — APPROVED** [review]
Looks good to me :tophat: 
Screenshot from 2022-02-21 19-29-35

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Thanks for the contribution. Quick heads up that we usually batch icons for release then rollout so it may be a little while (few weeks to a month) before this icon is full live everywhere. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Update on our end, we're planning to have this new icon live this week. Will update here when it's available.

**Comment by larouxn** [comment]
👋 Hello there, your new icon should be live everywhere now.

**Pull request merged**
