### PR TITLE
added upi icon on payment method

### PR DESCRIPTION
**Pull request by Kartik84094**
added upi icon on payment method

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by Kartik84094** [comment]
please review it and merge

**Review by larouxn — CHANGES_REQUESTED** [review]
Icon does not appear to be rendering. Maybe try overlaying it on top of the [template](https://github.com/activemerchant/payment_icons/blob/b2ebb1241bc8bb7da0d2a196c7576696d7a0bfe4/CONTRIBUTING.md#template).
Screenshot 2022-04-21 195059

**Comment by Kartik84094** [comment]
I have resoled the merge conflicts so now please review it and merge.

**Comment by larouxn** [comment]
👋 Can we add a coloured (white?) background? It's currently transparent.
Screen Shot 2022-04-25 at 15 36 19

**Comment by Kartik84094** [comment]
sure

> 👋 Can we add a coloured (white?) background? It's currently transparent. Screen Shot 2022-04-25 at 15 36 19

sure... will do the changes.

**Comment by larouxn** [comment]
👋 Icons till looks transparent. Can we add solid white background like the [template](https://github.com/activemerchant/payment_icons/blob/f5224c8fff0c476ab626f9c5cd4c043a689c9f50/CONTRIBUTING.md#template)?

**Comment by Kartik84094** [comment]
Hi @larouxn 
I made the changes so kindly review and merge it.

**Comment by Kartik84094** [comment]
Hi @larouxn
I made the changes so kindly review and approve it.

**Comment by larouxn** [comment]
👋 Hey @Kartik84094, looks like the icon needs to be optimized (down to a single line). ([CI logs](https://github.com/activemerchant/payment_icons/runs/6483577316?check_suite_focus=true))

```
Failure:
PaymentIconTest#test_Payment_icon_SVGs_are_a_single_line [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:127]:
The 'upi' SVG file should contain a single line of markup, optionally terminated by an empty line

rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:124
```

This can be accomplished with `SVGO` according to the [contribution guide](https://github.com/activemerchant/payment_icons/blob/edc00a06ccd5bba6388bd9311974061a07135688/CONTRIBUTING.md#contributing).

**Comment by Kartik84094** [comment]
Hi, @larouxn Please help me review soon. Thanks

**Comment by Kartik84094** [comment]
Hi, @larouxn Please help me review soon. Thanks

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-14 at 15 26 22

**Review by tauthomas01 — APPROVED** [review]

**Comment by Kartik84094** [comment]
now can we able to add upi payment method?

**Comment by larouxn** [comment]
> now can we able to add upi payment method?

This PR will need to merged, the gem released, and the new library rolled out everywhere first. Will likely take a week or so. _Maybe_ within this week. We will comment here when the new icon is live.

**Comment by larouxn** [comment]
👋 Hello, your icon(s) have been released in the latest version of this library. The rollout process will begin within a few days. We wanted to have it/them live this week but looking more likely to be live early to mid next week. Will report back here when live. Thank you for your patience. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, actually your icon(s) should be live everywhere now. 🚀

**Pull request merged**
