### PR TITLE
Add Smartpay icon

### PR DESCRIPTION
**Pull request by pjan**
Adds the logo for Smartpay: https://smartpay.co

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — COMMENTED** [review]
LGTM 🎩 
Screen Shot 2022-02-17 at 08 11 08

That said, can we rebase this PR to drop the non-icon-contribution specific changes. The odd spaces have removed in a separate PR (https://github.com/activemerchant/payment_icons/pull/559). Thanks for bringing those to our attention by the way.

**Comment by pjan** [comment]
@larouxn rebased - happy to help on the other front, be it just through VSCode settings hunting for these

**Review by larouxn — APPROVED** [review]

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Thanks for the contribution. Quick heads up that we usually batch icons for release then rollout so it may be a little while (few weeks to a month) before this icon is full live everywhere. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Update on our end, we're planning to have this new icon live this week. Will update here when it's available.

**Comment by pjan** [comment]
🙏🙌👏

**Comment by larouxn** [comment]
👋 Hello there, your new icon should be live everywhere now.

**Pull request merged**
