### PR TITLE
Kasssh

### PR DESCRIPTION
**Pull request by kishan93**
## Why are you adding this icons?
I'm adding/updating this icon(s) because Our payment app uses this payment method, so we need this icon to be shown on the checkout page, hence customers can recognize it

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

Updated Screenshot:
image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
@adeniyiao 

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Please use our template for creating this icon. Your icon doesn't fill the required space, and uses the incorrect border.

**Comment by kishan93** [comment]
@Jacquesattaque We have fixed the requested changes

here are the new screenshots of comparison with the `Visa` icon


image

image

**Comment by kishan93** [comment]
Hi @Jacquesattaque 
I have fixed the changes requested by you.

let me know if there's something missing.

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
There are a bunch of extra paths in the dollar sign that should be removed to reduce file size. Merge/flatten these and I will approve.

**Comment by kishan93** [comment]
@Jacquesattaque I have removed those extra paths.

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
