### PR TITLE
Updating LinkPay icon to include name

### PR DESCRIPTION
**Pull request by ssoper**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

Updating an existing icon originally added in https://github.com/activemerchant/payment_icons/pull/691

cc @amritlink @fjmarcos98

### CODE REVIEW

**Comment by ssoper** [comment]
hi @larouxn we are updating an icon originally submitted in https://github.com/activemerchant/payment_icons/pull/691, can you please run the checks and merge if everything passes? thanks

**Comment by larouxn** [comment]
👋 Hello, apologies but I (personally) no longer maintain this gem. If this icon is for use within Shopify you may be able to reach out to your partner manager and/or the payments platform team.

**Review by rahilvirani — CHANGES_REQUESTED** [review]
image

It seems like the logo is getting chopped on both the sides.

**Comment by ssoper** [comment]
Now with more padding, @rahilvirani please re-review when you get a chance, thanks!
Screenshot 2022-09-19 at 11 19 05 AM

**Comment by fjmarcos98** [comment]
@rahilvirani Please re-review when you get the chance. Thank you!

**Comment by fjmarcos98** [comment]
@rahilvirani please re-review when you have a chance! Thank you :)

**Comment by rahilvirani** [comment]
@fjmarcos98 will review them soon.

**Comment by lunataoo** [comment]
Looks good
SVG Editor:Viewer Online 🔊 2022-10-11 14-10-17

**Comment by ssoper** [comment]
thank you @lunataoo , what steps are remaining to get the final approval on this PR?

**Review by rahilvirani — APPROVED** [review]
👍 looks good!

**Comment by ssoper** [comment]
@rahilvirani hey there just wanted to check in and see when a new release would go out. looks like the last one was from September, hoping to see our new icon out in the wild. any help appreciated, thanks! cc @fjmarcos98

**Pull request merged**
