### PR TITLE
Add Afterpay Pay.nl Version

### PR DESCRIPTION
**Pull request by max-geraci**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by tauthomas01** [comment]
Hi @max-geraci ,

Can you please run your SVG code through svgo? See the [instructions](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#contributing)

**Comment by woutse** [comment]
@tauthomas01 I've run the SVG code through svgo, seems to go fine: 
afbeelding

Is everything okay now?

**Comment by woutse** [comment]
This PR will be droped, a new PR is made https://github.com/activemerchant/payment_icons/pull/282

**Comment by rahilvirani** [comment]
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

**Pull request closed without merging**
