### PR TITLE
adding resolvepay icon

### PR DESCRIPTION
**Pull request by resolveeng**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: https://www.figma.com/file/Wt7KZnuPr0UlZZ3beBUG43/Brand-guide?type=design&node-id=2%3A258&mode=design&t=J2IuHLm01uIQ7r0D-1

  - We are currently revamping part of our docs website and the link above will provide with details on brand guidelines that we are going to make public soon.

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

Screenshot: 

Screen Shot 2024-01-25 at 12 51 50 PM

image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
- We are Resolve Pay - https://resolvepay.com/ - and we provide with a SaaS solution for B2B / BNPL payments to a large number of merchants.
- We are currently an approved Shopify Payments Partner and we are developing an offsite payment app. We would like to have this icon approved, so we can attach it to the extension we are implementing, which will be used as a payment method in the merchant's checkout page. There isn't a specific person we are working with. We have been approved as partner some time ago and we are essentially following Shopify docs to implement our app and eventually contacting Shopify support for clarifications.

What's the expected date of this change to deploy on Shopify?
- As soon as possible, as we are in final stages of our app implementation. We should expect merchant to get onboarded by the first week of February/2024.
- I am using the company's github account engineering@resolvepay.com, but you can reach out to me at luccas@resolvepay.com.

### CODE REVIEW

**Comment by hellicarusprime** [comment]
@resolveeng The way you're applying the border to the icon doesn't look right. Please refer to our [contributing guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance) and update.

**Comment by resolveeng** [comment]
@hellicarusprime Thanks for the feedback. We applied the #00000 0.07 2px border radius stroke. However, we noticed that making the border radius outside as requested in the guidelines made the dimensions of our logo appear bigger when applied (but the dimensions are still technically 38x24). Because of this, we wanted to know if it would be better to send a logo that is technically 37x23 but 'looks' correct. I've attached a photo for reference. Looking forward to your reply!
Screen Shot 2024-01-29 at 10 21 16 PM

**Comment by resolveeng** [comment]
Thank you @hellicarusprime . I have pushed a new commit to the PR.

Screen Shot 2024-02-01 at 4 39 08 PM

**Comment by hellicarusprime** [comment]
Hey @resolveeng—to ensure we have the correct 2 px border-radius, the background layer should be 36 x 22 with the 1 px border applied to the outside. This will make it the appropriate 38 x 24. Apologies for any confusion.

**Comment by resolveeng** [comment]
@hellicarusprime just pushed new commit with the suggested fix. Please let me know if that meets the requirements. Thank you.

**Comment by hellicarusprime** [comment]
Hey @resolveeng, there's still something off with it. This might help to explain things more clearly.

image

**Comment by resolveeng** [comment]
@hellicarusprime just pushed a fix. Please let us know if that looks better. Apologies for the back and forth.

image

**Review by hellicarusprime — APPROVED** [review]

**Comment by resolveeng** [comment]
hello @hellicarusprime , any idea of when this is going to be available in the Shopify partners portal? Thank you.

**Comment by resolveeng** [comment]
hello @hellicarusprime @adeniyiao 
any idea of when a new release will come out with the new logos?

**Comment by adeniyiao** [comment]
Hi @resolveeng , 

The PR is failing some tests with error below. Could you please address. Thanks

```
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:89]:
{:message=>"The 'clip0_17506_909' ID should be pi-resolvepay-clip0_17506_909 (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "clip0_17506_909".
```

**Comment by resolveeng** [comment]
thank you @adeniyiao . I have pushed a fix to the ID as requested. Can you check if tests are successful now?

**Comment by resolveeng** [comment]
hello @hellicarusprime  @adeniyiao 
is there anything else you need from our end to create a new release?
Thank you.

**Pull request merged**
