### PR TITLE
add divido icon

### PR DESCRIPTION
**Pull request by andivido**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by andivido** [comment]
@larouxn , I've amended the svg title, which was causing the workflow checks to fail. Would you be able to run the workflow again?

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-01 at 13 50 22

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
Hi,

Please follow the [contributions](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) guideline:
- The border of the icon is missing [video example](https://screenshot.click/01-12-4314f-n348a.mp4)

You can follow this [example icon](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/visa.svg) as a reference.

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
image

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Hello, your icon(s) have been released in the latest version of this library. The rollout process will begin within a few days. We wanted to have it/them live this week but looking more likely to be live early to mid next week. Will report back here when live. Thank you for your patience. 🙇‍♂️

**Comment by andivido** [comment]
Thanks for the update @larouxn , and thanks for your work in getting it into the latest release

**Comment by larouxn** [comment]
👋 Hello, actually your icon(s) should be live everywhere now. 🚀

**Pull request merged**
