### PR TITLE
Payjustnow icon

### PR DESCRIPTION
**Pull request by matthewmonson**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [X ] I'm working/collaborating with the brand directly and they have provided the icons.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [X ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ X] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-payjustnow" role="img"><title id="pi-payjustnow">PayJustNow</title><rect width="38" height="24" rx="2" fill="#fff"/><path d="M27.115 11.853l-1.03.674a9.198 9.198 0 00-5.85-4 9.192 9.192 0 00-6.965 1.312 9.192 9.192 0 00-3.658 4.654H8.315a10.415 10.415 0 014.282-5.684 10.408 10.408 0 017.889-1.488 10.417 10.417 0 016.63 4.532z" fill="#EA516C"/><path d="M20.916 5.272l-.255 1.21a11.26 11.26 0 00-8.532 1.61 11.269 11.269 0 00-4.706 6.4h-1.28a12.504 12.504 0 015.31-7.436 12.486 12.486 0 019.463-1.784z" fill="#29AAF2"/><path d="M10.99 6.346a13.344 13.344 0 00-5.719 8.146h-1.26a14.573 14.573 0 016.305-9.177l.673 1.031z" fill="#86E3E8"/><path d="M5.038 17.742h-.444v.798h-.583v-2.66h1.084c.633 0 1.015.378 1.015.92v.007c0 .616-.477.935-1.072.935zm.481-.93c0-.262-.182-.403-.474-.403h-.45v.813h.462c.292 0 .462-.174.462-.401v-.01zM8.252 18.538l-.242-.597H6.888l-.243.597H6.05l1.137-2.678h.538l1.137 2.678h-.61zm-.803-1.973l-.353.862h.705l-.352-.862zM10.187 17.478v1.06h-.584V17.49l-1.02-1.61h.683l.633 1.068.644-1.068h.664l-1.02 1.598zM12.188 18.578c-.398 0-.651-.198-.818-.472l.216-.186c.163.246.33.379.606.379.3 0 .52-.216.52-.637v-1.781h.303v1.777c0 .61-.353.92-.827.92zM15.894 17.402c0 .775-.444 1.177-1.107 1.177-.656 0-1.103-.402-1.103-1.154v-1.546h.3v1.527c0 .574.303.896.81.896.49 0 .8-.295.8-.877v-1.546h.3v1.523zM17.554 17.065c.591.129.864.347.864.756 0 .459-.379.756-.906.756-.42 0-.765-.14-1.084-.424l.186-.22c.277.25.542.375.91.375.356 0 .591-.186.591-.455 0-.25-.133-.392-.69-.508-.61-.132-.89-.33-.89-.771 0-.426.367-.73.871-.73.387 0 .664.11.933.326l-.175.231a1.165 1.165 0 00-.765-.288c-.345 0-.565.19-.565.434 0 .252.136.393.72.518zM19.976 18.538h-.303v-2.38h-.89v-.278h2.084v.277h-.89v2.38zM23.234 18.538l-1.285-1.69v1.69h-.578V15.88h.538l1.244 1.638V15.88h.576v2.658h-.495zM25.656 18.585c-.819 0-1.406-.61-1.406-1.368v-.008c0-.756.595-1.374 1.414-1.374.818 0 1.406.61 1.406 1.366v.008c0 .756-.595 1.376-1.414 1.376zm.804-1.376c0-.457-.334-.836-.804-.836-.47 0-.796.372-.796.828v.008c0 .457.334.836.804.836.47 0 .796-.372.796-.828v-.008zM30.354 18.558h-.508l-.598-1.74-.6 1.74h-.507l-.906-2.678h.625l.55 1.8.595-1.807h.5l.595 1.808.55-1.8h.61l-.906 2.677zM32.921 17.516a.825.825 0 01-.411-.101.744.744 0 01-.28-.28.817.817 0 01-.101-.408c0-.153.033-.289.101-.407a.737.737 0 01.28-.284.825.825 0 01.411-.101c.154 0 .29.034.408.101a.71.71 0 01.276.284.803.803 0 01.102.407.817.817 0 01-.102.408.717.717 0 01-.276.28.804.804 0 01-.408.101zm0-.173a.572.572 0 00.434-.17.618.618 0 00.167-.446.61.61 0 00-.167-.445.573.573 0 00-.434-.17.59.59 0 00-.441.17.618.618 0 00-.163.445c0 .182.054.33.163.446a.59.59 0 00.441.17zm-.324-.223v-.804h.392c.086 0 .154.023.204.068.053.045.08.107.08.185 0 .118-.057.196-.17.234l.203.313-.256.004-.178-.298h-.049v.298h-.226zm.222-.46h.14a.086.086 0 00.057-.02c.017-.012.026-.032.026-.06 0-.025-.009-.043-.026-.053a.085.085 0 00-.057-.019h-.14v.151z" fill="#12183D"/><rect x=".5" y=".5" width="37" height="23" rx="2" stroke="#000" stroke-opacity=".07"/></svg>

<br>
<!-- TODO: insert your icon here -->
<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-payjustnow" role="img"><title id="pi-payjustnow">PayJustNow</title><rect width="38" height="24" rx="2" fill="#fff"/><path d="M27.115 11.853l-1.03.674a9.198 9.198 0 00-5.85-4 9.192 9.192 0 00-6.965 1.312 9.192 9.192 0 00-3.658 4.654H8.315a10.415 10.415 0 014.282-5.684 10.408 10.408 0 017.889-1.488 10.417 10.417 0 016.63 4.532z" fill="#EA516C"/><path d="M20.916 5.272l-.255 1.21a11.26 11.26 0 00-8.532 1.61 11.269 11.269 0 00-4.706 6.4h-1.28a12.504 12.504 0 015.31-7.436 12.486 12.486 0 019.463-1.784z" fill="#29AAF2"/><path d="M10.99 6.346a13.344 13.344 0 00-5.719 8.146h-1.26a14.573 14.573 0 016.305-9.177l.673 1.031z" fill="#86E3E8"/><path d="M5.038 17.742h-.444v.798h-.583v-2.66h1.084c.633 0 1.015.378 1.015.92v.007c0 .616-.477.935-1.072.935zm.481-.93c0-.262-.182-.403-.474-.403h-.45v.813h.462c.292 0 .462-.174.462-.401v-.01zM8.252 18.538l-.242-.597H6.888l-.243.597H6.05l1.137-2.678h.538l1.137 2.678h-.61zm-.803-1.973l-.353.862h.705l-.352-.862zM10.187 17.478v1.06h-.584V17.49l-1.02-1.61h.683l.633 1.068.644-1.068h.664l-1.02 1.598zM12.188 18.578c-.398 0-.651-.198-.818-.472l.216-.186c.163.246.33.379.606.379.3 0 .52-.216.52-.637v-1.781h.303v1.777c0 .61-.353.92-.827.92zM15.894 17.402c0 .775-.444 1.177-1.107 1.177-.656 0-1.103-.402-1.103-1.154v-1.546h.3v1.527c0 .574.303.896.81.896.49 0 .8-.295.8-.877v-1.546h.3v1.523zM17.554 17.065c.591.129.864.347.864.756 0 .459-.379.756-.906.756-.42 0-.765-.14-1.084-.424l.186-.22c.277.25.542.375.91.375.356 0 .591-.186.591-.455 0-.25-.133-.392-.69-.508-.61-.132-.89-.33-.89-.771 0-.426.367-.73.871-.73.387 0 .664.11.933.326l-.175.231a1.165 1.165 0 00-.765-.288c-.345 0-.565.19-.565.434 0 .252.136.393.72.518zM19.976 18.538h-.303v-2.38h-.89v-.278h2.084v.277h-.89v2.38zM23.234 18.538l-1.285-1.69v1.69h-.578V15.88h.538l1.244 1.638V15.88h.576v2.658h-.495zM25.656 18.585c-.819 0-1.406-.61-1.406-1.368v-.008c0-.756.595-1.374 1.414-1.374.818 0 1.406.61 1.406 1.366v.008c0 .756-.595 1.376-1.414 1.376zm.804-1.376c0-.457-.334-.836-.804-.836-.47 0-.796.372-.796.828v.008c0 .457.334.836.804.836.47 0 .796-.372.796-.828v-.008zM30.354 18.558h-.508l-.598-1.74-.6 1.74h-.507l-.906-2.678h.625l.55 1.8.595-1.807h.5l.595 1.808.55-1.8h.61l-.906 2.677zM32.921 17.516a.825.825 0 01-.411-.101.744.744 0 01-.28-.28.817.817 0 01-.101-.408c0-.153.033-.289.101-.407a.737.737 0 01.28-.284.825.825 0 01.411-.101c.154 0 .29.034.408.101a.71.71 0 01.276.284.803.803 0 01.102.407.817.817 0 01-.102.408.717.717 0 01-.276.28.804.804 0 01-.408.101zm0-.173a.572.572 0 00.434-.17.618.618 0 00.167-.446.61.61 0 00-.167-.445.573.573 0 00-.434-.17.59.59 0 00-.441.17.618.618 0 00-.163.445c0 .182.054.33.163.446a.59.59 0 00.441.17zm-.324-.223v-.804h.392c.086 0 .154.023.204.068.053.045.08.107.08.185 0 .118-.057.196-.17.234l.203.313-.256.004-.178-.298h-.049v.298h-.226zm.222-.46h.14a.086.086 0 00.057-.02c.017-.012.026-.032.026-.06 0-.025-.009-.043-.026-.053a.085.085 0 00-.057-.019h-.14v.151z" fill="#12183D"/><rect x=".5" y=".5" width="37" height="23" rx="2" stroke="#000" stroke-opacity=".07"/></svg>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
I'd consider removing the registered trademark icon and using the space to increase the size of the logo. It's quite hard to read. You'll also have to fix the corner radius of your border, which doesn't match the icon template. There are conflicts to resolve before this can be approved. 
Screenshot 2023-05-18 at 10 18 04 AM

**Comment by matthewmonson** [comment]
Thank you for your review, I have corrected the hard issues identified. 

The client has indicated that they would like to keep the registered trademark if possible?

**Comment by Jacquesattaque** [comment]
@matthewmonson Oh yeah totally possible, it was just a recommendation to make the name more readable at such a small size.

**Comment by adeniyiao** [comment]
Hi @matthewmonson ,

The changes are good to go but we need you to rebase your branch PJN-Repo:payjustnow_icon with activemerchant/master to resolve the conflicts.

After the rebase is done, we will be able to merge your changes.

Thanks

**Pull request merged**
