### PR TITLE
Added PayNow icon

### PR DESCRIPTION
**Pull request by rifeman2007**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by rifeman2007** [comment]
Hi @tauthomas01. Can you check this PR please. Thanks

**Comment by tauthomas01** [comment]
Hi @rifeman2007 ,

For some reason, I can't view the image
image

Can you take a look?

**Comment by rifeman2007** [comment]
> Hi @rifeman2007 ,
> 
> For some reason, I can't view the icon.
> image
> 
> Can you take a look?

Hi @tauthomas01. I am able to view it though. Please screenshot https://prnt.sc/s2prq3. Thanks

**Comment by adityahitpay** [comment]
Hi @tauthomas01 , Aditya here from HitPay. @rifeman2007 is on our team and we were hoping you could help us merge this PR. Please let us know if there is any issue with the icon as we are looking to launch this payment gateway immediately for merchants in sg.

**Comment by tauthomas01** [comment]
Hi @adityahitpay , I'm trying to view the icon but the browser doesn't display.

https://github.com/activemerchant/payment_icons/raw/b69f2244a173bc7754ea86f506544a8dd8201b92/app/assets/images/payment_icons/paynow.svg

In the past, it used to display base64 image file file but, apparently, there's a security issue that prevents to show the `<image>` file:

`Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANMAAACECAYAAAAKjB6WAAAABGdBTUEAALGOfPtRkwAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAA06ADAAQAAAABAAAAhAAAAACkgwW6AAAfO0lEQVR4Ae1de4wkR3nvMY8o/BFad5YDPh59Mo5j45g2ccgDJdeX9/tmIYGEhGwP4WGDzc5ibGwe2lkRbGPH7Jx5+AFhe0USWQSxcwhIRKJsX6IEZBxubAzGgHVtsBFyfEcrSoTy8E5+32z30NtT3V1fVU/PzG1/Uk9VffW96qv6qqqre2Ya3f3v6BiGsYKrKvChKMB1HFevfeo9IdLKAO1dg7I2Q2EXNi4z6A3oGHDoU7QBypeW4RfYYULWCVwWLlU4CFsCVea9xHcWGltlIJFvHVwurnVc30OHr+OykJ84QI8LJZxAIpva4...m7hmBqz/XKNDACrFILrzp1o9aKXaJb50aUTjDNygHEzDj7wgfuWMY+agEGhTNjFM+QHsgvrQOJ57QyqOttXoYX8fULeoF0HfdJTdpFz8E9U4jVqPXKUzdRMNWg6AGdlakOpgKn4ysYFExrCCZrhg8gurhvXn3F6ZvmdTUt6IXqqutgqsDX9NY4gmmFgorUzchpnodAX8U/rgdkUw36HqiDSd+H0hLwkquLAbyCwLJo60dQ8dF4CP096F592eN1EEl3nCRhHUySjiqTDC+62hjQS9heNXGZFTxn6kPPURx39xT/PbDM5p+xsrSCSYf5jPUos2FffMFVDgLrCFYMB09dKcgM5IcPedUf2tJpYsOHrGNYBX2dv5VhNmdPk+vEA34ujbq9Bh0PNPBqUBLwbp6DZ1U2IspEMB2iyMIbDVi9hq8N7bxJsfM6ET1Y7Q8Dr4FnQ4PGI3gDoo9Y7OMnkoOkzDpfjQd04uH/AUb2qJrh54AFAAAAAElFTkSuQmCC' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by adityahitpay** [comment]
Thanks @tauthomas01. Let us check this and get back asap.

**Comment by spacemonkey92** [comment]
@tanyajajodia I think the issue is not with the file. 

When you view on file and display the render [here](https://github.com/activemerchant/payment_icons/blob/b69f2244a173bc7754ea86f506544a8dd8201b92/app/assets/images/payment_icons/paynow.svg), its perfectly visible. 

Also when you download the file locally and open it in the browser its work fine. 

Screenshot 2020-04-23 at 12 06 37 AM

I suspect the issue is when you view 'RAW' file in github 

I can reproduce the same issue from the master branch as well:
https://raw.githubusercontent.com/activemerchant/payment_icons/bd162be42b31a7b5f8ab3d2eebf874907ae637f6/app/assets/images/payment_icons/prepaysolutions.svg

But they work fine when used in the Shopify

**Comment by tanyajajodia** [comment]
@spacemonkey92 you probably tagged the wrong person?

**Comment by adityahitpay** [comment]
Hi @tauthomas01 . Please find above response from lead engineer @spacemonkey92

**Comment by adityahitpay** [comment]
Thanks @tauthomas01 
Quick question, how long does it take for the icon to appear in the partner's payment gateway settings?

**Comment by tauthomas01** [comment]
@adityahitpay It depends on how long the deployment process takes.
First I have to make a release of payment icons, afterwards the platform needs to update the payment icon versions as well.

**Comment by adityahitpay** [comment]
Ah right! @tauthomas01 
So just to confirm, there is no further action required from our end correct?
We'll keep a lookout for the icon to appear in the payment gateway settings. Thanks v much for the prompt response.

**Comment by tauthomas01** [comment]
Yes, no further action is required on your end. Hopefully it will be available at the beginning of next week.

Cheers

**Comment by adityahitpay** [comment]
Hey @tauthomas01, we still do not see the icon appearing in the payment gateway setting. Is there anyway you can help us?

**Comment by tauthomas01** [comment]
Hi @adityahitpay , do you mean the payment gateway setting in the Partners dashboard?

**Comment by adityahitpay** [comment]
Hi @tauthomas01 , yes that is correct.

**Comment by tauthomas01** [comment]
Hi @adityahitpay, it just finished deploy. Please give it a few hours and it should be available.

**Comment by adityahitpay** [comment]
Awesome thanks @tauthomas01 I see it now in the payment gateway settings. Thank you very much for your help !

**Pull request merged**
