### PR TITLE
add four new payment icons 

### PR DESCRIPTION
**Pull request by ChiaMingChuang**
## Why are you adding this icons?
I'm adding these icons because we want to use these for our payment app as a payment method.

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Please read the contribution guidelines. You will need to update the YML file for these to appear. The icons need to be smaller in file size, either through simplifying the design and/or running them through SVGO. Transfer appears to be a generic payment method. If not, please supply a link to documentation on this payment brand.

**Comment by ChiaMingChuang** [comment]
We have made modifications based on your suggestions, please assist in confirming. Additionally, the "transfer " icon is a general payment. Thank you.

**Comment by Jacquesattaque** [comment]
Thanks! The JKO icon has a larger file size than it needs to because there are empty paths in the SVG. Please remove these and optimize for size. Generic payment methods are handled by Shopify, so please remove Transfer and resubmit.
Screenshot 2023-06-09 at 10 50 22 AM

**Comment by ChiaMingChuang** [comment]
We have submitted the JKO files. Additionally, the transfer icon is mainly provided for use in our app (App ID: 1057753). Please kindly assist us in confirming this. Thank you.

**Comment by Jacquesattaque** [comment]
@ChiaMingChuang If Transfer is just for your app can you give it a more specific name? You can add the name of your app to the name of the icon.

**Comment by ChiaMingChuang** [comment]
We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Thanks! Just remove the underscore in the SVG file name and the name and label (the label can have two words separated by a space; the name must be all lowercase with no special characters).

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque  We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications, please assist in confirming. Thank you.

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Thanks — the Easy Wallet icon should have a white background. Please run all the icons through SVGO to optimize their size. There are still unnecessary vectors in the JKO SVG, and the Zingala icon looks like it was auto-traced in Illustrator. Please replace that one with the proper vector logo from the brand. You've also still got failing checks to clear.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made modifications based on your suggestions, please assist in confirming.

**Comment by Jacquesattaque** [comment]
Icons all look great, thanks for making those changes. Just the automated checks need to pass and we'll approve.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque Thank you for helping us. We have made modifications based on your suggestions, please assist in confirming. Thank you.

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque We have made the modifications based on your suggestions. Please assist in confirming them. Thank you.

**Review by Jacquesattaque — APPROVED** [review]

**Comment by ChiaMingChuang** [comment]
@Jacquesattaque Thank you sincerely for your help. We would like to know when can we select the newly added icon from the payment icon list?

**Pull request merged**
