### PR TITLE
New Icons

### PR DESCRIPTION
**Pull request by thejoshualewis**
** Checklist **
- [ x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ x] I am confident that all icons are clear and easy to read/understand
- [ x] I have provided a link to the brand icon’s brand guidelines whenever possible.

https://bitpay.com/about/brand
If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by thejoshualewis** [comment]
hi @tauthomas01 ,
I removed all the id's I can without ruining the svg, and optimized with svgo

**Comment by tauthomas01** [comment]
Hi @thejoshualewis ,

- The dimension is invalid. Please see the [contribution guideline](url)

The "bitpay" currencies icon include 4 icons in 1 file.

- We already have Bitcoin (https://github.com/activemerchant/payment_icons/blob/8049e703143d789b92a1bf7358751a18ce213df6/app/assets/images/payment_icons/bitcoin.svg)
- We already have Bitcoin cash (https://github.com/activemerchant/payment_icons/blob/8049e703143d789b92a1bf7358751a18ce213df6/app/assets/images/payment_icons/bitcoin_cash.svg)
- The dimensions are invalid. It needs a width of 38 and height of 24

[alt](https://screenshot.click/23-44-qoaes-51hxy.png)

**Comment by thejoshualewis** [comment]
Hi @tauthoms01,

This is to replace those icons, and have the 4 as the standard, to show
users the different types accepted.

**Comment by tauthomas01** [comment]
Hi @thejoshualewis,

If that's the case, all 4 icons should be in their own file, not together.

**Comment by tauthomas01** [comment]
Hi @thejoshualewis 

I understand what you're trying to do, but in order to keep consistencies and the rules of this repository, we need to follow the guideline like any other icons.

Here are a few examples that demonstrate what I mean:
https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/eghl.svg
https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/amazon.svg

I can't go forward by simply adding this => https://bitpay.com/cdn/en_US/bitpay-mark-std.svg

**Comment by thejoshualewis** [comment]
So to have the layout with the mark + 4 icons, those all need to be individual?  And Shopify will add all 4 manually instead of 1 link?  Just trying to clarify the right way to do this.

**Comment by tauthomas01** [comment]
Exactly, you'll create 4 individual icons. All instructions are included here: https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons 

Here's the current list of icons, that will give you an idea how it looks like: https://github.com/activemerchant/payment_icons/tree/master/app/assets/images/payment_icons

**Comment by rahilvirani** [comment]
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

**Pull request closed without merging**
