### PR TITLE
PingPongCheckout add new icon for Shopify

### PR DESCRIPTION
**Pull request by pingpongCheckout**
## Why are you adding this icons?
I'm adding/updating this icon(s) because  we are payment provider PingPongCheckout,We provide payment services for merchants on shopify. We found that shopify is missing the icon of the payment method we support

#### Help us identify yourself
- [x ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

image

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Screenshot 2023-02-01 at 8 46 25 AM
Screenshot 2023-02-01 at 8 46 40 AM

Both icons have an issue with the border — because of the paths used the border is split between two colours. You can also simplify the layers in your SVGs to reduce file size. Please fix and resubmit.

**Comment by pingpongCheckout** [comment]
I have removed the border and resubmitted the picture. Please review it again

**Comment by pingpongCheckout** [comment]
I have fixed the above problems, please review again

**Comment by Jacquesattaque** [comment]
@pingpongCheckout Please check again. The SVGs attached to this PR still have the issue.

**Comment by santoso87** [comment]
hi @Jacquesattaque ,

since this PR dont have any progress , can i submit icons for skrill?

**Comment by Jacquesattaque** [comment]
@santoso87 Yup, you can re-open that one!

**Comment by santoso87** [comment]
hi @Jacquesattaque ,

thankyou , i already open PR for Skrill https://github.com/activemerchant/payment_icons/pull/831

**Comment by Jacquesattaque** [comment]
@pingpongCheckout Please remove Skrill from this ticket. It's now part of #831.

**Comment by pingpongCheckout** [comment]
I have updated the icon for mybank and removed the skill icon. Please review again

**Comment by pingpongCheckout** [comment]
> @pingpongCheckout Please remove Skrill from this ticket. It's now part of #831.

I have updated the icon for mybank and removed the skill icon. 
Please review again

thanks

**Comment by Jacquesattaque** [comment]
@pingpongCheckout The icon looks good. If you can resolve the conflicts I can approve.

**Comment by pingpongCheckout** [comment]
> @pingpongCheckout The icon looks good. If you can resolve the conflicts I can approve.

I have resolved the conflict, please review

**Comment by Jacquesattaque** [comment]
@pingpongCheckout Still shows as conflicts on my end.

**Comment by pingpongCheckout** [comment]
> 

Can I create a new branch to handle this problem？

**Comment by pingpongCheckout** [comment]
> @pingpongCheckout Still shows as conflicts on my end.


I have checked again and processed it. Please review it again

**Comment by pingpongCheckout** [comment]
> @pingpongCheckout Still shows as conflicts on my end.
According to the prompts for the test specimen, I have modified the SVG title to mybank. Please review

**Comment by pingpongCheckout** [comment]
> @pingpongCheckout Still shows as conflicts on my end.

These issues have been fixed

**Comment by pingpongCheckout** [comment]
> @pingpongCheckout Still shows as conflicts on my end.

Why can't mybank's icon still be found on Shopify after approving the merger

**Comment by adeniyiao** [comment]
Hi @pingpongCheckout, we are still working through the deployment. We'll let you know once release is done so you can confirm
Regards

**Pull request merged**
