### PR TITLE
Adding new Bread Pay and PayPlan by RBC icons

### PR DESCRIPTION
**Pull request by jefferykeller**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by larouxn — CHANGES_REQUESTED** [review]
Can we shrink the Bread Pay icon a bit? It's nearly off the side.
Screen Shot 2022-08-09 at 12 31 14

**Comment by jefferykeller** [comment]
Hi @larouxn, I shrunk the BreadPay image just a bit as requested.  Thanks for your attention on this one.

**Comment by jefferykeller** [comment]
Hi @larouxn, anything else required on my end before we can push this one through?  Thanks for your help.

**Comment by larouxn** [comment]
👋 @jefferykeller, looks like there are merge conflicts. They will need to be resolved before we can merge. I recommend placing the `db/payment_icons.yml` entries towards the middle of the file.

**Comment by jefferykeller** [comment]
Hi @larouxn, I moved my changes up in the payment_icons.yaml file.  Did that resolve the merge conflict?

**Comment by larouxn** [comment]
> Hi @larouxn, I moved my changes up in the payment_icons.yaml file. Did that resolve the merge conflict?

Yep, that fixed the merge conflicts. Thanks! 🙌

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-08-18 at 11 35 40

Screen Shot 2022-08-18 at 11 37 54

**Review by tauthomas01 — APPROVED** [review]

**Comment by jefferykeller** [comment]
@larouxn / @tauthomas01 , thanks for your approvals. Can one of you please merge this one when you get a chance?  Any idea on when the updates will be included in a release?

**Comment by larouxn** [comment]
> @larouxn / @tauthomas01 , thanks for your approvals. Can one of you please merge this one when you get a chance? Any idea on when the updates will be included in a release?

We just cut a release this week so I would estimate these icons will be live within a few weeks at the earliest. Surely within September at the latest though.

**Comment by jefferykeller** [comment]
Great, thank you for the update!

**Comment by jefferykeller** [comment]
Hi @larouxn / @tauthomas01 , just checking in on this on to see if you have a tentative release date planned for the recent payment icon updates? Our brand partners are asking for an update again. Thanks!!

**Pull request merged**
