### PR TITLE
Fix Swish icon

### PR DESCRIPTION
**Pull request by larouxn**
Rebuilt the Swish icon based on the standard Visa icon by duplicating Visa and replacing the Visa logo with Swish logo.

Screen Shot 2021-11-16 at 13 26 56

Hopefully addresses https://github.com/activemerchant/payment_icons/issues/510 once rolled out.

CC @Azzilx90

### CODE REVIEW

**Review by tauthomas01 — APPROVED** [review]
Thank you for doing this! 👏

**Comment by Azzilx90** [comment]
Thank you!!! 😊

**Comment by larouxn** [comment]
👋 Aiming to release a new version of this gem soon. Hoping to have this fixed icon live by end of next week at the latest.

**Comment by larouxn** [comment]
👋 @Azzilx90, the updated/fixed icon should be available everywhere now. Have a great day! ☀️

**Pull request merged**
