### PR TITLE
Updated SVG icon for Snap finance

### PR DESCRIPTION
**Pull request by smahendiran**
## Why are you adding this icons?
I'm adding/updating this icon(s) because snap finance has updated the company logo.

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: https://developer.snapfinance.com/media/ 
Company website- https://snapfinance.com/

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<svg xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" viewBox="0 0 38 24" aria-labelledby="pi-snap_checkout" xml:space="preserve"><title id="pi-snap_checkout">Snap Checkout</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><g xmlns="http://www.w3.org/2000/svg" transform="scale(0.30)" transform-origin="4 7"><path d="M13.4017 32.7323C11.9064 32.0495 10.7263 31.1227 9.8551 29.9456C8.9839 28.7717 8.52049 27.4587 8.46179 26.0066H13.5963C13.6828 27.0231 14.1679 27.8726 15.0545 28.5523C15.9381 29.2351 17.0503 29.5749 18.3849 29.5749C19.7195 29.5749 20.8564 29.3061 21.6256 28.7686C22.3949 28.231 22.778 27.5421 22.778 26.7018C22.778 25.8027 22.3485 25.1354 21.4928 24.6998C20.637 24.2642 19.2808 23.7854 17.4241 23.2633C15.6261 22.769 14.1617 22.2901 13.0279 21.8267C11.8972 21.3633 10.9178 20.6527 10.0899 19.695C9.26194 18.7373 8.85105 17.4768 8.85105 15.9105C8.85105 14.6346 9.22796 13.4668 9.98177 12.4071C10.7356 11.3474 11.8169 10.5133 13.2225 9.9047C14.6282 9.29609 16.247 8.99023 18.0759 8.99023C20.8039 8.99023 23.0004 9.67917 24.6687 11.057C26.3369 12.4349 27.2298 14.3133 27.3441 16.6921H22.3825C22.296 15.6201 21.8604 14.7643 21.0757 14.1248C20.291 13.4884 19.2345 13.1671 17.8998 13.1671C16.5652 13.1671 15.5921 13.4143 14.897 13.9055C14.2019 14.3998 13.8528 15.0516 13.8528 15.8641C13.8528 16.5037 14.0845 17.0381 14.5479 17.4737C15.0113 17.9093 15.5766 18.2492 16.2439 18.4963C16.9112 18.7435 17.8968 19.0555 19.2036 19.4324C20.9429 19.8958 22.3733 20.3685 23.4916 20.8474C24.6069 21.3262 25.5739 22.0306 26.3864 22.9574C27.1989 23.8873 27.619 25.12 27.6468 26.6554C27.6468 28.0209 27.2699 29.2382 26.5161 30.3102C25.7623 31.3822 24.6965 32.2256 23.3186 32.8342C21.9407 33.4428 20.3219 33.7487 18.4652 33.7487C16.6085 33.7487 14.8908 33.4088 13.3955 32.7261L13.4017 32.7323Z" fill="#062D4E"/><path d="M47.4745 10.1705C48.9666 10.9552 50.1344 12.1137 50.9778 13.6522C51.8181 15.1907 52.2383 17.0475 52.2383 19.2224V33.3657H47.32V19.9639C47.32 17.8167 46.7825 16.1701 45.7104 15.0239C44.6384 13.8777 43.171 13.3062 41.3143 13.3062C39.4575 13.3062 37.9839 13.8808 36.8964 15.0239C35.809 16.1701 35.2653 17.8167 35.2653 19.9639V33.3657H30.3037V9.38576H35.2653V12.1291C36.0778 11.1436 37.1158 10.3744 38.3763 9.82137C39.6367 9.27145 40.9806 8.99341 42.4017 8.99341C44.2862 8.99341 45.9761 9.38576 47.4714 10.1674L47.4745 10.1705Z" fill="#062D4E"/><path d="M56.3533 14.8694C57.3543 13.0127 58.7167 11.57 60.4436 10.5381C62.1706 9.50934 64.0767 8.99341 66.1652 8.99341C68.0497 8.99341 69.6963 9.36414 71.1051 10.1025C72.5107 10.844 73.6353 11.7646 74.4787 12.8675V9.38576H79.4835V33.3626H74.4787V29.7943C73.6384 30.9251 72.4922 31.8673 71.0402 32.6242C69.5882 33.378 67.9354 33.7549 66.0787 33.7549C64.018 33.7549 62.1335 33.2267 60.422 32.167C58.7105 31.1073 57.3543 29.6275 56.3533 27.7275C55.3523 25.8275 54.8519 23.6742 54.8519 21.2645C54.8519 18.8548 55.3523 16.7231 56.3533 14.8664V14.8694ZM73.4561 17.0444C72.7733 15.8272 71.8836 14.8973 70.7807 14.2577C69.6778 13.6213 68.4884 13.3 67.2125 13.3C65.9366 13.3 64.7471 13.6121 63.6442 14.2361C62.5413 14.8602 61.6485 15.7746 60.9688 16.9764C60.2861 18.1813 59.9462 19.6086 59.9462 21.2645C59.9462 22.9204 60.2861 24.3693 60.9688 25.6175C61.6516 26.8656 62.5506 27.814 63.6659 28.469C64.7811 29.1208 65.9644 29.4483 67.2125 29.4483C68.4606 29.4483 69.6778 29.1301 70.7807 28.4906C71.8836 27.8542 72.7764 26.9181 73.4561 25.6854C74.1389 24.4528 74.4787 23.01 74.4787 21.3541C74.4787 19.6982 74.1358 18.2647 73.4561 17.0475V17.0444Z" fill="#062D4E"/><path d="M91.6216 10.1241C93.0706 9.37031 94.711 8.99341 96.5399 8.99341C98.6283 8.99341 100.534 9.50934 102.261 10.5381C103.988 11.5669 105.345 13.0127 106.33 14.8694C107.316 16.7262 107.81 18.8579 107.81 21.2676C107.81 23.6773 107.316 25.8306 106.33 27.7306C105.345 29.6306 103.988 31.1104 102.261 32.1701C100.534 33.2297 98.6283 33.758 96.5399 33.758C94.711 33.758 93.086 33.3873 91.6649 32.6489C90.2438 31.9106 89.0822 30.9899 88.1832 29.887V44.7687H83.2216V9.38576H88.1832V12.9108C89.0235 11.8079 90.1696 10.881 91.6216 10.1272V10.1241ZM101.739 16.9764C101.057 15.7716 100.158 14.8602 99.0423 14.2361C97.924 13.6121 96.7284 13.3 95.4525 13.3C94.1765 13.3 93.0211 13.6182 91.9059 14.2577C90.7875 14.8973 89.8885 15.8241 89.2088 17.0444C88.5261 18.2616 88.1862 19.6982 88.1862 21.351C88.1862 23.0038 88.5261 24.4497 89.2088 25.6823C89.8916 26.915 90.7906 27.8511 91.9059 28.4875C93.0211 29.127 94.2044 29.4452 95.4525 29.4452C96.7006 29.4452 97.924 29.1178 99.0423 28.4659C100.158 27.814 101.06 26.8625 101.739 25.6144C102.422 24.3663 102.762 22.9173 102.762 21.2614C102.762 19.6055 102.422 18.1782 101.739 16.9733V16.9764Z" fill="#062D4E"/><path d="M9.19715 8.95291C10.0776 8.95291 10.7913 8.23919 10.7913 7.35878C10.7913 6.47836 10.0776 5.76465 9.19715 5.76465C8.31674 5.76465 7.60303 6.47836 7.60303 7.35878C7.60303 8.23919 8.31674 8.95291 9.19715 8.95291Z" fill="#1B844A"/><path d="M3.10173 17.9865C2.57654 17.9618 2.08224 17.6467 1.85362 17.1307C1.52924 16.4016 1.85671 15.552 2.5858 15.2277L4.4765 14.3873C5.2056 14.066 6.05517 14.3904 6.37956 15.1195C6.70394 15.8486 6.37647 16.6982 5.64738 17.0226L3.75668 17.8629C3.54351 17.9587 3.32108 17.9958 3.10173 17.9865Z" fill="#062D4E"/><path d="M13.8528 7.13346C13.7879 7.13037 13.7261 7.12419 13.6613 7.11183C12.8796 6.96663 12.3606 6.2159 12.5027 5.43429L13.238 1.42425C13.3801 0.639538 14.1339 0.123609 14.9155 0.265721C15.6972 0.410923 16.2162 1.16165 16.0741 1.94326L15.3388 5.95331C15.2059 6.67314 14.5634 7.16744 13.8528 7.13346Z" fill="#FFCA4D"/><path d="M6.1108 12.478C5.95633 12.4718 5.79877 12.4378 5.6443 12.376L0.905198 10.476C0.166837 10.1794 -0.191531 9.33913 0.10196 8.60076C0.39854 7.86239 1.23576 7.50402 1.97721 7.79752L6.71632 9.6975C7.45468 9.99408 7.81305 10.8344 7.51956 11.5728C7.28476 12.1597 6.70705 12.5058 6.1108 12.478Z" fill="#3D5CCF"/><path d="M6.46606 5.28896C6.03664 5.26734 5.62266 5.05726 5.35697 4.67726L3.664 2.27062C3.20677 1.61876 3.36124 0.719742 4.0131 0.262511C4.66495 -0.194721 5.56396 -0.0371611 6.02119 0.611613L7.71417 3.01826C8.1714 3.67012 8.01693 4.56913 7.36507 5.02636C7.0932 5.21791 6.775 5.30132 6.46606 5.28587V5.28896Z" fill="#1B844A"/><path d="M20.7173 41.7812H19.3673V47.8828H16.8587V41.7812H15.9504V39.699H16.8587V39.4642C16.8587 38.457 17.146 37.6908 17.7237 37.1687C18.3015 36.6466 19.1449 36.384 20.2601 36.384C20.4455 36.384 20.5814 36.3902 20.671 36.3995V38.525C20.1922 38.4941 19.8554 38.5652 19.6577 38.7289C19.4631 38.8957 19.3642 39.1923 19.3642 39.6248V39.699H20.7143V41.7812H20.7173Z" fill="#1B844A"/><path d="M23.6275 38.4569C23.3495 38.1974 23.2104 37.8761 23.2104 37.4961C23.2104 37.1161 23.3495 36.7794 23.6275 36.5199C23.9056 36.2604 24.267 36.1306 24.7057 36.1306C25.1444 36.1306 25.4904 36.2604 25.7685 36.5199C26.0465 36.7794 26.1855 37.1038 26.1855 37.4961C26.1855 37.8885 26.0465 38.1974 25.7685 38.4569C25.4904 38.7164 25.1351 38.8462 24.7057 38.8462C24.2763 38.8462 23.9056 38.7164 23.6275 38.4569ZM25.9538 39.6958V47.8796H23.4452V39.6958H25.9538Z" fill="#1B844A"/><path d="M36.226 40.5422C36.7975 41.1632 37.0848 42.0159 37.0848 43.1033V47.8857H34.5917V43.4432C34.5917 42.8963 34.4496 42.47 34.1654 42.1672C33.8812 41.8645 33.5012 41.7131 33.0223 41.7131C32.5435 41.7131 32.1604 41.8645 31.8792 42.1672C31.595 42.47 31.4529 42.8963 31.4529 43.4432V47.8857H28.9443V39.7019H31.4529V40.7863C31.7062 40.4248 32.0492 40.1375 32.4786 39.9274C32.908 39.7173 33.393 39.6123 33.9306 39.6123C34.8883 39.6123 35.6545 39.9212 36.226 40.5422Z" fill="#1B844A"/><path d="M39.8499 41.5618C40.1681 40.9254 40.6006 40.4373 41.1474 40.0944C41.6942 39.7515 42.3059 39.5815 42.9794 39.5815C43.5571 39.5815 44.0638 39.6989 44.4963 39.9337C44.9288 40.1685 45.2656 40.4775 45.5004 40.8575V39.6989H48.0089V47.8828H45.5004V46.7242C45.2563 47.1042 44.9165 47.4132 44.4809 47.648C44.0453 47.8828 43.5386 48.0002 42.964 48.0002C42.2998 48.0002 41.6912 47.8271 41.1443 47.478C40.5975 47.132 40.165 46.6377 39.8468 45.9982C39.5286 45.3587 39.371 44.6173 39.371 43.7769C39.371 42.9366 39.5286 42.1983 39.8468 41.5618H39.8499ZM44.9844 42.3095C44.6384 41.948 44.2152 41.7658 43.7147 41.7658C43.2142 41.7658 42.7941 41.9449 42.445 42.3002C42.099 42.6586 41.9229 43.1498 41.9229 43.7739C41.9229 44.3979 42.0959 44.8953 42.445 45.2629C42.791 45.6306 43.2142 45.8129 43.7147 45.8129C44.2152 45.8129 44.6353 45.6337 44.9844 45.2691C45.3335 44.9046 45.5065 44.4134 45.5065 43.7893C45.5065 43.1652 45.3335 42.6709 44.9844 42.3064V42.3095Z" fill="#1B844A"/><path d="M58.1853 40.5422C58.7569 41.1632 59.0442 42.0159 59.0442 43.1033V47.8857H56.5511V43.4432C56.5511 42.8963 56.409 42.47 56.1247 42.1672C55.8405 41.8645 55.4605 41.7131 54.9817 41.7131C54.5028 41.7131 54.1197 41.8645 53.8386 42.1672C53.5544 42.47 53.4123 42.8963 53.4123 43.4432V47.8857H50.9037V39.7019H53.4123V40.7863C53.6656 40.4248 54.0085 40.1375 54.4379 39.9274C54.8674 39.7173 55.3524 39.6123 55.8899 39.6123C56.8476 39.6123 57.6138 39.9212 58.1853 40.5422Z" fill="#1B844A"/><path d="M61.8493 41.5618C62.1953 40.9254 62.6803 40.4373 63.3013 40.0944C63.9223 39.7515 64.6328 39.5815 65.4361 39.5815C66.4617 39.5815 67.3206 39.8503 68.0095 40.3879C68.6984 40.9254 69.1495 41.6823 69.3657 42.6617H66.6965C66.471 42.0345 66.0354 41.7225 65.3928 41.7225C64.9325 41.7225 64.5649 41.9017 64.293 42.257C64.018 42.6153 63.8821 43.1251 63.8821 43.7893C63.8821 44.4535 64.018 44.9664 64.293 45.3216C64.5649 45.68 64.9325 45.8561 65.3928 45.8561C66.0385 45.8561 66.4741 45.5441 66.6965 44.9169H69.3657C69.1495 45.8746 68.6954 46.6285 68.0002 47.1753C67.3051 47.7221 66.4494 47.9971 65.433 47.9971C64.6297 47.9971 63.9192 47.8271 63.2982 47.4842C62.6772 47.1413 62.1922 46.6532 61.8462 46.0168C61.5002 45.3803 61.3241 44.6389 61.3241 43.7862C61.3241 42.9335 61.4971 42.1921 61.8462 41.5557L61.8493 41.5618Z" fill="#1B844A"/><path d="M79.5762 44.3917H73.901C73.9412 44.9015 74.1049 45.2877 74.3922 45.5564C74.6795 45.8252 75.0348 45.9612 75.455 45.9612C76.079 45.9612 76.5146 45.6986 76.7587 45.1703H79.4279C79.292 45.7078 79.0448 46.1929 78.6864 46.6223C78.3281 47.0517 77.8832 47.3915 77.3457 47.6356C76.8081 47.8797 76.2057 48.0033 75.5415 48.0033C74.7382 48.0033 74.0246 47.8333 73.4005 47.4904C72.7734 47.1475 72.2853 46.6594 71.9331 46.0229C71.5809 45.3865 71.4048 44.6451 71.4048 43.7924C71.4048 42.9397 71.5778 42.1983 71.9269 41.5618C72.2729 40.9254 72.761 40.4373 73.3851 40.0944C74.0091 39.7515 74.729 39.5815 75.5415 39.5815C76.354 39.5815 77.0367 39.7484 77.6546 40.0789C78.2725 40.4095 78.7513 40.8853 79.1004 41.5032C79.4464 42.1179 79.6225 42.8378 79.6225 43.6596C79.6225 43.8943 79.6071 44.1384 79.5793 44.3917H79.5762ZM77.0522 42.9984C77.0522 42.569 76.9039 42.2261 76.6135 41.9727C76.32 41.7194 75.9523 41.5927 75.5137 41.5927C75.075 41.5927 74.7382 41.7163 74.4509 41.9604C74.1636 42.2044 73.9844 42.5535 73.9164 43.0015H77.0553L77.0522 42.9984Z" fill="#1B844A"/></g></svg>
</br>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name) 
Snap finance has a Snap finance checkout payment public app ( https://apps.shopify.com/snap-checkout ) . Due to changes in the company logo we need to update in Shopify plugins as well. I'm working as a Shopify app developer.

What's the expected date of this change to deploy on Shopify? Immediate/High Priority

### CODE REVIEW

**Comment by smahendiran** [comment]
@Jacquesattaque Can you review the PR and merge?

**Comment by Jacquesattaque** [comment]
@smahendiran The file size is far too large here. Make sure you use SVGO to compress, and simplify the illustration if you need to. You've also got conflicts you have to resolve.

**Comment by smahendiran** [comment]
@Jacquesattaque Thanks for the reply. 
I have compressed the svg file using the SVGO and resolved the conflicts as well. 
Thanks.

**Comment by smahendiran** [comment]
@Jacquesattaque It seems the checks failed because of ruby version issue. Kindly help me resolve the issue please.

**Comment by hellicarusprime** [comment]
Hi @smahendiran I'm standing in for @Jacquesattaque at the moment. The file size looks good now, but the icon overlaps the border. Can you adjust it so it's contained? It also looks like you've got a few issues with the "Leasing" text.
image

**Comment by hellicarusprime** [comment]
@adeniyiao Can you help with the failing checks here?

**Comment by adeniyiao** [comment]
Hi @smahendiran , we addressed the ruby version issue, but we need you to rebase your branch `smahendiran:snap_checkout_new_icon` with `activemerchant/master` as well. Thanks

**Comment by smahendiran** [comment]
> Hi @smahendiran , we addressed the ruby version issue, but we need you to rebase your branch `smahendiran:snap_checkout_new_icon` with `activemerchant/master` as well. Thanks

Thanks @adeniyiao I have synced my branch with `activemerchant/master` branch.

**Comment by hellicarusprime** [comment]
> Hi @smahendiran I'm standing in for @Jacquesattaque at the moment. The file size looks good now, but the icon overlaps the border. Can you adjust it so it's contained? It also looks like you've got a few issues with the "Leasing" text. image

Hi @smahendiran Can you please address the issues raised here?

**Comment by smahendiran** [comment]
> > Hi @smahendiran I'm standing in for @Jacquesattaque at the moment. The file size looks good now, but the icon overlaps the border. Can you adjust it so it's contained? It also looks like you've got a few issues with the "Leasing" text. image
> 
> Hi @smahendiran Can you please address the issues raised here?

@hellicarusprime we have addressed these issues. Can you review and approve the PR. Thanks.

**Comment by smahendiran** [comment]
@hellicarusprime Any update on the Pull Request approval. We have resolved the issues 2 week back. Please help us on the PR approval if everything is looking fine.
Thanks

**Pull request merged**
