### PR TITLE
Add ADA icon to cryptocurrencies

### PR DESCRIPTION
**Pull request by ivanmanyus-b2m**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [X] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
Bit2Me Commerce and Cardano Foundation.

What's the expected date of this change to deploy on Shopify? As soon as possible :)

### CODE REVIEW

**Comment by ivanmanyus-b2m** [comment]
Hey @Jacquesattaque can you check this? Still pending of approval for several days:) ...Thanks!

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
@ivanmanyus-b2m Just resolve the conflicts and we'll approve.

**Comment by ivanmanyus-b2m** [comment]
Done! @Jacquesattaque

**Review by Jacquesattaque — APPROVED** [review]

**Comment by ivanmanyus-b2m** [comment]
Hi guys @Jacquesattaque @adeniyiao @dannye0231 , Happy new year!
Could I know a deadline to be able to include this payment icon in my official Shopify plugin?

Thanks in advance :))

**Comment by adeniyiao** [comment]
Hi @ivanmanyus-b2m , we recently addressed a ruby version issue causing the test failure with this PR , therefore we need you to rebase your branch `ivanmanyus-b2m:crypto_ada_icon` with `activemerchant/master ` to fix the CI failure. Thanks.
We plan to release by mid-next week.

**Comment by ivanmanyus-b2m** [comment]
Hi @adeniyiao, that's all? Is ready to deploy? :)

**Pull request merged**
