### PR TITLE
Using generic cash icon for gokwik cash on delivery method

### PR DESCRIPTION
**Pull request by kalpitrathore1**
## Why are you adding this icons?
I’m adding this icon(s) because we at [GoKwik](https://www.gokwik.co/) are offering Cash on Delivery as a payment method and for that the icon is missing and we want to use it for our payment app that provides “Cash on Delivery” as a payment method.

#### Help us identify yourself
- [x]  I’m associated with the brand and I’ve read all the brand icon’s guidelines.

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-cash" width="38" height="24" role="img"><title id="pi-cash">Cash</title><path fill="#98C74C" d="M38 21a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3h32a3 3 0 0 1 3 3v18z"/><circle opacity=".2" cx="19" cy="12" r="8"/><circle opacity=".2" cx="32" cy="12" r="2"/><circle opacity=".2" cx="6" cy="12" r="2"/><path fill="#fff" d="M22.113 13.897c0-1.573-1.271-2.067-2.518-2.42V8.763c.65.118 1.218.588 1.68 1.105l.71-.797c-.578-.609-1.424-1.128-2.39-1.246V6.83h-1.034v.973c-1.408.154-2.413 1.036-2.413 2.275 0 1.461 1.2 1.907 2.413 2.244v3.024c-.898-.145-1.608-.759-2.053-1.277l-.62.945c.597.673 1.504 1.151 2.674 1.266v.89h1.034v-.881c1.819-.186 2.517-1.304 2.517-2.392zm-4.974-3.948c0-.684.627-1.11 1.422-1.223v2.459c-.797-.133-1.422-.596-1.422-1.236zm2.456 5.426v-2.762c.813.254 1.451.59 1.451 1.359 0 .565-.364 1.246-1.451 1.403z"/></svg>

<br>
<!-- TODO: insert your icon here -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-cash" width="38" height="24" role="img"><title id="pi-cash">Cash</title><path fill="#98C74C" d="M38 21a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3h32a3 3 0 0 1 3 3v18z"/><circle opacity=".2" cx="19" cy="12" r="8"/><circle opacity=".2" cx="32" cy="12" r="2"/><circle opacity=".2" cx="6" cy="12" r="2"/><path fill="#fff" d="M22.113 13.897c0-1.573-1.271-2.067-2.518-2.42V8.763c.65.118 1.218.588 1.68 1.105l.71-.797c-.578-.609-1.424-1.128-2.39-1.246V6.83h-1.034v.973c-1.408.154-2.413 1.036-2.413 2.275 0 1.461 1.2 1.907 2.413 2.244v3.024c-.898-.145-1.608-.759-2.053-1.277l-.62.945c.597.673 1.504 1.151 2.674 1.266v.89h1.034v-.881c1.819-.186 2.517-1.304 2.517-2.392zm-4.974-3.948c0-.684.627-1.11 1.422-1.223v2.459c-.797-.133-1.422-.596-1.422-1.236zm2.456 5.426v-2.762c.813.254 1.451.59 1.451 1.359 0 .565-.364 1.246-1.451 1.403z"/></svg>
</br>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
@kalpitrathore1 I don't think this PR is necessary. This icon already exists and you should be able to use it in your app.

**Comment by garvitburad** [comment]
@Jacquesattaque We are not able to find the "Cash" method with it's icon listed payment method in the Offsite payment provider extension. Need this to create a payments app. 
Screenshot 2023-04-06 at 11 17 58 AM (1)

**Comment by Jacquesattaque** [comment]
@adeniyiao This may be a bigger issue, but is there a way to expose Cash here as a payment method? We already have an icon so I'm surprised it's not here.

**Comment by garvitburad** [comment]
@Jacquesattaque we think if you merge the changes suggested in the db/payment_icons.yml file then the icon will be displayed. @adeniyiao would love hear your opinion on this as well to fast track the request

**Comment by adeniyiao** [comment]
Hi @Jacquesattaque , though we have the cash icon, since the name and label is not in the `payment_icon.yml` file, I think it's likely we need this PR to be included in the next release.

**Comment by Jacquesattaque** [comment]
Cool let's do it then. @adeniyiao Do we need the icon added to this PR or just the name and label?

**Comment by adeniyiao** [comment]
Just the name and label. We should be able to use the existing [cash.svg](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/cash.svg) icon as I don't see it been used anywhere downstream.

**Comment by Jacquesattaque** [comment]
OK cool, I can approve once conflicts are resolved.

**Comment by kalpitrathore1** [comment]
Hey @Jacquesattaque I've made the changes suggested by workflow. Can you please check and approve the PR?

**Comment by kalpitrathore1** [comment]
Hey @Jacquesattaque, what is the expected merge date so that I can convey the same to the management. I would appreciate it if you could merge this PR as soon as possible. It's a blocker for our product launch.

**Comment by adeniyiao** [comment]
Hi @kalpitrathore1 , the next release is scheduled for next Wednesday, May 3rd.

**Comment by garvitburad** [comment]
HI @adeniyiao, I hope we are on track for the release on May 3rd and there are no blockers. Please let me know if you have any updates or questions.

**Comment by garvitburad** [comment]
Hi @adeniyiao thanks for release. I am still not able to select the "Cash" method in the Payment extension.
Screenshot 2023-05-03 at 8 53 49 PM
 Can you please check this on priority why this is not visible. Attaching the screenshot.

**Comment by adeniyiao** [comment]
Hi @garvitburad , we are still working through the deployment and I'll let you know as soon as all done.

**Comment by adeniyiao** [comment]
Hi @garvitburad icon is now deployed.

**Pull request merged**
