### PR TITLE
add TipTop payment method icon

### PR DESCRIPTION
**Pull request by ryantiptop**
## Why are you adding this icons?
I'm adding this icon because TipTop is a new payment method for Shopify stores and we want this icon featured when customers choose to pay with TipTop

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: N/A - see tiptop.com for information about our product. We also have an app in the iOS App Store.

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
visa_vs_tiptop

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
- Meghan Donaldson

What's the expected date of this change to deploy on Shopify?
- TipTop payments app was submitted for review on April 3, 2024. We are ready to go live once approved.

### CODE REVIEW

**Comment by hellicarusprime** [comment]
Hi @ryantiptop—could you please add a visible border to the icon? See our [contributing guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance).

**Comment by ryantiptop** [comment]
Hi @hellicarusprime. I added a border according to the guidelines and attached an updated screenshot. Ready for review again! Thanks.

**Comment by hellicarusprime** [comment]
Hi @ryantiptop—you're border radius isn't correct. 

`The border must have a 2px radius`

**Comment by ryantiptop** [comment]
Screenshot 2024-04-12 at 8 14 49 AM

@hellicarusprime the outer border does have a 2px radius. Here's a screenshot from Figma.

**Comment by ryantiptop** [comment]
@hellicarusprime thank you for the clarification. I updated our icon with the correct outer stroke and provided a new screenshot. thank you.

**Review by Lovedanihonjin — CHANGES_REQUESTED** [review]
Thanks for the update! It's looking great. Would mind outlining/expanding the stroke like the below image. Thank you!
Screenshot 2024-05-01 at 8 43 20 PM

**Comment by ryantiptop** [comment]
Screenshot 2024-05-02 at 12 45 01 AM

Hi @Lovedanihonjin. I think the new changes should satisfy your request. thank you.

**Comment by ryantiptop** [comment]
Hi, @hellicarusprime and @Lovedanihonjin. This is ready for re-review. Thank you!

**Comment by ryantiptop** [comment]
Hi, @hellicarusprime and @Lovedanihonjin, kindly bumping this PR to get it reviewed again. Our payment app was approved by Shopify today.

**Review by Lovedanihonjin — APPROVED** [review]
Looks great! Next deploy is on June 5.

**Pull request merged**
