### PR TITLE
Klarna single icon

### PR DESCRIPTION
**Pull request by kristibarbosky**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by kristibarbosky** [comment]
svgo

**Comment by kristibarbosky** [comment]
@tauthomas01  - Happy belated Canada Day!  As Klarna has informed merchants on June 28th of this upcoming badge icon update (moving from 3 Klarna badges previously with sunglasses, peace sign, and pizza) to a single Klarna badge), as time permits, could you (or the appropriate person) please review this PR so that we can update our Klarna gateways to use this new badge?  Thanks!

**Comment by kristibarbosky** [comment]
Thank you much @tauthomas01! can you provide a timeframe when this update will be available with the Shopify partner dashboard (so I can update the badges for our gateways)?

**Comment by tauthomas01** [comment]
@kristibarbosky I'm planning to make the release this afternoon so the update will be available at most tomorrow.

**Comment by kristibarbosky** [comment]
Thank you @tauthomas01 !

**Comment by kristibarbosky** [comment]
@tauthomas01  - I'm not yet seeing the new icon in the Shopify partner dashboard yet today.  Can you let me know if there is an updated ETA on the release?  or if I'm missing something?  thank you!

**Comment by tauthomas01** [comment]
Hi @kristibarbosky, I wasn't aware about updating the icons in the partner dashboard. I just found how to make the change and will let you know once it's done.

Sorry for the delay.

**Comment by kristibarbosky** [comment]
Great, thanks for the update @tauthomas01 !

**Comment by tauthomas01** [comment]
@kristibarbosky The changes should be seen anytime soon today.
Let me know if you see it.

**Comment by kristibarbosky** [comment]
Thanks @tauthomas01  - I see it now.  
image

**Comment by kristibarbosky** [comment]
While the icon is showing up in the Shopify partner dashboard, it isn't yet working on the Shopify storefront.  I will retest again later today as well in case it is a propagation/timing issue.  
image

**Comment by kristibarbosky** [comment]
@tauthomas01  - the new badge is not yet displaying on the storefront today; can you help please?  thank you!

**Comment by tauthomas01** [comment]
@kristibarbosky - there are some deploying issues on our end. I'll keep you posted once it's online.
Thank you

**Comment by tauthomas01** [comment]
The update should now be live (or in the next few hours).
Let me know if you see it.

**Comment by kristibarbosky** [comment]
Not seeing it yet, but I'll keep checking, thanks!

**Comment by kristibarbosky** [comment]
Thanks @tauthomas01  - I've updated our 15 public gateways today with the new icon, and all is looking good!

**Comment by tauthomas01** [comment]
Thank you for letting me know @kristibarbosky !

**Comment by kristibarbosky** [comment]
Hi again @tauthomas01  -
Today the new Klarna icon is not displaying for some stores; per my testing so far it seems to not work on US stores, but does work on EU stores.  Can you please check?  You can see the issue live at https://klarnastore.myshopify.com
image

**Comment by kristibarbosky** [comment]
https://klarnastore.myshopify.com is again working for me (after forcing a refresh cache in my browser), but not working for a co-worker in Europe at https://klarnastore.myshopify.com (but is working at https://nathan-klarna.myshopify.com)

**Comment by tauthomas01** [comment]
Hi @kristibarbosky ,

I just to clarify that the issue you are talking about refers to the checkout page. At this stage, the problem is not related to `payment_icons` repo anymore I am not be the best person to answer your question.

Have you asked your co-worker in Europe to force refresh cache?
On my end, it displays fine.

nathan-klarna
image

klarna-demo-store
image

**Pull request merged**
