### PR TITLE
added vipps payment icon

### PR DESCRIPTION
**Pull request by martinstougaard**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand

If this pull request is not adding new icons, you can remove this checklist.

Fixes: https://github.com/activemerchant/payment_icons/issues/128

### CODE REVIEW

**Comment by martinstougaard** [comment]
Apologies @NathanPJF it has now been changed.

**Comment by martinstougaard** [comment]
Hi @NathanPJF the changes have been made. Is there anything else you need me to do?

**Comment by NathanPJF** [comment]
Hi, @martinstougaard 

Thanks for making the change; however, the icon still does not meet the contributing guidelines.  Namely, it doesn't have a visible border or the required border radius.

https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance

> Icons have a visible border to give them a consistent shape on pages whose backgrounds match that of the icon.
> * Whenever possible, the border should be black with a 0.07% opacity.
> * The border width must be 1px (pixel) thick.
> * The border must have a 2px radius (outside stroke).

I put this SVG on a `pink` background to help show the issues.

**Comment by simonbognoe** [comment]
I've created a new pull request with the correct version of the Vipps mark: https://github.com/activemerchant/payment_icons/pull/146

Best regards, Simon from Vipps ✌🏻

**Comment by NathanPJF** [comment]
Closing this in favour of https://github.com/activemerchant/payment_icons/pull/146

**Pull request closed without merging**
