### PR TITLE
add hyperpay's methods icons

### PR DESCRIPTION
**Pull request by ahmada3mar**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: 

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
@ahmada3mar Thanks for submitting — these mostly look great. You have some automated checks failing and the Cliq logo has some noise in it. You'll have to take a look and see why it's rendering the Q this way, but I would remove all the little marks on either side. They aren't visible at the icon size and they are adding to the file size. 
Screenshot 2022-12-13 at 8 40 04 AM

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
@ahmada3mar Thanks for submitting — these mostly look great. You have some automated checks failing and the Cliq logo has some noise in it. You'll have to take a look and see why it's rendering the Q this way, but I would remove all the little marks on either side. They aren't visible at the icon size and they are adding to the file size. 
Screenshot 2022-12-13 at 8 40 04 AM

**Comment by ahmada3mar** [comment]
Hello @Jacquesattaque, thanks for your note. 
you're right it's would be better to remove the little marks on ether sides. we made the changes that you're requests and ready to re-review again.

**Comment by Jacquesattaque** [comment]
Logo update looks good! Just look into why the automated checks are failing and I'll approve.

**Comment by ahmada3mar** [comment]
@Jacquesattaque  can you check please ?

**Review by Jacquesattaque — APPROVED** [review]

**Comment by ahmada3mar** [comment]
@lunataoo When will this PR be merged ?

**Pull request merged**
