### PR TITLE
Add convenience stores

### PR DESCRIPTION
**Pull request by rramsden**
This pull request adds [popular](https://en.wikipedia.org/wiki/List_of_convenience_stores) convenience store logos. Convenience store settlement is a popular payment method used throughout Asia.

I've included the logos in category `convience_stores`.

image

### CODE REVIEW

**Comment by mwwang** [comment]
I've seen some merchants show a few top chains (7-11, familymart, Lawson's). That something worth considering?  Good opp for brand association.

**Comment by rramsden** [comment]
@mwwang That's a better idea actually. I'll add logos for the top 3 chains. I'll also include this generic one.

**Comment by rramsden** [comment]
Hi @AnthonyClark thanks for the review. I've updated the README to include the new group.
Also, I've added an additional logo. Could you please take a look at the commit?

**Comment by rramsden** [comment]
@AnthonyClark added, please take a look :bow:

**Comment by SebastianSzturo** [comment]
@rramsden Can you also rebase to resolve the merge conflicts? 🙏

**Comment by rramsden** [comment]
@SebastianSzturo rebased now, thanks.

**Comment by AnthonyClark** [comment]
Thanks for such quick updates @rramsden !

**Pull request merged**
