### PR TITLE
Malaysia (Direct Debit) Bank Icons

### PR DESCRIPTION
**Pull request by jawad-eGHL**
** Checklist **
- [✓] All icons have a corresponding entry in `db/payment_icons.yml`
- [✓] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [✓] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [✓] I am confident that all icons are clear and easy to read/understand
- [✓] I have provided a link to the brand icon’s brand guidelines whenever possible.

https://www.affinbank.com.my/
https://www.allianceonline.com.my/personal/login/login.do
https://www.ambank.com.my/eng/
https://www.bankislam.biz/
https://www.i-muamalat.com.my/rib/index.do
http://www.bankrakyat.com.my/
https://www.mybsn.com.my/
https://www.cimbclicks.com.my/clicks/#/
https://www.db.com/company/index.htm
https://s.hongleongconnect.my/rib/app/fo/login
https://www.hsbc.com.my/ways-to-bank/online-banking/
https://www.kfh.com.my/malaysia/personal.html
https://www.maybank2u.com.my/home/m2u/common/login.do
https://www.ocbc.com.my/group/group-home.html
https://www.pbebank.com/
https://logon.rhb.com.my/
https://www.sc.com/my/

### CODE REVIEW

**Comment by jhumayun** [comment]
@tauthomas01 I have added some Bank Icons that operate in Malaysia. Please review.

**Comment by jhumayun** [comment]
HI @tauthomas01 ,
Following up on this PR. Can you please escalate on this review? Still, this PR has no assignee.

**Review by tauthomas01 — APPROVED** [review]
Hi @jhumayun,

Sorry for the delay, there were a lot of icons to review. Everything looks good.

**Comment by jhumayun** [comment]
Hi @tauthomas01 , thanks for the review and merge. However, the icons are still not available when through the partner account. By when these icons will be available?

**Comment by alfredkho** [comment]
Hello @tauthomas01, we would like to follow up on the estimate timeline for the logo to available on the partner account.

**Comment by tauthomas01** [comment]
Hi @alfredkho @jhumayun , the logo will be available next week. It's in deployment process.

**Comment by alfredkho** [comment]
@tauthomas01 Thanks for your update. Please do keep us inform once it is deployed.

**Comment by alfredkho** [comment]
Hi @tauthomas01 would like to follow up on the status for this. 

In addition, we did encounter some logo where it was made available on our partner account, however it is not appearing on merchant side. Could you advise on this? 

Screenshot from Merchant account
image (1)
Screenshot from eGHL Partner account
image

**Comment by tauthomas01** [comment]
Hi @alfredkho , the new icons was just updated today.

As for the issue you're encountering, I'll have to double check and see if we're missing icons. Some of the deployment steps require manual labor so it's possible that some icons are missing.

**Comment by alfredkho** [comment]
Hi @tauthomas01 Thanks for update on the new icons, I have checked and confirmed that they are appearing on both eGHL partners account and Merchant account. 

Will be waiting for your further update on the missing icons for the rest of the logo available on eGHL partner account.

**Comment by tauthomas01** [comment]
@alfredkho : it seems like there is a list of icons that didn't go through on the merchant side. Me and @larouxn will go check the list and see which one is missing, but I can't promise you that we'll get this done this in a short time, mainly as this project isn't in our top priority and also black friday/cyber monday is coming so deployment will be on paused.

**Comment by alfredkho** [comment]
Hi, @tauthomas01 Thanks for the update. Do we have any estimate timeline?
Beside this, can an exception be made to allow "eNETS" icon only on Merchant account first?

**Comment by larouxn** [comment]
> Beside this, can an exception be made to allow "eNETS" icon only on Merchant account first?

👋  Hey @alfredkho, does this mean prioritize supporting eNETS icon? [payment_icons/enets.svg](https://github.com/activemerchant/payment_icons/blob/f33d706debd8027ebc38b0a312cc20694a08a910/app/assets/images/payment_icons/enets.svg)?

**Comment by alfredkho** [comment]
Hi @larouxn Yes, correct. we would like to have this eNETS logo to be prioritised as our merchant had eNETS, but complaining that it was not shown on the checkout page.

**Comment by larouxn** [comment]
@alfredkho, understood. As @tauthomas01 mentioned, due to it being Black Friday Cyber Monday this week a fix won't likely be going out until at least Tuesday, December 1st. Regardless, will update here when support is ready. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hey @alfredkho, eNETS icon should now be functioning properly. Thank you for waiting.

**Comment by alfredkho** [comment]
Hi @larouxn Thanks for your quick action and assistance. Checked and saw that it appeared on merchant account now. 
As for the checking and fixes of the other missing icons on merchant side, we can wait till the Black Friday Cyber Monday end.

**Comment by handzalah94** [comment]
Hi @larouxn , may I know if GrabpayPH and MCash eWallet is now available in Shopify payment?
shopify payment logo

**Comment by larouxn** [comment]
👋 Hey @handzalah94, is "GrabpayPH" [grabpay.svg](https://github.com/activemerchant/payment_icons/blob/f33d706debd8027ebc38b0a312cc20694a08a910/app/assets/images/payment_icons/grabpay.svg)? Which icon is "MCash eWallet"?

**Comment by alfredkho** [comment]
> 👋 Hey @handzalah94, is "GrabpayPH" [grabpay.svg](https://github.com/activemerchant/payment_icons/blob/f33d706debd8027ebc38b0a312cc20694a08a910/app/assets/images/payment_icons/grabpay.svg)? Which icon is "MCash eWallet"?

Hey @larouxn You may ignore for GrabPay, as they were added in previously. 
As for the MCash eWallet, you may refer to this Pull request [https://github.com/activemerchant/payment_icons/pull/382/]

Also, would like to follow up on the deployment for the rest of the logo? and the logo that wasn't available on the merchant side?

**Comment by larouxn** [comment]
Hey @alfredkho

> You may ignore for GrabPay, as they were added in previously

Okay, sounds goods.

> As for the MCash eWallet, you may refer to this Pull request

We're currently waiting for green CI on https://github.com/activemerchant/payment_icons/pull/382.

> deployment for the rest of the logo? and the logo that wasn't available on the merchant side?

Do we have a specific list of icons that are missing/undeployed? All merged icons have been released.

Also, please note, it's unlikely anything will be deployed until the week of January 4th due to holidays.

**Comment by alfredkho** [comment]
> @alfredkho : it seems like there is a list of icons that didn't go through on the merchant side. Me and @larouxn will go check the list and see which one is missing, but I can't promise you that we'll get this done this in a short time, mainly as this project isn't in our top priority and also black friday/cyber monday is coming so deployment will be on paused.

Hi @larouxn Well noted on the MCash eWallet. 
Unfortunately we do not have a specific list of icons, however previously we found that some of the logo are available in Partner account but not merchant account. Hence, we were being told that all the icons will be go through again to ensure they are available on both side. So i am following up on this if the checking were complete as we were not being informed of any new update after our last conversation. (Quoted reply for your reference)

**Comment by larouxn** [comment]
Ah yes, we still need to manually check the available icon list for potential differences. I'd like to have said check done by some time in January.

**Comment by alfredkho** [comment]
Hi @larouxn , we would like to follow up on the status for the checking.

**Comment by larouxn** [comment]
👋 Hey @alfredkho, nothing to report yet but we're aware of the issue and still hoping to look into it soon.

**Comment by alfredkho** [comment]
@larouxn hey, thanks for updating. We hope this issue can be cleared off as soon as possible. Thanks in advance for your help.

**Comment by larouxn** [comment]
Hey @alfredkho, I've looked into it some today and have definitely discovered some unsupported icons. Hoping to have full support for all icons in this gem live within a week or so. Sorry for the delay thus far.

**Comment by larouxn** [comment]
👋  Hello @alfredkho, I'm excited to let you know that we've shipped some fixes and now believe all icons are within [activemerchant/payment_icons](https://github.com/activemerchant/payment_icons) are supported everywhere on the Shopify platform.

Please let me know if anything is off or missing. Thanks!

**Comment by alfredkho** [comment]
Hi @larouxn Glad to know that, we will get this available on merchant account and get back to you if there is any issue.
Thanks a lot!

**Pull request merged**
