### PR TITLE
Update ViaBill Icon For Rebranding

### PR DESCRIPTION
**Pull request by ViaBill-Integrations**

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
LGTM 👍 
Screen Shot 2020-10-06 at 21 59 15

**Comment by ViaBill-Integrations** [comment]
Hi there,

 Thank you for reaching out to the ViaBill onboarding team.

 We've received your message, and we'll be in touch within 2 business days.

 Kind regards,

 The Onboarding Team

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
We're missing a grey border around the icon. Can we add that?

image

See this [example icon](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/visa.svg) as a reference.

**Comment by ViaBill-Integrations** [comment]
Hi there,

 Thank you for reaching out to the ViaBill onboarding team.

 We've received your message, and we'll be in touch within 2 business days.

 Kind regards,

 The Onboarding Team

 

 

 
   Previous-message-reference:
<activemerchant/payment_icons/pull/353/review/507493659@github.com>

 Previous-message-reference:
<06ad6e16a89f473ebeb52fa40b7986f1@email.dixa.io>

**Comment by rahilvirani** [comment]
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

**Comment by ViaBill-Integrations** [comment]
Hi there, Thank you for reaching out to the ViaBill onboarding team. 

We've received your message, and we'll be in touch within 2 business days. 
Kind regards,
 The Onboarding Team

In the meantime, take a look at our Merchant FAQ section 
<https://help.viabill.com/l/en/merchant-support> where you will find the answer 
to most of your questions.

Commonly asked questions: 

1) How ViaBill works <https://help.viabill.com/en/articles/40>
2) Where can I see my orders and payouts? 
<https://help.viabill.com/en/articles/54-where-can-i-see-my-orders-and-payouts>
3) How do I update my banking, business, or personal information? 
<https://help.viabill.com/en/articles/60-updating-your-business-personal-and-banking-information>




 <https://help.viabill.com/en/categories/10-merchant-support>

Previous-message-reference: 
***@***.***>

Previous-message-reference: ***@***.***>
Rahil Virani September 16, 16:37 GMT

Closed #353 < https://github.com/activemerchant/payment_icons/pull/353 
<https://github.com/activemerchant/payment_icons/pull/353> >.

—
 Reply to this email directly, view it on GitHub
 < https://github.com/activemerchant/payment_icons/pull/353#event-7404603290 
<https://github.com/activemerchant/payment_icons/pull/353#event-7404603290> >, 
or
 unsubscribe
 <

**Pull request closed without merging**
