### PR TITLE
Updated Paidy icon

### PR DESCRIPTION
**Pull request by markgaensicke**
Paidy refreshed their branding; this PR is to update Active Merchant to reflect the new logo.

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible. → [Paidy brand guidelines](https://paidy.com/docs/en/branding.html)
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hey @markgaensicke, can we clean up some of the IDs here in this updated SVG? Seeing test failures related to them but more so would be nice to have more succinct IDs than `paint0_linear_508_418`. Ideally we can remove them if possible.

All that said, icon does look good so once markup is addressed we can likely merge this.
Screen Shot 2022-04-01 at 14 27 36

CC @tauthomas01

**Comment by markgaensicke** [comment]
Grüezi @larouxn ! Thanks for the heads-up. We've changed the IDs to be in line to the [Guidelines for *new* icons](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons).

Designers will update their original source to not have those IDs in the future.

Thanks!

**Review by larouxn — APPROVED** [review]
Thanks for fixing this up! Looks good to me :tophat: 
Screenshot from 2022-04-04 19-54-57

**Comment by markgaensicke** [comment]
OK, now all tests pass 👍 Thanks!

**Comment by markgaensicke** [comment]
Question: how long does it take, after merge, until this new icon is visible in Shopify checkout?

**Review by tauthomas01 — APPROVED** [review]

**Comment by tauthomas01** [comment]
> Question: how long does it take, after merge, until this new icon is visible in Shopify checkout?

We'll need to make a deployment to all Shopify platform and we usually do a release once a month.

**Comment by larouxn** [comment]
👋 Hello, your updated icon should be available everyone now. Please let us know if otherwise.

**Pull request merged**
