### PR TITLE
Payfast payment method icons

### PR DESCRIPTION
**Pull request by RonDarby**

### CODE REVIEW

**Comment by jamiemtdwyer** [comment]
Just needs to be rebased on master, otherwise LGTM. 👍

**Comment by RonDarby** [comment]
Hi, thanks @jamiemtdwyer , see https://github.com/activemerchant/payment_icons/pull/15 please

**Comment by andrewpaliga** [comment]
@RonDarby it's really difficult to read the writing on the icons (especially the one below). Is it possible to provide a design more suited for this scale?

payment_icons payfast_instant_eft svg at ab876ef43983ca0c4f46fa742e26e8f15c26d60c payfast payment_icons 2016-06-07 10-43-00 2016-06-07 10-43-02

**Comment by RonDarby** [comment]
@jamiemtdwyer @andrewpaliga, changes made, please can you review pull request https://github.com/activemerchant/payment_icons/pull/15

**Comment by andrewpaliga** [comment]
LGTM -- @aprofeit?

**Pull request closed without merging**
