### PR TITLE
add zinia

### PR DESCRIPTION
**Pull request by payeverdev**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by payeverdev** [comment]
I have updated the icon, can the workflow be run

**Comment by larouxn** [comment]
> I have updated the icon, can the workflow be run

It has been run. Please see the [CI logs](https://github.com/activemerchant/payment_icons/runs/6741922868?check_suite_focus=true).

**Comment by payeverdev** [comment]
> > I have updated the icon, can the workflow be run
> 
> It has been run. Please see the [CI logs](https://github.com/activemerchant/payment_icons/runs/6741922868?check_suite_focus=true).

I have fixed the clip error, please run again.

**Review by larouxn — CHANGES_REQUESTED** [review]
The icon is missing a background/shape. Can we base it off of the [template](https://github.com/activemerchant/payment_icons/blob/c9d880d52728e6e3a2af1be9a81ec5f55b841803/CONTRIBUTING.md#template)?
Screen Shot 2022-06-27 at 14 34 52
Screen Shot 2022-06-27 at 14 35 34

**Review by larouxn — CHANGES_REQUESTED** [review]
Looks like the icon is too wide, reaching outside of the background.
image

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-06-28 at 17 39 55

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
Hi,

I left some comments.

Please let me know if there are any questions.

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Hello, we're working on the [v1.7.16](https://github.com/activemerchant/payment_icons/pull/702) release now. It will likely go live next week.

Apologies for the wait. Will report back here when it's live. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

**Pull request merged**
