### PR TITLE
Can you please review humm payment icon ?

### PR DESCRIPTION
**Pull request by rbi-flexigroup**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by shophumm** [comment]
hi @larouxn we are updating a PR that was submitted a few months ago, can we have this PR reviewed and merged if everything looks good? thanks

**Comment by larouxn** [comment]
👋 Hello, apologies but I (personally) no longer maintain this gem. If this icon is for use within Shopify you may be able to reach out to your partner manager and/or the payments platform team.

**Review by rahilvirani — APPROVED** [review]
image

The appearance looks good to me

**Comment by shophumm** [comment]
Hello @rahilvirani  ,  thanks , when to release the  merge and kindly advise when the humm payment icon is available at chechout on the shopify website ?

**Comment by shophumm** [comment]
Hello @rahilvirani , 

Can our GM William and I  know the progress for the payment icon available at updating Payment App Configuration 

Screen Shot 2022-09-26 at 3 28 11 pm


looking for your reply, 

Thanks

**Comment by rahilvirani** [comment]
@shophumm you should be able to access the icons now! They went live on Shopify on Tuesday

**Pull request merged**
