### PR TITLE
Mondido icons update: update trustly logo to reflect updated logo 

### PR DESCRIPTION
**Pull request by muhammadjalabi**
The Trustly brand has recently updated their brand logo, brands guidelines can be read here: [Trustly's 
Brand Guidelines](https://trustlybrandguidelines.com/)

Reading the visual identity, it seems to me that the Trustly-symbol and the wordmark function together as a unified logo, but there are two use-cases of where the Trustly-symbol is used by itself; (1) in an animation where the trustly wordmark appears a slight second after (so the end-result is adopting the the unified look), (2) in the iOS App Store.
Downloading the Trustly-symbol, it's only provided in .png, which makes me think it's not intended to be used by itself, I could be wrong here.

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand

### CODE REVIEW

**Comment by larouxn** [comment]
👋  Hey @muhammadjalabi, it looks like the new icon is missing the spacing around it, the border, and the white background. Can we add those back in? ([guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance))
Screen Shot 2021-03-18 at 22 19 59

**Comment by muhammadjalabi** [comment]
Hey @larouxn! 👋🏼 
First time ever I contribute to a project, well done on the excellent guidelines for adding value to the repo! 
I totally missed that part, will address asap!

**Comment by muhammadjalabi** [comment]
@larouxn Do you think this looks okay now? Possible to get it approved? =)

**Comment by muhammadjalabi** [comment]
@tauthomas01 would it be cool to bother you about an approval for this PR if it looks good?

**Review by larouxn — APPROVED** [review]
LGTM 🙌 
Screen Shot 2021-03-26 at 16 30 12

**Review by tauthomas01 — APPROVED** [review]

**Pull request merged**
