### PR TITLE
Fix d Barai icon

### PR DESCRIPTION
**Pull request by yishus**
Screenshot 2020-10-01 at 9 21 10 AM

Resolves https://github.com/activemerchant/payment_icons/issues/352

### CODE REVIEW

**Review by larouxn — CHANGES_REQUESTED** [review]
I think we need to remove the `<path fill="#fff" d="M0 0h38v24H0z"/>`. It's causing a white background. Was a bug in the previous icon as well. (with and without it below)
Screen Shot 2020-10-01 at 15 04 09

**Review by larouxn — APPROVED** [review]
LGTM 🚀 
Screen Shot 2020-10-01 at 15 22 15

**Review by larouxn — APPROVED** [review]
Still LGTM

**Comment by yishus** [comment]
one last change 🙇 🙇 good to merge after this

**Review by larouxn — APPROVED** [review]
🎩 LGTM
Screen Shot 2020-10-01 at 16 39 29

**Pull request merged**
