### PR TITLE
add kueskipay.svg and update .yml

### PR DESCRIPTION
**Pull request by isaiah-kueski**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 @isaiah-kueski, it looks like the border and general size is a bit different than the [guidelines](https://github.com/activemerchant/payment_icons/blob/10972c061718a4c96b3d7517ce162c203524eddb/CONTRIBUTING.md).
Screen Shot 2021-07-19 at 16 13 27

Example from the docs

```svg
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-{your-icon}">
    <title id="pi-{your-icon}">{Your icon}</title>
    <path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/>
    <path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/>
</svg>
```

**Review by larouxn — COMMENTED** [review]
Hmm, strangely seems to still be larger than standard `visa` icon.
Screen Shot 2021-07-20 at 16 25 14

Perhaps it's the border's width or opacity. 🤔

**Comment by tauthomas01** [comment]
> Perhaps it's the border's width or opacity. 🤔

It seems to be related on how you set the border position in the Illustrator application: "inside" or "outside".

**Comment by isaiah-kueski** [comment]
> Example from the docs
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-{your-icon}">
>     <title id="pi-{your-icon}">{Your icon}</title>
>     <path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/>
>     <path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/>
> </svg>
> ```

Can I still use this format?
```
<rect x="1" y="1" width="36" height="22" rx="2" fill="#fff" />
<rect x=".5" y=".5" width="37" height="23" rx="2.5" stroke="#000" stroke-opacity=".07" />
```

**Comment by isaiah-kueski** [comment]
I copy pasted code from template, and double checked using Figma to check my .svg with visa.svg and it seems everything is fine. I hope third time's the charm

**Review by larouxn — APPROVED** [review]
Looks good to me now. 👏 
Screen Shot 2021-07-21 at 16 30 01

**Review by tauthomas01 — APPROVED** [review]

**Pull request merged**
