### PR TITLE
Add ApeCoin icon

### PR DESCRIPTION
**Pull request by ksmithbaylor**
**Checklist**
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

Branding guidelines are found on the [ApeCoin website](https://apecoin.com/) at the bottom by clicking Press Kit ([direct download link](https://apecoin.com/assets/press/ApeCoin_Press_Kit.zip)).

Actual size:
image

Enlarged:
image

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
Looks good to me. Though I will note, I see an SVG nested inside another SVG here. Seems like it should work fine but seems fairly uncommon.

Screen Shot 2022-08-09 at 12 22 26

**Review by tauthomas01 — APPROVED** [review]
> I see an SVG nested inside another SVG here. Seems like it should work fine but seems fairly uncommon.

Looks good to me as well but I agree with @larouxn that it's unusual to see a nested svg inside another one. Could we replace it with something else?

It might look good on the visual side, but I have some worries if something happens during our release.

**Comment by ksmithbaylor** [comment]
Done!

**Review by zbriscoe — APPROVED** [review]
Re-reviewing after the newest changes, looks good:

Screen Shot 2022-09-15 at 11 25 10 AM

**Pull request merged**
