### PR TITLE
add paytomorrow logo

### PR DESCRIPTION
**Pull request by TushGH**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Can we update the icon to match the rest of the icons (shape)? ([template](https://github.com/activemerchant/payment_icons/blob/bd0f7ce66eef2cac215145d466cc21cb3474e24c/CONTRIBUTING.md#template))
Screen Shot 2022-07-07 at 17 32 15Screen Shot 2022-07-07 at 17 32 31

**Comment by TushGH** [comment]
> 👋 Can we update the icon to match the rest of the icons (shape)? ([template](https://github.com/activemerchant/payment_icons/blob/bd0f7ce66eef2cac215145d466cc21cb3474e24c/CONTRIBUTING.md#template)) Screen Shot 2022-07-07 at 17 32 15 Screen Shot 2022-07-07 at 17 32 31

Hey, I have updated the SVG to match the rest of the icons. let me know if there are any other recommendations. Thanks

**Review by larouxn — CHANGES_REQUESTED** [review]
Icon looks pretty good but can we shrink it a bit so there's space on both the left and right side? Also, can we center it vertically?

Screen Shot 2022-07-15 at 16 49 55

**Comment by TushGH** [comment]
> Icon looks pretty good but can we shrink it a bit so there's space on both the left and right side? Also, can we center it vertically?
> 
> Screen Shot 2022-07-15 at 16 49 55

Changed the SVG to add space and made it in the center. please let me know if you want any other changes.

**Review by larouxn — APPROVED** [review]
Looks good to me 🎩 
Screen Shot 2022-07-21 at 15 33 18

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Hello, we're working on the [v1.7.16](https://github.com/activemerchant/payment_icons/pull/702) release now. It will likely go live next week.

Apologies for the wait. Will report back here when it's live. 🙇‍♂️

**Comment by larouxn** [comment]
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

**Pull request merged**
