### PR TITLE
Added Super Payments icon

### PR DESCRIPTION
**Pull request by crossleydominic**
## Why are you adding this icons?
Super Payments is a new payments provider in the UK (currently). More information can be found at 
https://www.superpayments.com/about
https://www.linkedin.com/company/superpayments/mycompany/

This PR adds the Super Payments icon in preparation for a submission of the Super Payments Shopify payments app.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [X] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: https://design.superpayments.com/Super_Toolkit_MO_280722_v2_compressed.pdf

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

https://design.superpayments.com/super-payments-icon-comparions.png

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Thanks for your submission. Two changes:

- The name cannot have special characters, so please change "super_payments" to "superpayments"
- The icon itself could benefit from an extra pixel of padding on the left and right. It looks too tight in the frame.

**Comment by crossleydominic** [comment]
Suggested changes have been made. 

New icon comparison image can be found here: https://design.superpayments.com/super-payments-icon-comparison-resubmission.png

Thanks

**Comment by Jacquesattaque** [comment]
Icon looks good, just clear the failing checks and I'll approve

**Comment by crossleydominic** [comment]
I've updated the icon so it should now pass the tests. Thanks

**Comment by crossleydominic** [comment]
I've seen the test failures. I'll fix. Thanks

**Comment by crossleydominic** [comment]
All tests should now pass. Thanks

**Comment by crossleydominic** [comment]
Apoliges, rookie mistake, I pushed the wrong branch. I've pushed the correct one now.

**Review by Jacquesattaque — APPROVED** [review]

**Comment by adeniyiao** [comment]
Hello @crossleydominic 

The changes are good to go but we need y'all to rebase your branch superpayments:super_payments_icon with activemerchant/master to resolve these conflicts.

image

After the rebase is done, we will be able to merge your changes.

**Comment by crossleydominic** [comment]
This has now been rebased. Thanks

**Comment by crossleydominic** [comment]
On second glance it looks like it was an internal GHA failure:
``` 
Ruby 3.2 gemfiles/rails-edge.gemfile
GitHub Actions has encountered an internal error when running your job.
```
Re-running should hopefully fix it.

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
