### PR TITLE
Add BillEase installment option available for Dragonpay in the Philip…

### PR DESCRIPTION
**Pull request by jerieldragonpay**
…pines

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by jerieldragonpay** [comment]
Hi Team, requesting comment if there are issues with this pull request. The brand, BillEase, does not have a public brand icon guideline, but we are trying to reach out to them. They are our payment partner.

Thank you.

@tauthomas01

**Review by tauthomas01 — APPROVED** [review]
This looks good

**Comment by jerieldragonpay** [comment]
Thank you @tauthomas01. Just got confirmation that BillEase does not have icon guidelines, "as long as attached photos will be used". 

The "attached photos" varied a little with the tagline as "Buy Now Pay Later [BillEase]"/"Shop Now Pay Later [BillEase]", instead of "Pay with [BillEase]". Clarifying with them if "Pay with [BillEase]" is okay.

**Comment by jerieldragonpay** [comment]
> Thank you @tauthomas01. Just got confirmation that BillEase does not have icon guidelines, "as long as attached photos will be used".
> 
> The "attached photos" varied a little with the tagline as "Buy Now Pay Later [BillEase]"/"Shop Now Pay Later [BillEase]", instead of "Pay with [BillEase]". Clarifying with them if "Pay with [BillEase]" is okay.

Confirmed that the icon included in this commit, "Pay with BillEase", is okay.

**Review by larouxn — APPROVED** [review]
LGTM
Screenshot from 2021-09-21 09-03-32

**Comment by larouxn** [comment]
@jerieldragonpay, looks like we'll need to rebase this PR as there's a merge conflict with latetst `db/payment_icons.yml`.

**Comment by larouxn** [comment]
👋 Hey @jerieldragonpay, thanks for the quick rebase. One last thing though, it looks like this PR is now 5 commits, including unrelated, already merged commits. Can we clean this up to be just the Dragonpay commit(s)?
Screen Shot 2021-09-21 at 12 48 30

**Comment by jerieldragonpay** [comment]
> 👋 Hey @jerieldragonpay, thanks for the quick rebase. One last thing though, it looks like this PR is now 5 commits, including unrelated, already merged commits. Can we clean this up to be just the Dragonpay commit(s)?
> Screen Shot 2021-09-21 at 12 48 30

I am okay with that, but I honestly don't know how to do that. Should I just start over again with a new branch?

**Comment by jerieldragonpay** [comment]
@larouxn new one https://github.com/activemerchant/payment_icons/pull/487

**Pull request closed without merging**
