### PR TITLE
Add icons for UOB EZPay and Akulaku Paylater

### PR DESCRIPTION
**Pull request by keshav-c**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

### UOB EZPay screenshot

ss-uob-ezpay

### Akulaku PayLater screenshot

ss-akulaku-paylater

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Please only use alphabetic characters in the name. So uob-ezpay and akulaku-paylater could be uobezpay and akulakupaylater.

**Review by Jacquesattaque — APPROVED** [review]

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
@keshav-c This update looks good but has caused some automated checks to fail; can you have a look?

**Comment by keshav-c** [comment]
@Jacquesattaque I think it was because the filenames no longer matched db/payment_icons.yml
Can you run the checks again?

**Comment by Jacquesattaque** [comment]
Checks are still failing @keshav-c

**Comment by keshav-c** [comment]
@Jacquesattaque Sorry for the late update 🙏 I think the checks were failing because the `id` and `aria-labelled-by` attributes also needed to match the svg filenames. I've fixed those. Can you please run the checks again?

**Comment by keshav-c** [comment]
@Jacquesattaque Thanks for running the checks again, and sorry it still keeps failing. I have
- Run the svgo tool on the `akulakupaylater` icon again
- Made sure that there are no `class` attributes and `<style>` elements in the svgs.
- All `id` elements start with `pi-`
- The `name`s, `title`s, and `id`s are correct as per specification
- Also made sure that after the changes, the icons look the same.

Kindly run the checks again.

**Review by Bernis245 — APPROVED** [review]

**Review by Bernis245 — APPROVED** [review]

**Comment by keshav-c** [comment]
Hi @Jacquesattaque , @Bernis245 👋 
Please run the CI checks again for this PR.

**Review by Jacquesattaque — APPROVED** [review]

**Pull request merged**
