### PR TITLE
LatitudePay and Genoapay - Latitude Financial Services

### PR DESCRIPTION
**Pull request by william-lfs**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
https://resources.latitudefinancial.com/docs/latitude-pay/assets-logos/
https://www.genoapay.com/media-toolkit/

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Review by tauthomas01 — CHANGES_REQUESTED** [review]
Hi @william-lfs ,

These icons look good. There's one thing to do before approving: could you remove the empty spacing and put the code all in one line?

Here is an example: https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/visa.svg?short_path=e20b466

**Comment by william-lfs** [comment]
Hi @tauthomas01,
Thank you for your review.
I have made the SVG into 1 line only.
Maybe worth updating [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) with this instructions as well for others to follow.

**Comment by william-lfs** [comment]
Hi @tauthomas01, is this something that we can action today? As we're releasing a new Payments app, we're waiting on this before we can do our UAT. Thank you.

**Review by tauthomas01 — APPROVED** [review]
Sorry @william-lfs , I was on vacation.
This looks good

**Review by larouxn — APPROVED** [review]
🎩 🎩 🎩 🎩 🎩 
Screen Shot 2022-01-05 at 20 42 16

---

EDIT: All looks good now since Rails 7.0.1 was released, fixing Rails latest tests, please disregard below.

Note, the [strange flaky CI tests on Rails latest](https://github.com/activemerchant/payment_icons/runs/4715157063?check_suite_focus=true) should be resolved once Rails 7.0.1 drops, likely tomorrow January 6th. (context: https://github.com/rails/rails/issues/43998)
```
Rails::Engine is abstract, you cannot instantiate it directly.
/home/runner/work/payment_icons/payment_icons/vendor/bundle/ruby/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:246:in `initialize'
```

**Comment by larouxn** [comment]
👋 @william-lfs, we'll try to get these live within the month. Will report back here when they are live.

**Comment by Chandan-lfs** [comment]
Hi @larouxn Thanks for the update. Any chance this can be expedited as we are planning to go live with our new payment app this month and we can't add any icons or logos to the new app? @william-lfs is away on leave thus I am looking after this during his absence.

**Comment by larouxn** [comment]
👋 @Chandan-lfs, we're still aiming to have the icons live within January. Will update here when it's live.

**Comment by larouxn** [comment]
👋 @Chandan-lfs, the LatitudePay and Genoapay icons should now be available everywhere.

**Comment by william-lfs** [comment]
Hi @larouxn Thank you for the update! Greatly appreciated.

How do we make our logos to be available for selection in Partner App settings?
We are not able to find LatitudePay & Genoapay icons from the dropdown:
Screen Shot 2022-01-28 at 10 08 07

However we can access the new icons if we call them from the footer.liquid:
Screen Shot 2022-01-28 at 12 28 20
Screen Shot 2022-01-28 at 12 31 06

**Comment by larouxn** [comment]
👋 @william-lfs, thanks for the heads up. I believe I have found and fixed the issue. Your icons _should_ available now.

Can you please take a look and let me know when you have a moment? Thanks!

**Comment by william-lfs** [comment]
Hi @larouxn, thank you very much! It's working! 👍

**Pull request merged**
