### PR TITLE
added affirm logo

### PR DESCRIPTION
**Pull request by AmyBeall**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by larouxn** [comment]
👋 Hello @AmyBeall, thank you for your contribution. Can we update the icon to be a rounder rectangle like the other icons? You can find a template SVG here in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/dc6de5046bf9afac185e5b54983eedd76b0a08a6/CONTRIBUTING.md#template).
Screen Shot 2021-09-10 at 09 43 30

**Comment by AmyBeall** [comment]
On it! Thanks for the quick feedback

**Comment by larouxn** [comment]
👋  Seeing the following error over here in [test logs](https://github.com/activemerchant/payment_icons/pull/483/checks?check_run_id=3562546495).
```
Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:89]:
{:message=>"The 'clip0' ID should be pi-affirm-clip0 (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "clip0".
```

You may find it helpful to run tests locally via `bundle exec rails test`.

**Comment by AmyBeall** [comment]
@larouxn we updated the SVG, please let me know if it works!

**Review by larouxn — COMMENTED** [review]
Hmm, still something off about the border here. I think this new icon uses an outside border whereas we typically use inside borders.
Screenshot from 2021-09-21 09-04-59

**Comment by tauthomas01** [comment]
> I think this new icon uses an outside border whereas we typically use inside borders.

That sounds right from the look of it.

**Comment by AmyBeall** [comment]
@LaNeraNura 3rd times a charm :)

**Review by tauthomas01 — APPROVED** [review]

**Review by larouxn — APPROVED** [review]
LGTM :raised_hands: 
Screenshot from 2021-09-24 17-30-47

**Comment by larouxn** [comment]
👋  Ran into a few release pipeline issues. Hoping to have this live by end of next week, potentially sooner.

**Pull request merged**
