### PR TITLE
Add Home Credit icon

### PR DESCRIPTION
**Pull request by tungd**
## Why are you adding this icons?
I'm adding icon for Home Credit, as we are building Home Credit integration and would like proper branding showing up, as discussed.

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

Screenshot 2023-05-30 at 09 32 27

Previous version with a bit too narrow padding, for reference:

Screenshot 2023-05-18 at 12 17 24

#### If the icons are intended for use by Shopify, please provide the following info:

Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

Sabrina. Please refer to the support ticket numbered 38453095.

What's the expected date of this change to deploy on Shopify?

June 15th, 2023

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
@tungd The icon looks good — I would consider making the logo a little smaller to give it more padding. You can see how Visa has handled this in their icon.

**Comment by tungd** [comment]
@Jacquesattaque Hi 👋 , I've updated the icon with more appropriate padding. Please help me review it. Thank you very much.

Screenshot 2023-05-30 at 09 32 27

**Review by Jacquesattaque — APPROVED** [review]

**Comment by tungd** [comment]
@Jacquesattaque Hi 👋 , I see the PR is approved. Is there any ETA on when will this be merged and is available on Shopify?

**Comment by Jacquesattaque** [comment]
We do a monthly release — the June release is scheduled for next Wednesday, June 7.

**Pull request merged**
