### PR TITLE
Add Tensile

### PR DESCRIPTION
**Pull request by sshelton-tensile**
** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by sshelton-tensile** [comment]
@tauthomas01 @larouxn any word on when this PR can get reviewed and merged?

**Review by larouxn — CHANGES_REQUESTED** [review]
This icon should have a wide background + the 0.7 border like this [template](https://github.com/activemerchant/payment_icons/blob/514f3497775930f695f9f87eafe1353fcd98156c/CONTRIBUTING.md#template).
Screen Shot 2022-04-20 at 12 44 21
Screen Shot 2022-04-20 at 12 45 09
Screen Shot 2022-04-20 at 12 45 54

**Comment by larouxn** [comment]
👋 @sshelton-tensile, thanks for updating. Unfortunately still looks off here. Maybe the white background is extending into the border or something, not sure. Maybe we can revisit the template to compare.

Screen Shot 2022-04-21 at 10 22 38

**Comment by sshelton-tensile** [comment]
@larouxn okay I _think_ it's fixed now. I used Gapplin to compare it to other svg's in light and dark mode.

**Review by larouxn — APPROVED** [review]
Looks good to me! 🎩 
Screen Shot 2022-04-21 at 15 44 36

**Review by tauthomas01 — APPROVED** [review]

**Comment by larouxn** [comment]
👋 Hello, your icon(s) should be available everyone now. Please let us know if otherwise.

**Pull request merged**
