### PR TITLE
Etika payments icon addition for shopify

### PR DESCRIPTION
**Pull request by ryanhissey**
## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

Screenshot 2023-02-10 at 11 48 52

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

Etika (Shopify partner) 

What's the expected date of this change to deploy on Shopify?

ASAP

### CODE REVIEW

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Thanks for your submission! Please update the border to 7% opacity – everything else looks good. You've also got some automated checks failing. Once those are clear, we can approve.

**Comment by ryanhissey** [comment]
> Thanks for your submission! Please update the border to 7% opacity – everything else looks good. You've also got some automated checks failing. Once those are clear, we can approve.

Hey @Jacquesattaque, thanks for taking the time to look at my PR. I have made the changes you stated above. Please could you run the CI again as it doesn't allow me to. Thanks 😄

**Comment by Jacquesattaque** [comment]
@ryanhissey Icon looks good. You've got some conflicts to resolve and then I'll approve.

**Comment by ryanhissey** [comment]
@Jacquesattaque These conflicts have now been resolved. Please could you take another look.

**Comment by Jacquesattaque** [comment]
@ryanhissey You've still got some automated checks failing. Please have a look.

**Comment by ryanhissey** [comment]
Hey @Jacquesattaque, Ooops sorry looks like when the merge conflicts were resolved I removed a line in `db/payment_icons.yml` This should now be fixed, Please can you rerun the pipeline 😄

**Comment by ryanhissey** [comment]
Hey @Jacquesattaque, Do you have an ETA on the next release? We were waiting on this payment icon to be added so we can submit our app. Thanks

**Pull request merged**
