### PR TITLE
Add Clerq Payments icon

### PR DESCRIPTION
**Pull request by h3nnn4n**
## Why are you adding this icons?
I'm adding/updating this icon(s) because we are in the publishing process of a payment app.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon along side the example Visa icon

image

#### If the icons are intended for use by Shopify, please provide the following info:
- Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

- What's the expected date of this change to deploy on Shopify?
ASAP

### CODE REVIEW

**Review by dmrkv — CHANGES_REQUESTED** [review]
Hello!
everything alright except the fact that icon touches the border.
Would be nice to add some white space between icon itself and the border.

**Comment by h3nnn4n** [comment]
Hey @dmrkv 

We made the icon smaller, and updated it as well.

lmk if it needs further changes

**Comment by anujbhatt** [comment]
@dmrkv @Jacquesattaque anything else that is needed from our side?

**Comment by Jacquesattaque** [comment]
@anujbhatt Yes — you have some failing checks you need to clear and then I can approve.

**Comment by anujbhatt** [comment]
@Jacquesattaque - can you now run the jobs?

**Comment by anujbhatt** [comment]
Addressing these items

**Comment by anujbhatt** [comment]
@Jacquesattaque changes made and tests ran locally. Please re-run workflow and let us know if additional changes arer needed. Thank you!

**Review by Jacquesattaque — APPROVED** [review]

**Comment by anujbhatt** [comment]
@Jacquesattaque @dmrkv what are next steps here? Is there an ETA on when the PR gets approved and the icon will show up in Shopify?

**Comment by Jacquesattaque** [comment]
@anujbhatt Next release is scheduled for May 3.

**Comment by anujbhatt** [comment]
@Jacquesattaque is this something that will hold up our payment app approval or is this independent of that process?

**Comment by Jacquesattaque** [comment]
@anujbhatt No, it shouldn't. You'll be able to update the app afterwards to add the icon.

**Comment by anujbhatt** [comment]
@Jacquesattaque I see this is still pending a review from @dmrkv and just wanted to make sure it's all set to go out with the the next deploy.

**Comment by Jacquesattaque** [comment]
Thanks @anujbhatt — I dismissed the review. You're all good.

**Review by douglas — APPROVED** [review]

**Comment by douglas** [comment]
Hello @anujbhatt and @h3nnn4n! The changes are good to go but we need y'all to rebase your branch `clerq-io:clerq_payments_icon` with `activemerchant/master` first to resolve these conflicts.

Screenshot 2023-05-03 at 09 55 21

After the rebase is done, we will be able to merge your changes - let us know if you have any questions 👍

**Comment by h3nnn4n** [comment]
@douglas All done

Here shows that it is pending approval from a maintainer, so I can't merge yet.
image

**Comment by h3nnn4n** [comment]
@douglas All green now: 
image

**Comment by h3nnn4n** [comment]
@adeniyiao Updated 🙌

**Pull request merged**
