### PR TITLE
Updated sezzle payment icon to work more universally

### PR DESCRIPTION
**Pull request by killianbrackey**
** Checklist **
- [x] All icons include `width="38" height="24"` in their attributes
- [x] All icons have solid white backgrounds
- [x] All icons have a a `viewBox` attribute
- [x] All fonts have been converted to paths
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I am confident that all icons are clear and easy to read/understand

Updated image:
https://cl.ly/3Z0B2N0m1y16

If this pull request is not adding new icons, you can remove this checklist.

### CODE REVIEW

**Comment by killianbrackey** [comment]
Related to #39 .  This is just an updated image that works more universally for shops and on payment views.  @AnthonyClark previously approved, is there anything missing here or that I can do to help it along?  Thanks!

**Comment by charlieyouakim** [comment]
Would love to see this pull request completed.

**Comment by AnotherJoSmith** [comment]
Hey @killianbrackey @charlieyouakim,

Love the new design, only two small things:

 - Can you increase the width of the svg by 4 pixels? Currently the image is 34x24 and it needs to be 38x24.
- Can you set the background to solid white? It is currently transparent.

Thanks!

**Comment by killianbrackey** [comment]
@AnotherJoSmith Thanks for getting back! The most recent commit has these changes -- I can squash the commits if you would like.  

Let me know if there are any other issues!  The background is now white and the dimensions are 38x24

**Comment by AnotherJoSmith** [comment]
@killianbrackey Looks great! Can you squash and I will merge :)

**Comment by killianbrackey** [comment]
Squashed and down to 1 commit.  Let me know if there is anything else you need @AnotherJoSmith 

Thanks!

**Pull request merged**
