### PR TITLE
Add payment icon for Dinacard

### PR DESCRIPTION
**Pull request by ALibrenjak-Corvuspay**
## Why are you adding this icons?
I'm adding this icon because CorvusPay's payment app needs to add DinaCard as payment method according to ticket 44582605. 
https://dinacard.nbs.rs/english/index.html

#### Help us identify yourself
- [ ✓ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>
-Not available

## Checklist to add new icons
- [ ✓ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ✓ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ✓ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ✓ ] I am confident that all icons are clear and easy to read/understand
- [ ✓ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ✓ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [ ✓ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
dina visa

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-dinacard"><title id="pi-dinacard">Dinacard</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path id="path14" fill="#2350a9" d="M3.547 12.628h.438c.403 0 .684-.07.842-.194.157-.122.245-.35.245-.65 0-.315-.088-.544-.245-.667-.158-.14-.439-.193-.824-.193h-.456zm-1.648.878v-3.46H3.88c.508 0 .877 0 1.14.035.245.036.455.088.63.158.351.14.632.334.807.597.175.264.263.58.263.949s-.105.702-.333.983c-.21.264-.544.457-.982.597a2.596 2.596 0 01-.613.106 18.43 18.43 0 01-1.21.035zm5.417-2.81v-.738h1.507v.738zm0 2.81v-2.564h1.507v2.564zm2.244 0v-2.564h1.367v.386a1.6 1.6 0 01.578-.333 2.5 2.5 0 01.737-.106c.228 0 .438.018.613.07.193.053.333.123.456.229.123.105.193.21.245.35.053.124.07.352.07.633v1.335h-1.49V12.17c0-.193-.035-.316-.122-.386-.07-.07-.21-.106-.386-.106-.193 0-.333.035-.438.123-.088.088-.123.193-.123.369v1.335zm7.275-1.142a6.63 6.63 0 01-.561.106c-.386.07-.561.158-.561.28 0 .07.035.123.105.176a.73.73 0 00.315.053c.246 0 .439-.035.544-.123.122-.07.175-.193.175-.369V12.4c0-.017 0-.035-.017-.035zm.14 1.142l-.088-.246a2.64 2.64 0 01-.613.246c-.228.07-.474.087-.754.087-.42 0-.754-.07-1-.21a.67.67 0 01-.333-.597c0-.264.106-.457.334-.58.227-.105.666-.193 1.297-.263.087 0 .193-.018.333-.018.473-.017.701-.105.701-.228 0-.088-.035-.14-.123-.176-.087-.035-.228-.035-.42-.035a.982.982 0 00-.351.053c-.088.035-.123.105-.14.193h-1.473c.018-.28.193-.51.526-.65.333-.158.842-.228 1.49-.228.316 0 .596.018.86.07.262.035.472.088.613.158.175.07.315.176.385.264.07.105.106.263.106.456v1.405c0 .053.017.088.035.123.035.053.07.07.122.105v.07zm5.469-1.352h1.543c-.035.456-.28.807-.702 1.07-.42.247-.999.37-1.735.37-.824 0-1.473-.159-1.928-.492-.474-.316-.684-.773-.684-1.317 0-.562.21-1.019.666-1.352.473-.316 1.104-.492 1.91-.492.737 0 1.316.123 1.736.369.421.246.666.597.719 1.053h-1.578a.496.496 0 00-.245-.404c-.14-.087-.35-.14-.614-.14-.333 0-.56.07-.718.246-.176.158-.246.386-.246.72 0 .298.088.544.246.702.175.158.438.246.753.246.263 0 .456-.053.614-.158a.631.631 0 00.263-.421zm4.593.21a6.27 6.27 0 01-.579.106c-.368.07-.56.158-.56.28 0 .07.034.123.122.176.07.035.175.053.316.053.245 0 .42-.035.543-.123.105-.07.175-.193.175-.369 0-.035 0-.07-.017-.088v-.035zm.14 1.142l-.088-.246a2.486 2.486 0 01-.63.246c-.229.07-.474.087-.755.087-.42 0-.753-.07-.981-.21a.686.686 0 01-.35-.597.62.62 0 01.35-.58c.228-.105.666-.193 1.297-.263.07 0 .193-.018.316-.018.473-.017.718-.105.718-.228 0-.088-.052-.14-.122-.176-.088-.035-.228-.035-.421-.035-.158 0-.28.018-.35.053a.253.253 0 00-.159.193h-1.455c0-.28.176-.51.526-.65.333-.158.824-.228 1.49-.228.316 0 .596.018.86.07.262.035.473.088.613.158.175.07.298.176.368.264.07.105.105.263.105.456v1.405a.16.16 0 00.053.123c.017.053.07.07.123.105v.07zm2.104 0v-2.564h1.384v.474a.858.858 0 01.421-.404c.193-.088.438-.123.736-.123h.14v1.019c-.052-.018-.105-.018-.157-.018h-.14c-.316 0-.526.035-.667.123-.157.088-.227.228-.227.44v1.053zm7.117 0h-1.333v-.316a1.39 1.39 0 01-.543.298 2.18 2.18 0 01-.701.105c-.474 0-.86-.122-1.157-.368-.298-.246-.456-.58-.456-1.001 0-.387.158-.72.456-.966.298-.263.683-.386 1.157-.386.228 0 .42.035.613.087.175.053.35.14.491.264v-1.177h1.473zm-2.069-.668a.655.655 0 00.456-.158c.105-.105.158-.246.158-.439s-.053-.333-.158-.421c-.088-.106-.246-.158-.456-.158-.21 0-.368.052-.456.158-.105.088-.158.228-.158.421 0 .193.053.334.158.44.105.105.263.157.456.157"/><path id="path16" fill="#2350a9" d="M10.068 19.353h17.915A7.466 7.466 0 0034.89 14.7h-.841a6.66 6.66 0 01-6.066 3.898H10.068A6.68 6.68 0 014.003 14.7h-.824c1.104 2.722 3.769 4.653 6.89 4.653zM34.89 9.151a7.466 7.466 0 00-6.907-4.654H10.068c-3.12 0-5.785 1.932-6.89 4.654h.825a6.68 6.68 0 016.065-3.899h17.915a6.66 6.66 0 016.066 3.899h.841"/><path id="path18" fill="#ed1c24" d="M19.096 2.425c4.242 0 7.853 2.845 9.045 6.726H10.015c1.193-3.881 4.804-6.726 9.08-6.726zM28.14 14.7c-1.192 3.88-4.803 6.725-9.045 6.725-4.277 0-7.888-2.844-9.08-6.725H28.14"/></svg>
<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-dinacard"><title id="pi-dinacard">Dinacard</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path id="path14" fill="#2350a9" d="M3.547 12.628h.438c.403 0 .684-.07.842-.194.157-.122.245-.35.245-.65 0-.315-.088-.544-.245-.667-.158-.14-.439-.193-.824-.193h-.456zm-1.648.878v-3.46H3.88c.508 0 .877 0 1.14.035.245.036.455.088.63.158.351.14.632.334.807.597.175.264.263.58.263.949s-.105.702-.333.983c-.21.264-.544.457-.982.597a2.596 2.596 0 01-.613.106 18.43 18.43 0 01-1.21.035zm5.417-2.81v-.738h1.507v.738zm0 2.81v-2.564h1.507v2.564zm2.244 0v-2.564h1.367v.386a1.6 1.6 0 01.578-.333 2.5 2.5 0 01.737-.106c.228 0 .438.018.613.07.193.053.333.123.456.229.123.105.193.21.245.35.053.124.07.352.07.633v1.335h-1.49V12.17c0-.193-.035-.316-.122-.386-.07-.07-.21-.106-.386-.106-.193 0-.333.035-.438.123-.088.088-.123.193-.123.369v1.335zm7.275-1.142a6.63 6.63 0 01-.561.106c-.386.07-.561.158-.561.28 0 .07.035.123.105.176a.73.73 0 00.315.053c.246 0 .439-.035.544-.123.122-.07.175-.193.175-.369V12.4c0-.017 0-.035-.017-.035zm.14 1.142l-.088-.246a2.64 2.64 0 01-.613.246c-.228.07-.474.087-.754.087-.42 0-.754-.07-1-.21a.67.67 0 01-.333-.597c0-.264.106-.457.334-.58.227-.105.666-.193 1.297-.263.087 0 .193-.018.333-.018.473-.017.701-.105.701-.228 0-.088-.035-.14-.123-.176-.087-.035-.228-.035-.42-.035a.982.982 0 00-.351.053c-.088.035-.123.105-.14.193h-1.473c.018-.28.193-.51.526-.65.333-.158.842-.228 1.49-.228.316 0 .596.018.86.07.262.035.472.088.613.158.175.07.315.176.385.264.07.105.106.263.106.456v1.405c0 .053.017.088.035.123.035.053.07.07.122.105v.07zm5.469-1.352h1.543c-.035.456-.28.807-.702 1.07-.42.247-.999.37-1.735.37-.824 0-1.473-.159-1.928-.492-.474-.316-.684-.773-.684-1.317 0-.562.21-1.019.666-1.352.473-.316 1.104-.492 1.91-.492.737 0 1.316.123 1.736.369.421.246.666.597.719 1.053h-1.578a.496.496 0 00-.245-.404c-.14-.087-.35-.14-.614-.14-.333 0-.56.07-.718.246-.176.158-.246.386-.246.72 0 .298.088.544.246.702.175.158.438.246.753.246.263 0 .456-.053.614-.158a.631.631 0 00.263-.421zm4.593.21a6.27 6.27 0 01-.579.106c-.368.07-.56.158-.56.28 0 .07.034.123.122.176.07.035.175.053.316.053.245 0 .42-.035.543-.123.105-.07.175-.193.175-.369 0-.035 0-.07-.017-.088v-.035zm.14 1.142l-.088-.246a2.486 2.486 0 01-.63.246c-.229.07-.474.087-.755.087-.42 0-.753-.07-.981-.21a.686.686 0 01-.35-.597.62.62 0 01.35-.58c.228-.105.666-.193 1.297-.263.07 0 .193-.018.316-.018.473-.017.718-.105.718-.228 0-.088-.052-.14-.122-.176-.088-.035-.228-.035-.421-.035-.158 0-.28.018-.35.053a.253.253 0 00-.159.193h-1.455c0-.28.176-.51.526-.65.333-.158.824-.228 1.49-.228.316 0 .596.018.86.07.262.035.473.088.613.158.175.07.298.176.368.264.07.105.105.263.105.456v1.405a.16.16 0 00.053.123c.017.053.07.07.123.105v.07zm2.104 0v-2.564h1.384v.474a.858.858 0 01.421-.404c.193-.088.438-.123.736-.123h.14v1.019c-.052-.018-.105-.018-.157-.018h-.14c-.316 0-.526.035-.667.123-.157.088-.227.228-.227.44v1.053zm7.117 0h-1.333v-.316a1.39 1.39 0 01-.543.298 2.18 2.18 0 01-.701.105c-.474 0-.86-.122-1.157-.368-.298-.246-.456-.58-.456-1.001 0-.387.158-.72.456-.966.298-.263.683-.386 1.157-.386.228 0 .42.035.613.087.175.053.35.14.491.264v-1.177h1.473zm-2.069-.668a.655.655 0 00.456-.158c.105-.105.158-.246.158-.439s-.053-.333-.158-.421c-.088-.106-.246-.158-.456-.158-.21 0-.368.052-.456.158-.105.088-.158.228-.158.421 0 .193.053.334.158.44.105.105.263.157.456.157"/><path id="path16" fill="#2350a9" d="M10.068 19.353h17.915A7.466 7.466 0 0034.89 14.7h-.841a6.66 6.66 0 01-6.066 3.898H10.068A6.68 6.68 0 014.003 14.7h-.824c1.104 2.722 3.769 4.653 6.89 4.653zM34.89 9.151a7.466 7.466 0 00-6.907-4.654H10.068c-3.12 0-5.785 1.932-6.89 4.654h.825a6.68 6.68 0 016.065-3.899h17.915a6.66 6.66 0 016.066 3.899h.841"/><path id="path18" fill="#ed1c24" d="M19.096 2.425c4.242 0 7.853 2.845 9.045 6.726H10.015c1.193-3.881 4.804-6.726 9.08-6.726zM28.14 14.7c-1.192 3.88-4.803 6.725-9.045 6.725-4.277 0-7.888-2.844-9.08-6.725H28.14"/></svg>
</br>
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)
When we (CorvusPay) required about the possibility of adding DinaCard icon in payment method, we got answer from Miguel Q that we need to add icon here (ticket 44582605).

What's the expected date of this change to deploy on Shopify?
As soon as it is possible.

### CODE REVIEW

**Review by Lovedanihonjin — CHANGES_REQUESTED** [review]
The typography on the Dinacard looks different in the SVG than the actual logo. Do you happen to have the source file for the logo
Screenshot 2024-05-09 at 9 25 52 AM
?

**Comment by ALibrenjak-Corvuspay** [comment]
Improved version of image is uploaded.
Conflicts are resolved.

**Review by Lovedanihonjin — APPROVED** [review]
SVG file looks good. Thank you!

**Comment by adeniyiao** [comment]
Hi @ALibrenjak-Corvuspay ,

Your PR shows more files changes are being made than required. Could you please rebase this PR against activemerchant:master or preferably closing this PR and submitting a new PR as there are too many commits to follow through the changes. You should only be adding your new icon and adding it to the `db/payment_icons.yml` only

Thanks

**Comment by ALibrenjak-Corvuspay** [comment]
Hi @adeniyiao,
New pull request is https://github.com/activemerchant/payment_icons/pull/1185.

**Pull request closed without merging**
