### PR TITLE
Duitnow logo

### PR DESCRIPTION
**Pull request by spacemonkey92**
## Why are you adding this icons?
I'm adding/updating this icon because HitPay payment gateway now supports duitnow Payment Method 
https://www.shopify.com/sg/payment-gateways/singapore

#### Help us identify yourself
- [x] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

```
<!-- Change background color if needed to showcase your icon better -->
<style> body { background: black; } </style>

<!-- DO NOT DELETE EXAMPLE -->
<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<!-- TODO: insert your icon here -->
<YOUR SVG CODE>

<br>
<!-- TODO: insert your icon here -->
<YOUR SVG CODE>
</br
```

### CODE REVIEW

**Comment by Jacquesattaque** [comment]
@spacemonkey92 Do you still need this icon? If not, I will close the issue.

**Comment by spacemonkey92** [comment]
hi, @Jacquesattaque  sorry lost the notification. 
Let me update the PR, please do not close this issue. 

Thank you!

**Review by dmrkv — CHANGES_REQUESTED** [review]
Technically the icon is OK, but there are 2 problems with the logo:
1. looks like logo is scaled vertically, so it is kinda vertically compressed
2. letters/words under the image is so small, so they are not readable and only add visual noise. Maybe version with just image and without text will look better and be more readable  and accessible

**Comment by spacemonkey92** [comment]
> Technically the icon is OK, but there are 2 problems with the logo:
> 
> 1. looks like logo is scaled vertically, so it is kinda vertically compressed
> 2. letters/words under the image is so small, so they are not readable and only add visual noise. Maybe version with just image and without text will look better and be more readable  and accessible

hey @Jacquesattaque 
Thanks for the feedback, but we also have to respect the brand guidelines 
https://www.duitnow.my/img/assets/DNQR_Brand%20Guidelines_2021.pdf
https://www.duitnow.my/QR/media-bank.html

That's the reason I would prefer not to make any changes to the logo. 
Let me know if you think this is reasonable, If not we can consider updating the logo without the text.

**Comment by Jacquesattaque** [comment]
@spacemonkey92 That makes sense — it looks like the brand uses the icon with the Duit Now text but without QR, which should help. You'll still need to replace the bitmap image with vector graphics though before we approve. You should be able to reach out to the brand for a vector logo.

**Comment by spacemonkey92** [comment]
> @spacemonkey92 That makes sense — it looks like the brand uses the icon with the Duit Now text but without QR, which should help. You'll still need to replace the bitmap image with vector graphics though before we approve. You should be able to reach out to the brand for a vector logo.

hi @Jacquesattaque 
I have updated the image from base64 to SVG. Please review and let me know! 
Thank you!

**Review by Jacquesattaque — CHANGES_REQUESTED** [review]
Icon looks much better, but please run it through the SVGO optimizer to reduce file size.

**Comment by spacemonkey92** [comment]
> Icon looks much better, but please run it through the SVGO optimizer to reduce file size.

Done! @Jacquesattaque

**Comment by adeniyiao** [comment]
Hi @spacemonkey92 , could you please fix the issues raised in the failed test, in line 15 and 23

image

**Comment by spacemonkey92** [comment]
hey @adeniyiao I have fixed the issue. Could you please re-run the action? Thank you!

**Comment by spacemonkey92** [comment]
hi, @adeniyiao can you please retrigger the job? I have fixed the issues.

**Comment by adeniyiao** [comment]
Hi @spacemonkey92 ,

Another failed test to address..

image

**Comment by spacemonkey92** [comment]
Hi @adeniyiao 
The role tag has been added. Please re-run the tests. 

Thank you!

**Review by Jacquesattaque — APPROVED** [review]

**Comment by spacemonkey92** [comment]
hey @adeniyiao thanks for the merge. 
May i know when will this logo be deployed to the shopify platform?

**Pull request merged**
