### PR TITLE
Stylesheet

### PR DESCRIPTION
**Pull request by joshnuss**
It would be useful to have a stylesheet inside this engine.

The stylesheet is generated dynamically based on the current icons. This way, if we modify the icon set in the future, the stylesheet will update automatically.

To include it:

```scss
@import "payment_icons/payment_icons"
```

### CODE REVIEW

**Comment by Edouard-chin** [comment]
Thanks!

**Comment by SebastianSzturo** [comment]
Can we 🚢  this?

**Comment by Edouard-chin** [comment]
@SebastianSzturo Looks like there is issues in Shopify core with `*.scss.erb` file, will have to dig.

**Comment by Edouard-chin** [comment]
This PR is good to go

**Pull request merged**
