### PR TITLE
Taly new icon

### PR DESCRIPTION
**Pull request by rakholiyasaurav535**
## Why are you adding this icons?
I'm adding/updating this icon(s) because we are developing an offsite payment app in shopify.

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

image

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?
- 30 Dec 2023

### CODE REVIEW

**Review by miteshpanchal1992 — APPROVED** [review]

**Comment by rakholiyasaurav535** [comment]
I've added the Ruby 2.7 rails edge to be excluded as mentioned in #1121

**Comment by adeniyiao** [comment]
Hi @rakholiyasaurav535 we addressed the ruby version issue, but we need you to rebase your branch `rakholiyasaurav535:taly_new_icon` with `activemerchant/master` as well. Also the test fails due to issue with SVG as described in screenshot below

image

**Comment by rakholiyasaurav535** [comment]
Hey @adeniyiao I've made the changes and svg file and rebased my branch as well, please review it ASAP

**Comment by adeniyiao** [comment]
> Hey @adeniyiao I've made the changes and svg file and rebased my branch as well, please review it ASAP

HI @rakholiyasaurav535, there's another test failing with the svg as seen below. Kindly look into it. Thanks
image


```
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:89]:
{:message=>"The 'paint0_linear_4947_4625' ID should be pi-taly-paint0_linear_4947_4625 (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "paint0_linear_4947_4625".
```

**Comment by rakholiyasaurav535** [comment]
Hey @adeniyiao I've added the pi prefix to the ID

**Comment by adeniyiao** [comment]
Hi @rakholiyasaurav535 ,

Another error

`Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:93]:
{:message=>"The 'taly' SVG file should have a 'role' attribute on the root <svg> tag"}`

**Comment by rakholiyasaurav535** [comment]
Hey @adeniyiao 

I've added the role attribute ran the github action locally to verify if there's any other change to be made and seems like there's no more, hope this get's merge ASAP now.

**Comment by hellicarusprime** [comment]
Hi @rakholiyasaurav535 I noticed you're using a gradient fill on the background of the icon. Would it be possible to change this to a solid background color? We request this in [our guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance) whenever possible. Have you also considered adding the border that we suggest there?

**Comment by rakholiyasaurav535** [comment]
Hey @hellicarusprime We've updated the svg as per the requirements

**Comment by hellicarusprime** [comment]
> Hey @hellicarusprime We've updated the svg as per the requirements

Thanks for the update @rakholiyasaurav535, but it looks like you've got a 4px border-radius now instead of the required 2px.

**Comment by miteshpanchal1992** [comment]
Hi @hellicarusprime Now we have to change "rx" attribute value to be 2 only right?

**Comment by rakholiyasaurav535** [comment]
Hey @hellicarusprime, Thanks for pointing out the border-radius issue, I've adjusted it to 2px as needed.

**Comment by hellicarusprime** [comment]
> Hey @hellicarusprime, Thanks for pointing out the border-radius issue, I've adjusted it to 2px as needed.

Hey @rakholiyasaurav535 It doesn't look like it's changed.

**Comment by rakholiyasaurav535** [comment]
Hey @hellicarusprime check now

**Comment by hellicarusprime** [comment]
@rakholiyasaurav535 You have a different issue now. Although the icon is 38 x 24, it's displaying too small due to the fact that it doesn't have a border. I've attached an example of what we need to help explain.
image

**Comment by rakholiyasaurav535** [comment]
hey @hellicarusprime check now

**Comment by hellicarusprime** [comment]
@rakholiyasaurav535 This is much better! One last thing, it looks like you can reduce the file size by ~55% if you run it through [SVGO](https://jakearchibald.github.io/svgomg/). Once this is done, I'll be happy to approve. Thanks!

**Comment by rakholiyasaurav535** [comment]
@hellicarusprime I've reduced the size

**Review by hellicarusprime — APPROVED** [review]

**Comment by miteshpanchal1992** [comment]
@hellicarusprime Is there anything pending from our end now?

**Comment by adeniyiao** [comment]
Hi @miteshpanchal1992 Could you please rebase this branch with activemerchant/master to resolve the conflicts. Thanks.

The next release is planned for Feb 7.

**Comment by rakholiyasaurav535** [comment]
hey @adeniyiao I've rebased the branch, do let me know if there is anything else pending from our end

**Comment by adeniyiao** [comment]
Hi @rakholiyasaurav535 , it looks like the rebase was not done correctly as there are other files in the PR this PR that shouldn't be included as they are already merged. Could you please review and correct. 
Thanks

**Comment by rakholiyasaurav535** [comment]
Hey @adeniyiao check now

**Comment by adeniyiao** [comment]
Still doesn't look right. May be close the PR and open another one as you will see that you have more files  (https://github.com/activemerchant/payment_icons/pull/1120/files) than expected in this PR

**Comment by rakholiyasaurav535** [comment]
Hey @adeniyiao 

I've created a new [Pull Request](https://github.com/activemerchant/payment_icons/pull/1143) please get this merged ASAP

**Pull request closed without merging**
