### PR TITLE
add already existing generic card icon to db.yml

### PR DESCRIPTION
**Pull request by d11n**

### CODE REVIEW

**Comment by tauthomas01** [comment]
Hi @d11n ,

Thank you for your contribution. Out of curiosity, do you have an example or demo store where this generic card icon is used?

**Comment by d11n** [comment]
Unfortunately no. We're using this in an app for governments, so it's not open to the public and there isn't a demo/example of the payment experience. I actually included the generic icon in fallback logic, but only noticed it wasn't in the database because of a bug in our code. But when the generic icon is used, the experience looks like:

screenshot-20190607-112841

which isn't especially ideal, but was the path of least resistance.

**Comment by NathanPJF** [comment]
@d11n That's neat! Is placing the generic icon in the `payment_icons` database file necessary to solve your issue? Could your app display the generic SVG as a fallback when it encounters a missing icon? 

I'm hesitant to add this generic template amongst the list of "real" payment options.  For example, ee have a [bogus gateway](https://github.com/activemerchant/payment_icons/blob/bd162be42b31a7b5f8ab3d2eebf874907ae637f6/app/assets/images/payment_icons/bogus.svg) icon in the repo, but we haven't needed it in the `db/payment_icons.yml` file to use it.

**Comment by d11n** [comment]
I see what you mean. Were I more familiar with rails, I would have known to access the icon via other means. For my purposes, this works as a fallback when a card isn't found:
```ruby
image_tag(
    asset_path('payment_icons/generic.svg'),
    ...
)
```
Thanks for pointing me in the right direction.

**Pull request closed without merging**
